name: "Deploy to nuget.org"
description: "Deploy to nuget.org"

inputs:
  token:
    description: "The token to use for nuget publishing"
    required: true

runs:
  using: "composite"

  steps:
  - name: Download Artifacts
    uses: actions/download-artifact@v4
    with:
        name: NuGet-Signed
        path: artifacts

  - uses: actions/setup-dotnet@v4
    with:
      dotnet-version: '9.0.x'

  - name: Uno NuGet Feed Push
    shell: pwsh
    env:
      FEED_ENDPOINT: https://pkgs.dev.azure.com/uno-platform/1dd81cbd-cb35-41de-a570-b0df3571a196/_packaging/unoplatformdev/nuget/v3/index.json
      NUGET_AUTH_TOKEN: ${{ inputs.token }}
    run: |
        dotnet nuget push artifacts/*.nupkg --source $env:FEED_ENDPOINT --api-key AzureDevOps --skip-duplicate
