jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - template: build/templates/gitversion-run.yml

  - task: UseDotNet@2
    displayName: 'Use .NET 10 SDK'
    inputs:
      version: 10.x
  
  - script: dotnet workload install wasm-tools wasm-tools-net9
    displayName: Install workloads

  - task: DotNetCoreCLI@2
    inputs:
      command: build      
      projects: MonacoEditorComponent.slnx
      arguments:  -c Release -p:ArtifactsPath=$(Build.ArtifactStagingDirectory) /bl:$(Build.ArtifactStagingDirectory)/log/build.binlog 

  # - task: PowerShell@2
  #   displayName: Authenticode Sign Packages
  #   inputs:
  #     filePath: build/Sign-Package.ps1
  #   env:
  #     SignClientUser: $(SignClientUser)
  #     SignClientSecret: $(SignClientSecret)
  #     SignPackageName: "uno.monaco-editor-uwp"
  #     SignPackageDescription: "uno.monaco-editor-uwp"
  #     ArtifactDirectory: $(Build.ArtifactStagingDirectory)
  #   condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

  - publish: $(Build.ArtifactStagingDirectory)/package/release
    displayName: Publish Build Logs
    condition: always()
    artifact: packages

  - publish: $(Build.ArtifactStagingDirectory)/log
    displayName: Publish Build Logs
    condition: always()
    artifact: logs

