<Project ToolsVersion="15.0">
  <!--
    To update the version of Uno, you should instead update the Sdk version in the global.json file.

    See https://aka.platform.uno/using-uno-sdk for more information.
    See https://aka.platform.uno/using-uno-sdk#implicit-packages for more information regarding the Implicit Packages.
  -->
  <ItemGroup>
    <PackageVersion Include="Nito.AsyncEx" Version="5.1.2" />
    <PackageVersion Include="StreamJsonRpc" Version="2.24.84" />
    <PackageVersion Include="Uno.CommunityToolkit.WinUI" Version="7.1.204" />
    <PackageVersion Include="Uno.WinUI" Version="6.5.153" />
    <PackageVersion Include="Uno.Core.Extensions.Logging" Version="4.1.1" />
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.1.1" />
    <PackageVersion Include="Microsoft.TypeScript.MSBuild" Version="5.9.3" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />    
    <PackageVersion Include="Microsoft.Playwright" Version="1.58.0" />
    <PackageVersion Include="Microsoft.Playwright.Xunit.v3" Version="1.58.0" />
    <PackageVersion Include="Nerdbank.Streams" Version="2.13.16" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.4.1" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.0.2" />
    <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.8.118"/>
  </ItemGroup>
</Project>