// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages.Json
{
    /// <summary>
    /// A JSON Schema definition.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.json.IJSONSchema.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IJSONSchema, JSONSchema>))]
    public partial interface IJSONSchema
    {
        [JsonPropertyName("$comment")]
        string? Comment { get; set; }

        [JsonPropertyName("$id")]
        string? Id { get; set; }

        [JsonPropertyName("$ref")]
        string? Ref { get; set; }

        [JsonPropertyName("$schema")]
        string? Schema { get; set; }

        string? Title { get; set; }

    }
}