// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages.Json
{
    /// <summary>
    /// A JSON Schema definition.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.json.IJSONSchema.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class JSONSchema : IJSONSchema
    {
        [JsonPropertyName("$comment")]
        public string? Comment { get; set; }

        [JsonPropertyName("$id")]
        public string? Id { get; set; }

        [JsonPropertyName("$ref")]
        public string? Ref { get; set; }

        [JsonPropertyName("$schema")]
        public string? Schema { get; set; }

        public string? Title { get; set; }

    }
}