// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for the editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IGlobalEditorOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IGlobalEditorOptions, GlobalEditorOptions>))]
    public partial interface IGlobalEditorOptions
    {
        /// <summary>
        /// Controls whether the semanticHighlighting is shown for the languages that support it.
        /// </summary>
        [JsonPropertyName("semanticHighlighting.enabled")]
        object? SemanticHighlightingEnabled { get; set; }

        /// <summary>
        /// The number of spaces a tab is equal to.
        /// </summary>
        double? TabSize { get; set; }

    }
}
