// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Accessibility options for the editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IAccessibilityOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IAccessibilityOptions, AccessibilityOptions>))]
    public partial interface IAccessibilityOptions
    {
        /// <summary>
        /// The ARIA label for the editor.
        /// </summary>
        [JsonPropertyName("aria-label")]
        string? AriaLabel { get; set; }

        /// <summary>
        /// Whether accessibility is enabled.
        /// </summary>
        bool? Enabled { get; set; }

    }
}
