// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <summary>
    /// A universal resource identifier representing either a file on disk or another resource.
    /// </summary>
    public sealed class Uri
    {
        /// <summary>
        /// scheme is the 'http' part of 'http://www.example.com/some/path?query#fragment'.
        /// </summary>
        public string Scheme { get; }

        /// <summary>
        /// authority is the 'www.example.com' part.
        /// </summary>
        public string Authority { get; }

        /// <summary>
        /// path is the '/some/path' part.
        /// </summary>
        public string Path { get; }

        /// <summary>
        /// query is the 'query' part.
        /// </summary>
        public string Query { get; }

        /// <summary>
        /// fragment is the 'fragment' part.
        /// </summary>
        public string Fragment { get; }

        public string ToString() => throw new NotImplementedException();

    }
}