// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <summary>
    /// Marker severity levels.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/MarkerSeverity.html">Monaco API</see> for more details.
    /// </remarks>
    public enum MarkerSeverity
    {
        /// <summary>
        /// A hint marker severity.
        /// </summary>
        Hint = 1,
        /// <summary>
        /// An informational marker severity.
        /// </summary>
        Info = 2,
        /// <summary>
        /// A warning marker severity.
        /// </summary>
        Warning = 4,
        /// <summary>
        /// An error marker severity.
        /// </summary>
        Error = 8
    }
}
