// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <summary>
    /// Marker severity levels.
    /// </summary>
    public enum MarkerSeverity
    {
        Hint = 1,
        Info = 2,
        Warning = 4,
        Error = 8
    }
}