// <auto-generated />
#nullable enable
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Control the cursor style.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/types/editor.CursorStyle.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(JsonStringEnumConverter<CursorStyle>))]
    public enum CursorStyle
    {
        [JsonStringEnumMemberName("block")]
        [EnumMember(Value = "block")]
        Block,
        [JsonStringEnumMemberName("block-outline")]
        [EnumMember(Value = "block-outline")]
        BlockOutline,
        [JsonStringEnumMemberName("line")]
        [EnumMember(Value = "line")]
        Line,
        [JsonStringEnumMemberName("line-thin")]
        [EnumMember(Value = "line-thin")]
        LineThin,
        [JsonStringEnumMemberName("underline")]
        [EnumMember(Value = "underline")]
        Underline,
        [JsonStringEnumMemberName("underline-thin")]
        [EnumMember(Value = "underline-thin")]
        UnderlineThin
    }
}