// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <summary>
    /// A position in the editor. This interface is suitable for serialization.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/classes/Position.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class Position
    {
        /// <summary>
        /// line number (starts at 1)
        /// </summary>
        public double LineNumber { get; }

        /// <summary>
        /// column (the first character in a line is between column 1 and column 2)
        /// </summary>
        public double Column { get; }

        public Position(double lineNumber, double column)
        {
            LineNumber = lineNumber;
            Column = column;
        }

        /// <summary>
        /// Test if `obj` is an `IPosition`.
        /// </summary>
        /// <returns>True if the argument satisfies the TypeScript type predicate <c>obj is IPosition</c>.</returns>
        public static bool IsIPosition(object obj) => throw new NotImplementedException();

        /// <summary>
        /// Test if `$node` is an `IPosition` (dollar-prefixed parameter).
        /// </summary>
        /// <returns>True if the argument satisfies the TypeScript type predicate <c>$node is IPosition</c>.</returns>
        public static bool IsIPositionDollar(object node) => throw new NotImplementedException();

        /// <summary>
        /// Test if `this` is a `Position`-like object.
        /// </summary>
        /// <returns>True if the argument satisfies the TypeScript type predicate <c>this is IPosition</c>.</returns>
        public bool IsPositionLike() => throw new NotImplementedException();

        /// <summary>
        /// Test if position `a` equals position `b`.
        /// </summary>
        /// <returns>A boolean value.</returns>
        public static bool Equals(IPosition a, IPosition b) => throw new NotImplementedException();

    }
}