// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IAutoClosingPairConditional.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class AutoClosingPairConditional : IAutoClosingPairConditional
    {
        public string[]? NotIn { get; set; }

    }
}
