// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IAutoClosingPair.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class AutoClosingPair : IAutoClosingPair
    {
        public string Close { get; set; }

        public string Open { get; set; }

    }
}
