// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CodeLensList.html">Monaco API</see> for more details.
    /// </remarks>
    public interface CodeLensList
    {
        CodeLens[] Lenses { get; set; }

        void Dispose();

    }
}
