// <auto-generated />
#nullable enable
using Monaco;
using Monaco.Editor;
using System.Text.Json.Serialization;

namespace Monaco.Languages
{
    /// <summary>
    /// Contains additional diagnostic information about the context in which
    /// a [code action](#CodeActionProvider.provideCodeActions) is run.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CodeActionContext.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class CodeActionContext
    {
        /// <summary>
        /// An array of diagnostics.
        /// </summary>
        public MarkerData[]? Markers { get; set; } // TODO: Should setup the serialization mappings between interfaces to leave interfaces here...

        /// <summary>
        /// Requested kind of actions to return.
        /// </summary>
        public string? Only { get; set; }
    }
}

