// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CodeLens.html">Monaco API</see> for more details.
    /// </remarks>
    public interface CodeLens
    {
        Command? Command { get; set; }

        string? Id { get; set; }

        IRange Range { get; set; }

    }
}
