// <auto-generated />
#nullable enable
using Monaco;
using Monaco.Editor;

namespace Monaco.Languages
{
    /// <summary>
    /// Represents a list of code actions provided by a code action provider.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CodeActionList.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class CodeActionList // IDisposable??
    {
        /// <summary>
        /// Gets or sets the array of code actions.
        /// </summary>
        public CodeAction[]? Actions { get; set; }

    }
}

