// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// /**
    ///      * Metadata about the type of code actions that a {@link CodeActionProvider}provides.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CodeActionProviderMetadata.html">Monaco API</see> for more details.
    /// </remarks>
    public interface CodeActionProviderMetadata
    {
        object[]? Documentation { get; }

        /// <summary>
        /// /**
        ///          * List of code action kinds that a {@link CodeActionProvider}may return.
        ///          *
        ///          * This list is used to determine if a given `CodeActionProvider` should be invoked or not.
        ///          * To avoid unnecessary computation, every `CodeActionProvider` should list use `providedCodeActionKinds`. The
        ///          * list of kinds may either be generic, such as `["quickfix", "refactor", "source"]`, or list out every kind provided,
        ///          * such as `["quickfix.removeLine", "source.fixAll" ...]`.
        /// </summary>
        string[]? ProvidedCodeActionKinds { get; }

    }
}
