// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CommentAuthorInformation.html">Monaco API</see> for more details.
    /// </remarks>
    public interface CommentAuthorInformation
    {
        UriComponents? IconPath { get; set; }

        string Name { get; set; }

    }
}
