// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// Describes how comments for a language work.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CommentRule.html">Monaco API</see> for more details.
    /// </remarks>
    public interface CommentRule
    {
        /// <summary>
        /// The block comment character pair, like `/* block comment *&amp;#47;`
        /// </summary>
        CharacterPair? BlockComment { get; set; }

        /// <summary>
        /// The line comment token, like `// this is a comment`
        /// </summary>
        string? LineComment { get; set; }

    }
}
