// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.Command.html">Monaco API</see> for more details.
    /// </remarks>
    public interface Command
    {
        object[]? Arguments { get; set; }

        string Id { get; set; }

        string Title { get; set; }

        string? Tooltip { get; set; }

    }
}
