// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// /**
    ///      * Contains additional information about the context in which
    ///      * {@link CompletionItemProvider.provideCompletionItems completion provider}is triggered.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CompletionContext.html">Monaco API</see> for more details.
    /// </remarks>
    public interface CompletionContext
    {
        /// <summary>
        /// Character that triggered the completion item provider.
        ///
        /// `undefined` if provider was not triggered by a character.
        /// </summary>
        string? TriggerCharacter { get; set; }

        /// <summary>
        /// How the completion was triggered.
        /// </summary>
        CompletionTriggerKind TriggerKind { get; set; }

    }
}
