// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages
{
    /// <summary>
    /// Represents a list of completion items provided by a completion provider.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CompletionList.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class CompletionList
    {
        /// <summary>
        /// Gets or sets a value indicating whether this list is incomplete and should be re-queried as the user continues typing.
        /// </summary>
        public bool? Incomplete { get; set; }

        /// <summary>
        /// Gets or sets the array of completion suggestions.
        /// </summary>
        public CompletionItem[]? Suggestions { get; set; }
    }
}
