// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CompletionItemLabel.html">Monaco API</see> for more details.
    /// </remarks>
    public interface CompletionItemLabel
    {
        string? Description { get; set; }

        string? Detail { get; set; }

        string Label { get; set; }

    }
}
