// <auto-generated />
#nullable enable
﻿namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/languages.CompletionItemInsertTextRule.html">Monaco API</see> for more details.
    /// </remarks>
    public enum CompletionItemInsertTextRule
    {
        /// <summary>
        /// `insertText` is a snippet.
        /// </summary>
        InsertAsSnippet = 4,
        /// <summary>
        /// Adjust whitespace/indentation of multiline insert texts to
        /// match the current line indentation.
        /// </summary>
        KeepWhitespace = 1
    }
}