// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages
{
    /// <summary>
    /// Contains additional information about the context in which
    /// [completion provider](#CompletionItemProvider.provideCompletionItems) is triggered.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CompletionContext.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class CompletionContext
    {
        /// <summary>
        /// Character that triggered the completion item provider.
        ///
        /// `undefined` if provider was not triggered by a character.
        /// </summary>
        public string? TriggerCharacter { get; set; }

        /// <summary>
        /// How the completion was triggered.
        /// </summary>
        public CompletionTriggerKind TriggerKind { get; set; }
    }
}
