// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// Definition of documentation comments (e.g. Javadoc/JSdoc)
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IDocComment.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class DocComment : IDocComment
    {
        /// <summary>
        /// The string that appears on the last line and closes the doc comment (e.g. ' * /').
        /// </summary>
        public string? Close { get; set; }

        /// <summary>
        /// The string that starts a doc comment (e.g. '/**')
        /// </summary>
        public string Open { get; set; }

    }
}
