// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <summary>
    /// The document formatting provider interface defines the contract between extensions and
    /// the formatting-feature.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.DocumentRangeFormattingEditProvider.html">Monaco API</see> for more details.
    /// </remarks>
    public interface DocumentRangeFormattingEditProvider
    {
        string? DisplayName { get; }

        /// <summary>
        /// Provide formatting edits for a range in a document.
        ///
        /// The given range is a hint and providers can decide to format a smaller
        /// or larger range. Often this is done by adjusting the start and end
        /// of the range to full syntax nodes.
        /// </summary>
        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<TextEdit[]> ProvideDocumentRangeFormattingEdits(editor.ITextModel model, Range range, FormattingOptions options, CancellationToken token);

        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<TextEdit[]> ProvideDocumentRangesFormattingEdits(editor.ITextModel model, Range[] ranges, FormattingOptions options, CancellationToken token);

    }
}
