// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.DocumentContextItem.html">Monaco API</see> for more details.
    /// </remarks>
    public interface DocumentContextItem
    {
        IRange[] Ranges { get; }

        Uri Uri { get; }

        double Version { get; }

    }
}
