// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <summary>
    /// A document highlight is a range inside a text document which deserves
    /// special attention. Usually a document highlight is visualized by changing
    /// the background color of its range.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.DocumentHighlight.html">Monaco API</see> for more details.
    /// </remarks>
    public interface DocumentHighlight
    {
        /// <summary>
        /// /**
        ///          * The highlight kind, default is {@link DocumentHighlightKind.Text text}.
        /// </summary>
        DocumentHighlightKind? Kind { get; set; }

        /// <summary>
        /// The range this highlight applies to.
        /// </summary>
        IRange Range { get; set; }

    }
}
