// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.DocumentSymbol.html">Monaco API</see> for more details.
    /// </remarks>
    public interface DocumentSymbol
    {
        DocumentSymbol[]? Children { get; set; }

        string? ContainerName { get; set; }

        string Detail { get; set; }

        SymbolKind Kind { get; set; }

        string Name { get; set; }

        IRange Range { get; set; }

        IRange SelectionRange { get; set; }

        SymbolTag[] Tags { get; set; }

    }
}
