// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <summary>
    /// The document symbol provider interface defines the contract between extensions and
    /// the [go to symbol](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol)-feature.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.DocumentSymbolProvider.html">Monaco API</see> for more details.
    /// </remarks>
    public interface DocumentSymbolProvider
    {
        string? DisplayName { get; set; }

        /// <summary>
        /// Provide symbol information for the given document.
        /// </summary>
        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<DocumentSymbol[]> ProvideDocumentSymbols(editor.ITextModel model, CancellationToken token);

    }
}
