// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <summary>
    /// A provider of folding ranges for editor models.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.FoldingRangeProvider.html">Monaco API</see> for more details.
    /// </remarks>
    public interface FoldingRangeProvider
    {
        /// <summary>
        /// An optional event to signal that the folding ranges from this provider have changed.
        /// </summary>
        IEvent<object>? OnDidChange { get; set; }

        /// <summary>
        /// Provides the folding ranges for a specific model.
        /// </summary>
        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<FoldingRange[]> ProvideFoldingRanges(editor.ITextModel model, FoldingContext context, CancellationToken token);

    }
}
