// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// Describes folding rules for a language.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.FoldingRules.html">Monaco API</see> for more details.
    /// </remarks>
    public interface FoldingRules
    {
        /// <summary>
        /// Region markers used by the language.
        /// </summary>
        FoldingMarkers? Markers { get; set; }

        /// <summary>
        /// Used by the indentation based strategy to decide whether empty lines belong to the previous or the next block.
        /// A language adheres to the off-side rule if blocks in that language are expressed by their indentation.
        /// See [wikipedia](https://en.wikipedia.org/wiki/Off-side_rule) for more information.
        /// If not set, `false` is used and empty lines belong to the previous block.
        /// </summary>
        bool? OffSide { get; set; }

    }
}
