// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.HoverVerbosityRequest.html">Monaco API</see> for more details.
    /// </remarks>
    public interface HoverVerbosityRequest<THover>
    {
        /// <summary>
        /// The previous hover for the same position
        /// </summary>
        THover PreviousHover { get; set; }

        /// <summary>
        /// The delta by which to increase/decrease the hover verbosity level
        /// </summary>
        double VerbosityDelta { get; set; }

    }
}
