// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.HoverContext.html">Monaco API</see> for more details.
    /// </remarks>
    public interface HoverContext<THover>
    {
        /// <summary>
        /// Hover verbosity request
        /// </summary>
        HoverVerbosityRequest<THover>? VerbosityRequest { get; set; }

    }
}
