// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IAutoClosingPairConditional.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IAutoClosingPairConditional, AutoClosingPairConditional>))]
    public interface IAutoClosingPairConditional : IAutoClosingPair
    {
        string[]? NotIn { get; set; }

    }
}
