// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IAutoClosingPair.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IAutoClosingPair, AutoClosingPair>))]
    public interface IAutoClosingPair
    {
        string Close { get; set; }

        string Open { get; set; }

    }
}
