// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages
{
    /// <summary>
    /// String representations for a color
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IColorPresentation.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IColorPresentation, ColorPresentation>))]
    public interface IColorPresentation
    {
        /// <summary>
        /// /**
        ///          * An optional array of additional {@link TextEdit text edits}that are applied when
        ///          * selecting this color presentation.
        /// </summary>
        TextEdit[]? AdditionalTextEdits { get; set; }

        /// <summary>
        /// The label of this color presentation. It will be shown on the color
        /// picker header. By default this is also the text that is inserted when selecting
        /// this color presentation.
        /// </summary>
        string Label { get; set; }

        /// <summary>
        /// /**
        ///          * An {@link TextEdit edit}which is applied to a document when selecting
        ///          * this presentation for the color.
        /// </summary>
        TextEdit? TextEdit { get; set; }

    }
}
