// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IExpandedMonarchLanguageRule.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IExpandedMonarchLanguageRule, ExpandedMonarchLanguageRule>))]
    public interface IExpandedMonarchLanguageRule
    {
        /// <summary>
        /// action to take on match
        /// </summary>
        IMonarchLanguageAction? Action { get; set; }

        /// <summary>
        /// or an include rule. include all rules from the included state
        /// </summary>
        string? Include { get; set; }

        /// <summary>
        /// match tokens
        /// </summary>
        object? Regex { get; set; }

    }
}
