// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Languages
{
    /// <summary>
    /// A link inside the editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.ILink.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ILink, Link>))]
    public interface ILink
    {
        IRange Range { get; set; }

        string? Tooltip { get; set; }

        object? Url { get; set; }

    }
}
