// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <summary>
    /// The implementation provider interface defines the contract between extensions and
    /// the go to implementation feature.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.ImplementationProvider.html">Monaco API</see> for more details.
    /// </remarks>
    public interface ImplementationProvider
    {
        /// <summary>
        /// Provide the implementation of the symbol at the given position and document.
        /// </summary>
        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<object> ProvideImplementation(editor.ITextModel model, Position position, CancellationToken token);

    }
}
