// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// Describes indentation rules for a language.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IndentationRule.html">Monaco API</see> for more details.
    /// </remarks>
    public interface IndentationRule
    {
        /// <summary>
        /// If a line matches this pattern, then all the lines after it should be unindented once (until another rule matches).
        /// </summary>
        string DecreaseIndentPattern { get; set; }

        /// <summary>
        /// If a line matches this pattern, then all the lines after it should be indented once (until another rule matches).
        /// </summary>
        string IncreaseIndentPattern { get; set; }

        /// <summary>
        /// If a line matches this pattern, then **only the next line** after it should be indented once.
        /// </summary>
        string? IndentNextLinePattern { get; set; }

        /// <summary>
        /// If a line matches this pattern, then its indentation should not be changed and it should not be evaluated against the other rules.
        /// </summary>
        string? UnIndentedLinePattern { get; set; }

    }
}
