// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.InlayHintsProvider.html">Monaco API</see> for more details.
    /// </remarks>
    public interface InlayHintsProvider
    {
        string? DisplayName { get; set; }

        IEvent<object>? OnDidChangeInlayHints { get; set; }

        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<InlayHintList> ProvideInlayHints(editor.ITextModel model, Range range, CancellationToken token);

        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<InlayHint> ResolveInlayHint(InlayHint hint, CancellationToken token);

    }
}
