// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.InlayHint.html">Monaco API</see> for more details.
    /// </remarks>
    public interface InlayHint
    {
        InlayHintKind? Kind { get; set; }

        object Label { get; set; }

        bool? PaddingLeft { get; set; }

        bool? PaddingRight { get; set; }

        IPosition Position { get; set; }

        TextEdit[]? TextEdits { get; set; }

        object? Tooltip { get; set; }

    }
}
