// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/languages.InlayHintKind.html">Monaco API</see> for more details.
    /// </remarks>
    public enum InlayHintKind
    {
        Parameter = 2,
        Type = 1
    }
}
