// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.InlineCompletionsProvider.html">Monaco API</see> for more details.
    /// </remarks>
    public interface InlineCompletionsProvider<T>
    {
        /// <summary>
        /// /**
        ///          * Only used for {@link yieldsToGroupIds}.
        ///          * Multiple providers can have the same group id.
        /// </summary>
        InlineCompletionProviderGroupId? GroupId { get; set; }

        /// <summary>
        /// /**
        ///          * Returns a list of preferred provider {@link groupId}s.
        ///          * The current provider is only requested for completions if no provider with a preferred group id returned a result.
        /// </summary>
        InlineCompletionProviderGroupId[]? YieldsToGroupIds { get; set; }

        /// <summary>
        /// Will be called when a completions list is no longer in use and can be garbage-collected.
        /// </summary>
        void FreeInlineCompletions(T completions);

        /// <summary>
        /// Will be called when an item is shown.
        /// </summary>
        /// <param name="updatedInsertText">Is useful to understand bracket completion.</param>
        void HandleItemDidShow(T completions, object item, string updatedInsertText);

        /// <summary>
        /// Will be called when an item is partially accepted.
        /// </summary>
        void HandlePartialAccept(T completions, object item, double acceptedCharacters, PartialAcceptInfo info);

        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<T> ProvideInlineCompletions(editor.ITextModel model, Position position, InlineCompletionContext context, CancellationToken token);

        /// <returns>A string value.</returns>
        string ToString();

    }
}
