// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// /**
    ///      * How an {@link InlineCompletionsProvider inline completion provider}was triggered.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/languages.InlineCompletionTriggerKind.html">Monaco API</see> for more details.
    /// </remarks>
    public enum InlineCompletionTriggerKind
    {
        /// <summary>
        /// Completion was triggered automatically while editing.
        /// It is sufficient to return a single completion item in this case.
        /// </summary>
        Automatic = 0,
        /// <summary>
        /// Completion was triggered explicitly by a user gesture.
        /// Return multiple completion items to enable cycling through them.
        /// </summary>
        Explicit = 1
    }
}
