// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages
{
    /// <summary>
    /// A token.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IToken.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IToken, Token>))]
    public interface IToken
    {
        string Scopes { get; set; }

        double StartIndex { get; set; }

    }
}
