// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.LanguageFilter.html">Monaco API</see> for more details.
    /// </remarks>
    public interface LanguageFilter
    {
        bool? Exclusive { get; }

        /// <summary>
        /// This provider is implemented in the UI thread.
        /// </summary>
        bool? HasAccessToAllModels { get; }

        /// <summary>
        /// This provider comes from a builtin extension.
        /// </summary>
        bool? IsBuiltin { get; }

        string? Language { get; }

        string? NotebookType { get; }

        object? Pattern { get; }

        string? Scheme { get; }

    }
}
