// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <summary>
    /// A link inside the editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.ILink.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class Link : ILink
    {
        public IRange Range { get; set; }

        public string? Tooltip { get; set; }

        public object? Url { get; set; }

    }
}
