// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <summary>
    /// A provider of links.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.LinkProvider.html">Monaco API</see> for more details.
    /// </remarks>
    public interface LinkProvider
    {
        object? ResolveLink { get; set; }

        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<ILinksList> ProvideLinks(editor.ITextModel model, CancellationToken token);

    }
}
