// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <summary>
    /// Represents a location inside a resource, such as a line
    /// inside a text file.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.Location.html">Monaco API</see> for more details.
    /// </remarks>
    public interface Location
    {
        /// <summary>
        /// The document range of this locations.
        /// </summary>
        IRange Range { get; set; }

        /// <summary>
        /// The resource identifier of this location.
        /// </summary>
        Uri Uri { get; set; }

    }
}
