// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// This interface can be shortened as an array, ie. ['{','}','delimiter.curly']
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IMonarchLanguageBracket.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class MonarchLanguageBracket : IMonarchLanguageBracket
    {
        /// <summary>
        /// closing bracket
        /// </summary>
        public string Close { get; set; }

        /// <summary>
        /// open bracket
        /// </summary>
        public string Open { get; set; }

        /// <summary>
        /// token class
        /// </summary>
        public string Token { get; set; }

    }
}
