// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <summary>
    /// Represents a set of document highlights for a specific Uri.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.MultiDocumentHighlight.html">Monaco API</see> for more details.
    /// </remarks>
    public interface MultiDocumentHighlight
    {
        /// <summary>
        /// The set of highlights for the document.
        /// </summary>
        DocumentHighlight[] Highlights { get; set; }

        /// <summary>
        /// The Uri of the document that the highlights belong to.
        /// </summary>
        Uri Uri { get; set; }

    }
}
