// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.NewSymbolNamesProvider.html">Monaco API</see> for more details.
    /// </remarks>
    public interface NewSymbolNamesProvider
    {
        object? SupportsAutomaticNewSymbolNamesTriggerKind { get; set; }

        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<NewSymbolName[]> ProvideNewSymbolNames(editor.ITextModel model, IRange range, NewSymbolNameTriggerKind triggerKind, CancellationToken token);

    }
}
