// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.NewSymbolName.html">Monaco API</see> for more details.
    /// </remarks>
    public interface NewSymbolName
    {
        string NewSymbolName { get; }

        NewSymbolNameTag[]? Tags { get; }

    }
}
