// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/languages.NewSymbolNameTriggerKind.html">Monaco API</see> for more details.
    /// </remarks>
    public enum NewSymbolNameTriggerKind
    {
        Automatic = 1,
        Invoke = 0
    }
}
