// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <summary>
    /// Represents a parameter of a callable-signature. A parameter can
    /// have a label and a doc-comment.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.ParameterInformation.html">Monaco API</see> for more details.
    /// </remarks>
    public interface ParameterInformation
    {
        /// <summary>
        /// The human-readable doc-comment of this signature. Will be shown
        /// in the UI but can be omitted.
        /// </summary>
        object? Documentation { get; set; }

        /// <summary>
        /// The label of this signature. Will be shown in
        /// the UI.
        /// </summary>
        object Label { get; set; }

    }
}
