// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// How a partial acceptance was triggered.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/languages.PartialAcceptTriggerKind.html">Monaco API</see> for more details.
    /// </remarks>
    public enum PartialAcceptTriggerKind
    {
        Line = 1,
        Suggest = 2,
        Word = 0
    }
}
