// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <summary>
    /// The reference provider interface defines the contract between extensions and
    /// the [find references](https://code.visualstudio.com/docs/editor/editingevolved#_peek)-feature.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.ReferenceProvider.html">Monaco API</see> for more details.
    /// </remarks>
    public interface ReferenceProvider
    {
        /// <summary>
        /// Provide a set of project-wide references for the given position and document.
        /// </summary>
        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<Location[]> ProvideReferences(editor.ITextModel model, Position position, ReferenceContext context, CancellationToken token);

    }
}
