// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IRelativePattern.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class RelativePattern : IRelativePattern
    {
        /// <summary>
        /// A base file path to which this pattern will be matched against relatively.
        /// </summary>
        public string Base { get; set; }

        /// <summary>
        /// A file glob pattern like `*.{ts,js}` that will be matched on file paths
        /// relative to the base path.
        ///
        /// Example: Given a base of `/home/work/folder` and a file path of `/home/work/folder/index.js`,
        /// the file glob pattern will match on `index.js`.
        /// </summary>
        public string Pattern { get; set; }

    }
}
