// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.RenameLocation.html">Monaco API</see> for more details.
    /// </remarks>
    public interface RenameLocation
    {
        IRange Range { get; set; }

        string Text { get; set; }

    }
}
