// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.SelectionRangeProvider.html">Monaco API</see> for more details.
    /// </remarks>
    public interface SelectionRangeProvider
    {
        /// <summary>
        /// Provide ranges that should be selected from the given position.
        /// </summary>
        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<SelectionRange[][]> ProvideSelectionRanges(editor.ITextModel model, Position[] positions, CancellationToken token);

    }
}
