// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/classes/languages.SelectedSuggestionInfo.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class SelectedSuggestionInfo
    {
        public CompletionItemKind CompletionKind { get; }

        public bool IsSnippetText { get; }

        public IRange Range { get; }

        public string Text { get; }

        public SelectedSuggestionInfo(IRange range, string text, CompletionItemKind completionKind, bool isSnippetText)
        {
            Range = range;
            Text = text;
            CompletionKind = completionKind;
            IsSnippetText = isSnippetText;
        }

        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool Equals(SelectedSuggestionInfo other) => throw new NotImplementedException();

    }
}
