// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.SemanticTokensEdit.html">Monaco API</see> for more details.
    /// </remarks>
    public interface SemanticTokensEdit
    {
        uint[]? Data { get; }

        double DeleteCount { get; }

        double Start { get; }

    }
}
