// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// Signature help represents the signature of something
    /// callable. There can be multiple signatures but only one
    /// active and only one active parameter.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.SignatureHelp.html">Monaco API</see> for more details.
    /// </remarks>
    public interface SignatureHelp
    {
        /// <summary>
        /// The active parameter of the active signature.
        /// </summary>
        double ActiveParameter { get; set; }

        /// <summary>
        /// The active signature.
        /// </summary>
        double ActiveSignature { get; set; }

        /// <summary>
        /// One or more signatures.
        /// </summary>
        SignatureInformation[] Signatures { get; set; }

    }
}
