// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.SignatureHelpResult.html">Monaco API</see> for more details.
    /// </remarks>
    public interface SignatureHelpResult : IDisposable
    {
        SignatureHelp Value { get; set; }

    }
}
