// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/languages.SignatureHelpTriggerKind.html">Monaco API</see> for more details.
    /// </remarks>
    public enum SignatureHelpTriggerKind
    {
        ContentChange = 3,
        Invoke = 1,
        TriggerCharacter = 2
    }
}
