// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Languages
{
    /// <summary>
    /// Represents the signature of something callable. A signature
    /// can have a label, like a function-name, a doc-comment, and
    /// a set of parameters.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.SignatureInformation.html">Monaco API</see> for more details.
    /// </remarks>
    public interface SignatureInformation
    {
        /// <summary>
        /// Index of the active parameter.
        ///
        /// If provided, this is used in place of `SignatureHelp.activeSignature`.
        /// </summary>
        double? ActiveParameter { get; set; }

        /// <summary>
        /// The human-readable doc-comment of this signature. Will be shown
        /// in the UI but can be omitted.
        /// </summary>
        object? Documentation { get; set; }

        /// <summary>
        /// The label of this signature. Will be shown in
        /// the UI.
        /// </summary>
        string Label { get; set; }

        /// <summary>
        /// The parameters of this signature.
        /// </summary>
        ParameterInformation[] Parameters { get; set; }

    }
}
