// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.SignatureHelpContext.html">Monaco API</see> for more details.
    /// </remarks>
    public interface SignatureHelpContext
    {
        SignatureHelp? ActiveSignatureHelp { get; }

        bool IsRetrigger { get; }

        string? TriggerCharacter { get; }

        SignatureHelpTriggerKind TriggerKind { get; }

    }
}
