// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// The state of the tokenizer between two lines.
    /// It is useful to store flags such as in multiline comment, etc.
    /// The model will clone the previous line's state and pass it in to tokenize the next line.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IState.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class State : IState
    {
        /// <returns>A IState instance.</returns>
        public IState Clone() => throw new NotImplementedException();

        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool Equals(IState other) => throw new NotImplementedException();

    }
}
