// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// A symbol kind.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/languages.SymbolKind.html">Monaco API</see> for more details.
    /// </remarks>
    public enum SymbolKind
    {
        Array = 17,
        Boolean = 16,
        Class = 4,
        Constant = 13,
        Constructor = 8,
        Enum = 9,
        EnumMember = 21,
        Event = 23,
        Field = 7,
        File = 0,
        Function = 11,
        Interface = 10,
        Key = 19,
        Method = 5,
        Module = 1,
        Namespace = 2,
        Null = 20,
        Number = 15,
        Object = 18,
        Operator = 24,
        Package = 3,
        Property = 6,
        String = 14,
        Struct = 22,
        TypeParameter = 25,
        Variable = 12
    }
}
