// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// A factory for token providers.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.TokensProviderFactory.html">Monaco API</see> for more details.
    /// </remarks>
    public interface TokensProviderFactory
    {
        /// <returns>A ProviderResult instance.</returns>
        ProviderResult<object> Create();

    }
}
