// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <summary>
    /// A "manual" provider of tokens.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.TokensProvider.html">Monaco API</see> for more details.
    /// </remarks>
    public interface TokensProvider
    {
        /// <summary>
        /// The initial state of a language. Will be the state passed in to tokenize the first line.
        /// </summary>
        /// <returns>A IState instance.</returns>
        IState GetInitialState();

        /// <summary>
        /// Tokenize a line given the state at the beginning of the line.
        /// </summary>
        /// <returns>A ILineTokens instance.</returns>
        ILineTokens Tokenize(string line, IState state);

    }
}
