// <auto-generated />
#nullable enable

namespace Monaco.Languages
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.WorkspaceEditMetadata.html">Monaco API</see> for more details.
    /// </remarks>
    public interface WorkspaceEditMetadata
    {
        string? Description { get; set; }

        string Label { get; set; }

        bool NeedsConfirmation { get; set; }

    }
}
