// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages
{
    /// <summary>
    /// Represents a collection of edits to be applied across multiple files in the workspace.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.WorkspaceEdit.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class WorkspaceEdit
    {
        /// <summary>
        /// Gets or sets the array of text edits to apply.
        /// </summary>
        public WorkspaceTextEdit[]? Edits { get; set; } // TODO: This could also be of type 'WorkspaceFileEdit'
    }
}