// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Languages
{
    /// <summary>
    /// Represents a text edit in a workspace edit, targeting a specific resource.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.IWorkspaceTextEdit.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class WorkspaceTextEdit
    {
        /// <summary>
        /// Gets or sets the text edit to apply.
        /// </summary>
        public TextEdit? Edit { get; set; }

        /// <summary>
        /// Gets or sets the metadata associated with this edit.
        /// </summary>
        public WorkspaceEditMetadata? Metadata { get; set; }

        /// <summary>
        /// Gets or sets the model version ID to ensure the edit is applied to the correct version.
        /// Important for this to be nullable here, as otherwise it still serializes as '0' which throws a 'bad state - model changed in the meantime' as version will mismatch.
        /// </summary>
        public double? ModelVersionId { get; set; }

        /// <summary>
        /// Gets or sets the URI of the resource to edit.
        /// </summary>
        public Uri? Resource { get; set; }
    }
}
