// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages.Css
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.css.IPropertyData.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IPropertyData, PropertyData>))]
    public interface IPropertyData
    {
        string[]? Browsers { get; set; }

        object? Description { get; set; }

        string Name { get; set; }

        IReference[]? References { get; set; }

        double? Relevance { get; set; }

        string[]? Restrictions { get; set; }

        EntryStatus? Status { get; set; }

        string? Syntax { get; set; }

        IValueData[]? Values { get; set; }

    }
}
