// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages.Css
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.css.IReference.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IReference, Reference>))]
    public interface IReference
    {
        string Name { get; set; }

        string Url { get; set; }

    }
}
