// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages.Css
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.css.IValueData.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IValueData, ValueData>))]
    public interface IValueData
    {
        string[]? Browsers { get; set; }

        object? Description { get; set; }

        string Name { get; set; }

        IReference[]? References { get; set; }

        EntryStatus? Status { get; set; }

    }
}
