// <auto-generated />
#nullable enable

namespace Monaco.Languages.Css
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.css.MarkupContent.html">Monaco API</see> for more details.
    /// </remarks>
    public interface MarkupContent
    {
        MarkupKind Kind { get; set; }

        string Value { get; set; }

    }
}
