// <auto-generated />
#nullable enable
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Monaco.Languages.Css
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/types/languages.css.MarkupKind.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(JsonStringEnumConverter<MarkupKind>))]
    public enum MarkupKind
    {
        [JsonStringEnumMemberName("plaintext")]
        [EnumMember(Value = "plaintext")]
        Plaintext,
        [JsonStringEnumMemberName("markdown")]
        [EnumMember(Value = "markdown")]
        Markdown
    }
}
