// <auto-generated />
#nullable enable

namespace Monaco.Languages.Css
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.css.Options.html">Monaco API</see> for more details.
    /// </remarks>
    public interface Options
    {
        /// <summary>
        /// Configures the CSS data types known by the langauge service.
        /// </summary>
        CSSDataConfiguration? Data { get; }

        /// <summary>
        /// Settings for the CSS formatter.
        /// </summary>
        CSSFormatConfiguration? Format { get; }

        object? Lint { get; }

        bool? Validate { get; }

    }
}
