// <auto-generated />
#nullable enable

namespace Monaco.Languages.Css
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.css.IPropertyData.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class PropertyData : IPropertyData
    {
        public string[]? Browsers { get; set; }

        public object? Description { get; set; }

        public string Name { get; set; }

        public IReference[]? References { get; set; }

        public double? Relevance { get; set; }

        public string[]? Restrictions { get; set; }

        public EntryStatus? Status { get; set; }

        public string? Syntax { get; set; }

        public IValueData[]? Values { get; set; }

    }
}
