// <auto-generated />
#nullable enable

namespace Monaco.Languages.Typescript
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.typescript.CompilerOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public interface CompilerOptions
    {
        bool? AllowJs { get; set; }

        bool? AllowSyntheticDefaultImports { get; set; }

        bool? AllowUmdGlobalAccess { get; set; }

        bool? AllowUnreachableCode { get; set; }

        bool? AllowUnusedLabels { get; set; }

        bool? AlwaysStrict { get; set; }

        string? BaseUrl { get; set; }

        string? Charset { get; set; }

        bool? CheckJs { get; set; }

        bool? Composite { get; set; }

        bool? Declaration { get; set; }

        string? DeclarationDir { get; set; }

        bool? DeclarationMap { get; set; }

        bool? DisableSizeLimit { get; set; }

        bool? DisableSourceOfProjectReferenceRedirect { get; set; }

        bool? DownlevelIteration { get; set; }

        bool? EmitBOM { get; set; }

        bool? EmitDeclarationOnly { get; set; }

        bool? EmitDecoratorMetadata { get; set; }

        bool? EsModuleInterop { get; set; }

        bool? ExperimentalDecorators { get; set; }

        bool? ForceConsistentCasingInFileNames { get; set; }

        bool? ImportHelpers { get; set; }

        bool? InlineSourceMap { get; set; }

        bool? InlineSources { get; set; }

        bool? IsolatedModules { get; set; }

        JsxEmit? Jsx { get; set; }

        string? JsxFactory { get; set; }

        bool? KeyofStringsOnly { get; set; }

        string[]? Lib { get; set; }

        string? Locale { get; set; }

        string? MapRoot { get; set; }

        double? MaxNodeModuleJsDepth { get; set; }

        ModuleKind? Module { get; set; }

        ModuleResolutionKind? ModuleResolution { get; set; }

        NewLineKind? NewLine { get; set; }

        bool? NoEmit { get; set; }

        bool? NoEmitHelpers { get; set; }

        bool? NoEmitOnError { get; set; }

        bool? NoErrorTruncation { get; set; }

        bool? NoFallthroughCasesInSwitch { get; set; }

        bool? NoImplicitAny { get; set; }

        bool? NoImplicitReturns { get; set; }

        bool? NoImplicitThis { get; set; }

        bool? NoImplicitUseStrict { get; set; }

        bool? NoLib { get; set; }

        bool? NoResolve { get; set; }

        bool? NoStrictGenericChecks { get; set; }

        bool? NoUnusedLocals { get; set; }

        bool? NoUnusedParameters { get; set; }

        string? Out { get; set; }

        string? OutDir { get; set; }

        string? OutFile { get; set; }

        MapLike<string[]>? Paths { get; set; }

        bool? PreserveConstEnums { get; set; }

        bool? PreserveSymlinks { get; set; }

        string? Project { get; set; }

        string? ReactNamespace { get; set; }

        bool? RemoveComments { get; set; }

        bool? ResolveJsonModule { get; set; }

        string? RootDir { get; set; }

        string[]? RootDirs { get; set; }

        bool? SkipDefaultLibCheck { get; set; }

        bool? SkipLibCheck { get; set; }

        bool? SourceMap { get; set; }

        string? SourceRoot { get; set; }

        bool? Strict { get; set; }

        bool? StrictBindCallApply { get; set; }

        bool? StrictFunctionTypes { get; set; }

        bool? StrictNullChecks { get; set; }

        bool? StrictPropertyInitialization { get; set; }

        bool? StripInternal { get; set; }

        bool? SuppressExcessPropertyErrors { get; set; }

        bool? SuppressImplicitAnyIndexErrors { get; set; }

        ScriptTarget? Target { get; set; }

        bool? TraceResolution { get; set; }

        /// <summary>
        /// Paths used to compute primary types search locations
        /// </summary>
        string[]? TypeRoots { get; set; }

        string[]? Types { get; set; }

        bool? UseDefineForClassFields { get; set; }

        CompilerOptionsValue this[string option] { get; set; }

    }
}
