// <auto-generated />
#nullable enable

namespace Monaco.Languages.Typescript
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.json.DiagnosticsOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public interface DiagnosticsOptions
    {
        double[]? DiagnosticCodesToIgnore { get; set; }

        bool? NoSemanticValidation { get; set; }

        bool? NoSuggestionDiagnostics { get; set; }

        bool? NoSyntaxValidation { get; set; }

        /// <summary>
        /// Limit diagnostic computation to only visible files.
        /// Defaults to false.
        /// </summary>
        bool? OnlyVisible { get; set; }

    }
}
