// <auto-generated />
#nullable enable

namespace Monaco.Languages.Typescript
{
    /// <summary>
    /// A linked list of formatted diagnostic messages to be used as part of a multiline message.
    /// It is built from the bottom up, leaving the head to be the "main" diagnostic.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.typescript.DiagnosticMessageChain.html">Monaco API</see> for more details.
    /// </remarks>
    public interface DiagnosticMessageChain
    {
        /// <summary>
        /// Diagnostic category: warning = 0, error = 1, suggestion = 2, message = 3
        /// </summary>
        object Category { get; set; }

        double Code { get; set; }

        string MessageText { get; set; }

        DiagnosticMessageChain[]? Next { get; set; }

    }
}
