// <auto-generated />
#nullable enable

namespace Monaco.Languages.Typescript
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.typescript.EmitOutput.html">Monaco API</see> for more details.
    /// </remarks>
    public interface EmitOutput
    {
        Diagnostic[]? Diagnostics { get; set; }

        bool EmitSkipped { get; set; }

        OutputFile[] OutputFiles { get; set; }

    }
}
