// <auto-generated />
#nullable enable

namespace Monaco.Languages.Typescript
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.typescript.IExtraLibs.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ExtraLibs : IExtraLibs
    {
        public IExtraLib this[string path] { get; set; }

    }
}
