// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages.Typescript
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.typescript.IExtraLibs.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IExtraLibs, ExtraLibs>))]
    public interface IExtraLibs
    {
        IExtraLib this[string path] { get; set; }

    }
}
