// <auto-generated />
#nullable enable
using Monaco;
using Monaco.Languages.Css;
using Monaco.Languages.Json;

namespace Monaco.Languages.Typescript
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.css.LanguageServiceDefaults.html">Monaco API</see> for more details.
    /// </remarks>
    public interface LanguageServiceDefaults
    {
        InlayHintsOptions InlayHintsOptions { get; }

        ModeConfiguration ModeConfiguration { get; }

        /// <summary>
        /// Event fired when compiler options or diagnostics options are changed.
        /// </summary>
        IEvent<object> OnDidChange { get; }

        /// <summary>
        /// Event fired when extra libraries registered with the language service change.
        /// </summary>
        IEvent<object> OnDidExtraLibsChange { get; }

        WorkerOptions WorkerOptions { get; }

        /// <summary>
        /// Add an additional source file to the language service. Use this
        /// for typescript (definition) files that won't be loaded as editor
        /// documents, like `jquery.d.ts`.
        /// </summary>
        /// <param name="content">The file content</param>
        /// <param name="filePath">An optional file path</param>
        /// <returns>A IDisposable instance.</returns>
        IDisposable AddExtraLib(string content, string? filePath);

        /// <summary>
        /// Get current TypeScript compiler options for the language service.
        /// </summary>
        /// <returns>A CompilerOptions instance.</returns>
        CompilerOptions GetCompilerOptions();

        /// <summary>
        /// Get the current diagnostics options for the language service.
        /// </summary>
        /// <returns>A DiagnosticsOptions instance.</returns>
        DiagnosticsOptions GetDiagnosticsOptions();

        /// <summary>
        /// Get the current setting for whether all existing models should be eagerly sync'd
        /// to the worker on start or restart.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        bool GetEagerModelSync();

        /// <summary>
        /// Get the current extra libs registered with the language service.
        /// </summary>
        /// <returns>A IExtraLibs instance.</returns>
        IExtraLibs GetExtraLibs();

        /// <summary>
        /// Set TypeScript compiler options.
        /// </summary>
        void SetCompilerOptions(CompilerOptions options);

        /// <summary>
        /// Configure whether syntactic and/or semantic validation should
        /// be performed
        /// </summary>
        void SetDiagnosticsOptions(DiagnosticsOptions options);

        /// <summary>
        /// Configure if all existing models should be eagerly sync'd
        /// to the worker on start or restart.
        /// </summary>
        void SetEagerModelSync(bool @value);

        /// <summary>
        /// Remove all existing extra libs and set the additional source
        /// files to the language service. Use this for typescript definition
        /// files that won't be loaded as editor documents, like `jquery.d.ts`.
        /// </summary>
        /// <param name="libs">An array of entries to register.</param>
        void SetExtraLibs(object[] libs);

        /// <summary>
        /// Configure inlay hints options.
        /// </summary>
        void SetInlayHintsOptions(InlayHintsOptions options);

        /// <summary>
        /// No-op.
        /// </summary>
        void SetMaximumWorkerIdleTime(double @value);

        void SetModeConfiguration(ModeConfiguration modeConfiguration);

        /// <summary>
        /// Configure webworker options
        /// </summary>
        void SetWorkerOptions(WorkerOptions options);

    }
}
