// <auto-generated />
#nullable enable

namespace Monaco.Languages.Typescript
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.typescript.MapLike.html">Monaco API</see> for more details.
    /// </remarks>
    public interface MapLike<T>
    {
        T this[string index] { get; set; }

    }
}
