// <auto-generated />
#nullable enable

namespace Monaco.Languages.Typescript
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/languages.typescript.ScriptTarget.html">Monaco API</see> for more details.
    /// </remarks>
    public enum ScriptTarget
    {
        ES2015 = 2,
        ES2016 = 3,
        ES2017 = 4,
        ES2018 = 5,
        ES2019 = 6,
        ES2020 = 7,
        ES3 = 0,
        ES5 = 1,
        ESNext = 99,
        JSON = 100,
        Latest = 99
    }
}
