// <auto-generated />
#nullable enable

namespace Monaco.Languages.Typescript
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.typescript.TypeScriptWorker.html">Monaco API</see> for more details.
    /// </remarks>
    public interface TypeScriptWorker
    {
        /// <summary>
        /// Get other occurrences which should be updated when renaming the item at the given file and position.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object FindRenameLocations(string fileName, double positon, bool findInStrings, bool findInComments, bool providePrefixAndSuffixTextForRename);

        /// <summary>
        /// Get possible code fixes at the given position in the file.
        /// </summary>
        /// <param name="formatOptions">`typescript.FormatCodeOptions`</param>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetCodeFixesAtPosition(string fileName, double start, double end, double[] errorCodes, object formatOptions);

        /// <summary>
        /// Get diagnostic messages related to the current compiler options.
        /// </summary>
        /// <param name="fileName">Not used</param>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetCompilerOptionsDiagnostics(string fileName);

        /// <summary>
        /// Get code completion details for the given file, position, and entry.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetCompletionEntryDetails(string fileName, double position, string entry);

        /// <summary>
        /// Get code completions for the given file and position.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetCompletionsAtPosition(string fileName, double position);

        /// <summary>
        /// Get the definition of the item at the given position in the file.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetDefinitionAtPosition(string fileName, double position);

        /// <returns>A task representing the asynchronous operation.</returns>
        object GetDocumentHighlights(string fileName, double position, string[] filesToSearch);

        /// <summary>
        /// Get transpiled output for the given file.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetEmitOutput(string fileName, bool? emitOnlyDtsFiles, bool? forceDtsEmit);

        /// <summary>
        /// Get formatting changes which should be applied after the given keystroke.
        /// </summary>
        /// <param name="options">`typescript.FormatCodeOptions`</param>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetFormattingEditsAfterKeystroke(string fileName, double postion, string ch, object options);

        /// <summary>
        /// Get changes which should be applied to format the given file.
        /// </summary>
        /// <param name="options">`typescript.FormatCodeOptions`</param>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetFormattingEditsForDocument(string fileName, object options);

        /// <summary>
        /// Get changes which should be applied to format the given range in the file.
        /// </summary>
        /// <param name="options">`typescript.FormatCodeOptions`</param>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetFormattingEditsForRange(string fileName, double start, double end, object options);

        /// <summary>
        /// Get outline entries for the item at the given position in the file.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetNavigationTree(string fileName);

        /// <summary>
        /// Get quick info for the item at the given position in the file.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetQuickInfoAtPosition(string fileName, double position);

        /// <summary>
        /// Get references to the item at the given position in the file.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetReferencesAtPosition(string fileName, double position);

        /// <summary>
        /// Get edits which should be applied to rename the item at the given file and position (or a failure reason).
        /// </summary>
        /// <param name="options">`typescript.RenameInfoOptions`</param>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetRenameInfo(string fileName, double positon, object options);

        /// <summary>
        /// Get the content of a given file.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetScriptText(string fileName);

        /// <summary>
        /// Get diagnostic messages for any semantic issues in the given file.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetSemanticDiagnostics(string fileName);

        /// <summary>
        /// Get signature help items for the item at the given file and position.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetSignatureHelpItems(string fileName, double position, object options);

        /// <summary>
        /// Get diagnostic messages for any suggestions related to the given file.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetSuggestionDiagnostics(string fileName);

        /// <summary>
        /// Get diagnostic messages for any syntax issues in the given file.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetSyntacticDiagnostics(string fileName);

        /// <summary>
        /// Get inlay hints in the range of the file.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        object ProvideInlayHints(string fileName, double start, double end);

    }
}
