// <auto-generated />
#nullable enable

namespace Monaco.Languages.Typescript
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.typescript.WorkerOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public interface WorkerOptions
    {
        /// <summary>
        /// A full HTTP path to a JavaScript file which adds a function `customTSWorkerFactory` to the self inside a web-worker
        /// </summary>
        string? CustomWorkerPath { get; set; }

    }
}
