// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/classes/CancellationTokenSource.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class CancellationTokenSource
    {
        public CancellationToken Token { get; }

        public CancellationTokenSource(CancellationToken? parent) { }

        public void Cancel() => throw new NotImplementedException();

        public void Dispose(bool? cancel) => throw new NotImplementedException();

    }
}
