// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/Environment.html">Monaco API</see> for more details.
    /// </remarks>
    public interface Environment
    {
        /// <summary>
        /// The base url where the editor sources are found (which contains the vs folder)
        /// </summary>
        string? BaseUrl { get; set; }

        /// <summary>
        /// Define a global `monaco` symbol.
        /// This is true by default in AMD and false by default in ESM.
        /// </summary>
        bool? GlobalAPI { get; set; }

        /// <summary>
        /// Create a trusted types policy (same API as window.trustedTypes.createPolicy)
        /// </summary>
        ITrustedTypePolicy CreateTrustedTypesPolicy(string policyName, ITrustedTypePolicyOptions? policyOptions);

        /// <summary>
        /// A web worker factory.
        /// NOTE: If `getWorker` is defined, `getWorkerUrl` is not invoked.
        /// </summary>
        object GetWorker(string workerId, string label);

        /// <summary>
        /// Return the location for web worker scripts.
        /// NOTE: If `getWorker` is defined, `getWorkerUrl` is not invoked.
        /// </summary>
        /// <returns>A string value.</returns>
        string GetWorkerUrl(string workerId, string label);

    }
}
