// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/IEvent.html">Monaco API</see> for more details.
    /// </remarks>
    public interface IEvent<T>
    {
        /// <returns>A IDisposable instance.</returns>
        IDisposable Invoke(object listener, object? thisArg);

    }
}
