// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco
{
    /// <summary>
    /// A range in the editor. This interface is suitable for serialization.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/IRange.html">Monaco API</see> for more details.
    /// </remarks>
    public partial interface IRange
    {
        /// <summary>
        /// Line number on which the range starts (starts at 1).
        /// </summary>
        uint StartLineNumber { get; }

        /// <summary>
        /// Column on which the range starts in line `startLineNumber` (starts at 1).
        /// </summary>
        uint StartColumn { get; }

        /// <summary>
        /// Line number on which the range ends.
        /// </summary>
        uint EndLineNumber { get; }

        /// <summary>
        /// Column on which the range ends in line `endLineNumber`.
        /// </summary>
        uint EndColumn { get; }
    }
}
