// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco
{
    /// <summary>
    /// A selection in the editor.
    /// The selection is a range that has an orientation.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/ISelection.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ISelection, Selection>))]
    public interface ISelection
    {
        /// <summary>
        /// The column on `positionLineNumber` where the selection has ended.
        /// </summary>
        double PositionColumn { get; }

        /// <summary>
        /// The line number on which the selection has ended.
        /// </summary>
        double PositionLineNumber { get; }

        /// <summary>
        /// The column on `selectionStartLineNumber` where the selection has started.
        /// </summary>
        double SelectionStartColumn { get; }

        /// <summary>
        /// The line number on which the selection has started.
        /// </summary>
        double SelectionStartLineNumber { get; }

    }
}
