// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/ITrustedTypePolicyOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ITrustedTypePolicyOptions, TrustedTypePolicyOptions>))]
    public interface ITrustedTypePolicyOptions
    {
        object? CreateHTML { get; set; }

        object? CreateScript { get; set; }

        object? CreateScriptURL { get; set; }

    }
}
