// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/ITrustedTypePolicy.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ITrustedTypePolicy, TrustedTypePolicy>))]
    public interface ITrustedTypePolicy
    {
        string Name { get; }

        object CreateHTML(string input);

        object CreateScript(string input);

        object CreateScriptURL(string input);

    }
}
