// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/IKeyboardEvent.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class KeyboardEvent : IKeyboardEvent
    {
        public bool _standardKeyboardEventBrand { get; set; }

        public bool AltGraphKey { get; set; }

        public bool AltKey { get; set; }

        public KeyboardEvent BrowserEvent { get; set; }

        public string Code { get; set; }

        public bool CtrlKey { get; set; }

        public KeyCode KeyCode { get; set; }

        public bool MetaKey { get; set; }

        public bool ShiftKey { get; set; }

        public object Target { get; set; }

        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool Equals(double keybinding) => throw new NotImplementedException();

        public void PreventDefault() => throw new NotImplementedException();

        public void StopPropagation() => throw new NotImplementedException();

    }
}
