// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <summary>
    /// Virtual Key Codes, the value does not hold any inherent meaning.
    /// Inspired somewhat from https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx
    /// But these are "more general", as they should work across browsers &amp; OS`s.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/KeyCode.html">Monaco API</see> for more details.
    /// </remarks>
    public enum KeyCode
    {
        AbntC1 = 115,
        AbntC2 = 116,
        Alt = 6,
        AudioVolumeDown = 119,
        AudioVolumeMute = 117,
        AudioVolumeUp = 118,
        /// <summary>
        /// Used for miscellaneous characters; it can vary by keyboard.
        /// For the US standard keyboard, the '`~' key
        /// </summary>
        Backquote = 91,
        /// <summary>
        /// Used for miscellaneous characters; it can vary by keyboard.
        /// For the US standard keyboard, the '\|' key
        /// </summary>
        Backslash = 93,
        Backspace = 1,
        /// <summary>
        /// Used for miscellaneous characters; it can vary by keyboard.
        /// For the US standard keyboard, the '[{' key
        /// </summary>
        BracketLeft = 92,
        /// <summary>
        /// Used for miscellaneous characters; it can vary by keyboard.
        /// For the US standard keyboard, the ']}' key
        /// </summary>
        BracketRight = 94,
        BrowserBack = 122,
        BrowserForward = 123,
        BrowserHome = 121,
        BrowserSearch = 120,
        CapsLock = 8,
        /// <summary>
        /// VK_CLEAR, 0x0C, CLEAR key
        /// </summary>
        Clear = 131,
        /// <summary>
        /// For any country/region, the ',' key
        /// For the US standard keyboard, the ',&lt;' key
        /// </summary>
        Comma = 87,
        ContextMenu = 58,
        Ctrl = 5,
        Delete = 20,
        DependsOnKbLayout = -1,
        Digit0 = 21,
        Digit1 = 22,
        Digit2 = 23,
        Digit3 = 24,
        Digit4 = 25,
        Digit5 = 26,
        Digit6 = 27,
        Digit7 = 28,
        Digit8 = 29,
        Digit9 = 30,
        DownArrow = 18,
        End = 13,
        Enter = 3,
        /// <summary>
        /// For any country/region, the '+' key
        /// For the US standard keyboard, the '=+' key
        /// </summary>
        Equal = 86,
        Escape = 9,
        F1 = 59,
        F10 = 68,
        F11 = 69,
        F12 = 70,
        F13 = 71,
        F14 = 72,
        F15 = 73,
        F16 = 74,
        F17 = 75,
        F18 = 76,
        F19 = 77,
        F2 = 60,
        F20 = 78,
        F21 = 79,
        F22 = 80,
        F23 = 81,
        F24 = 82,
        F3 = 61,
        F4 = 62,
        F5 = 63,
        F6 = 64,
        F7 = 65,
        F8 = 66,
        F9 = 67,
        Home = 14,
        Insert = 19,
        /// <summary>
        /// Either the angle bracket key or the backslash key on the RT 102-key keyboard.
        /// </summary>
        IntlBackslash = 97,
        /// <summary>
        /// Cover all key codes when IME is processing input.
        /// </summary>
        KeyInComposition = 114,
        KeyA = 31,
        KeyB = 32,
        KeyC = 33,
        KeyD = 34,
        KeyE = 35,
        KeyF = 36,
        KeyG = 37,
        KeyH = 38,
        KeyI = 39,
        KeyJ = 40,
        KeyK = 41,
        KeyL = 42,
        KeyM = 43,
        KeyN = 44,
        KeyO = 45,
        KeyP = 46,
        KeyQ = 47,
        KeyR = 48,
        KeyS = 49,
        KeyT = 50,
        KeyU = 51,
        KeyV = 52,
        KeyW = 53,
        KeyX = 54,
        KeyY = 55,
        KeyZ = 56,
        LaunchApp2 = 130,
        LaunchMail = 129,
        LaunchMediaPlayer = 128,
        LeftArrow = 15,
        /// <summary>
        /// Placed last to cover the length of the enum.
        /// Please do not depend on this value!
        /// </summary>
        MaxValue = 132,
        MediaPlayPause = 127,
        MediaStop = 126,
        MediaTrackNext = 124,
        MediaTrackPrevious = 125,
        Meta = 57,
        /// <summary>
        /// For any country/region, the '-' key
        /// For the US standard keyboard, the '-_' key
        /// </summary>
        Minus = 88,
        NumLock = 83,
        NumpadSeparator = 110,
        Numpad0 = 98,
        Numpad1 = 99,
        Numpad2 = 100,
        Numpad3 = 101,
        Numpad4 = 102,
        Numpad5 = 103,
        Numpad6 = 104,
        Numpad7 = 105,
        Numpad8 = 106,
        Numpad9 = 107,
        NumpadAdd = 109,
        NumpadDecimal = 112,
        NumpadDivide = 113,
        NumpadMultiply = 108,
        NumpadSubtract = 111,
        /// <summary>
        /// Used for miscellaneous characters; it can vary by keyboard.
        /// </summary>
        Oem8 = 96,
        PageDown = 12,
        PageUp = 11,
        PauseBreak = 7,
        /// <summary>
        /// For any country/region, the '.' key
        /// For the US standard keyboard, the '.&gt;' key
        /// </summary>
        Period = 89,
        /// <summary>
        /// Used for miscellaneous characters; it can vary by keyboard.
        /// For the US standard keyboard, the ''"' key
        /// </summary>
        Quote = 95,
        RightArrow = 17,
        ScrollLock = 84,
        /// <summary>
        /// Used for miscellaneous characters; it can vary by keyboard.
        /// For the US standard keyboard, the ';:' key
        /// </summary>
        Semicolon = 85,
        Shift = 4,
        /// <summary>
        /// Used for miscellaneous characters; it can vary by keyboard.
        /// For the US standard keyboard, the '/?' key
        /// </summary>
        Slash = 90,
        Space = 10,
        Tab = 2,
        /// <summary>
        /// Placed first to cover the 0 value of the enum.
        /// </summary>
        Unknown = 0,
        UpArrow = 16
    }
}
