// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/classes/KeyMod.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class KeyMod
    {
        [JsonPropertyName("Alt")]
        public double Alt { get; }

        [JsonPropertyName("CtrlCmd")]
        public double CtrlCmd { get; }

        [JsonPropertyName("Shift")]
        public double Shift { get; }

        [JsonPropertyName("WinCtrl")]
        public double WinCtrl { get; }

        /// <returns>A numeric value.</returns>
        public static double Chord(double firstPart, double secondPart) => throw new NotImplementedException();

    }
}
