// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/MarkerTag.html">Monaco API</see> for more details.
    /// </remarks>
    public enum MarkerTag
    {
        Deprecated = 2,
        Unnecessary = 1
    }
}
