// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/MarkerSeverity.html">Monaco API</see> for more details.
    /// </remarks>
    public enum MarkerSeverity
    {
        Error = 8,
        Hint = 1,
        Info = 2,
        Warning = 4
    }
}
