// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <summary>
    /// A position in the editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/classes/Position.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class Position
    {
        /// <summary>
        /// column (the first character in a line is between column 1 and column 2)
        /// </summary>
        public double Column { get; }

        /// <summary>
        /// line number (starts at 1)
        /// </summary>
        public double LineNumber { get; }

        public Position(double lineNumber, double column)
        {
            LineNumber = lineNumber;
            Column = column;
        }

        /// <summary>
        /// Clone this position.
        /// </summary>
        /// <returns>A Position instance.</returns>
        public Position Clone() => throw new NotImplementedException();

        /// <summary>
        /// A function that compares positions, useful for sorting
        /// </summary>
        /// <returns>A numeric value.</returns>
        public static double Compare(IPosition a, IPosition b) => throw new NotImplementedException();

        /// <summary>
        /// Derive a new position from this position.
        /// </summary>
        /// <param name="deltaLineNumber">line number delta</param>
        /// <param name="deltaColumn">column delta</param>
        /// <returns>A Position instance.</returns>
        public Position Delta(double? deltaLineNumber, double? deltaColumn) => throw new NotImplementedException();

        /// <summary>
        /// Test if this position equals other position
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool Equals(IPosition other) => throw new NotImplementedException();

        /// <summary>
        /// Test if position `a` equals position `b`
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public static bool Equals(IPosition a, IPosition b) => throw new NotImplementedException();

        /// <summary>
        /// Test if this position is before other position.
        /// If the two positions are equal, the result will be false.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool IsBefore(IPosition other) => throw new NotImplementedException();

        /// <summary>
        /// Test if position `a` is before position `b`.
        /// If the two positions are equal, the result will be false.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public static bool IsBefore(IPosition a, IPosition b) => throw new NotImplementedException();

        /// <summary>
        /// Test if this position is before other position.
        /// If the two positions are equal, the result will be true.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool IsBeforeOrEqual(IPosition other) => throw new NotImplementedException();

        /// <summary>
        /// Test if position `a` is before position `b`.
        /// If the two positions are equal, the result will be true.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public static bool IsBeforeOrEqual(IPosition a, IPosition b) => throw new NotImplementedException();

        /// <summary>
        /// Test if `obj` is an `IPosition`.
        /// </summary>
        public static obj is IPosition IsIPosition(object obj) => throw new NotImplementedException();

        /// <summary>
        /// Create a `Position` from an `IPosition`.
        /// </summary>
        /// <returns>A Position instance.</returns>
        public static Position Lift(IPosition pos) => throw new NotImplementedException();

        /// <returns>A IPosition instance.</returns>
        public IPosition ToJSON() => throw new NotImplementedException();

        /// <summary>
        /// Convert to a human-readable representation.
        /// </summary>
        /// <returns>A string value.</returns>
        public string ToString() => throw new NotImplementedException();

        /// <summary>
        /// Create a new position from this position.
        /// </summary>
        /// <param name="newLineNumber">new line number</param>
        /// <param name="newColumn">new column</param>
        /// <returns>A Position instance.</returns>
        public Position With(double? newLineNumber, double? newColumn) => throw new NotImplementedException();

    }
}
