// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco
{
    /// <summary>
    /// A range in the editor. (startLineNumber,startColumn) is &lt;= (endLineNumber,endColumn)
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/classes/Range.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class Range : IRange
    {
        /// <summary>
        /// Column on which the range ends in line `endLineNumber`.
        /// </summary>
        [JsonInclude]
        public uint EndColumn { get; internal set; }
        /// <summary>
        /// Line number on which the range ends.
        /// </summary>
        [JsonInclude]
        public uint EndLineNumber { get; internal set; }
        /// <summary>
        /// Column on which the range starts in line `startLineNumber` (starts at 1).
        /// </summary>
        [JsonInclude]
        public uint StartColumn { get; internal set; }
        /// <summary>
        /// Line number on which the range starts (starts at 1).
        /// </summary>
        [JsonInclude]
        public uint StartLineNumber { get; internal set; }

        public Range() // For Serialization
        {
        }

        public Range(uint startLineNumber, uint startColumn, uint endLineNumber, uint endColumn)
        {
            // TODO: Range Check? Monaco doesn't seem to do it currently...
            StartLineNumber = startLineNumber;
            StartColumn = startColumn;
            EndLineNumber = endLineNumber;
            EndColumn = endColumn;
        }

        public Range CloneRange()
        {
            return new Range(StartLineNumber, StartColumn, EndLineNumber, EndColumn);
        }

        public Range CollapseToStart()
        {
            return new Range(StartColumn, StartColumn, StartLineNumber, StartColumn);
        }

        public bool ContainsPosition(IPosition position)
        {
            if (StartLineNumber == position.LineNumber && position.LineNumber == EndLineNumber)
            {
                return StartColumn <= position.Column && position.Column <= EndColumn;
            }
            else if (StartLineNumber == position.LineNumber)
            {
                return StartColumn <= position.Column;
            }
            else if (EndLineNumber == position.LineNumber)
            {
                return position.Column <= EndColumn;
            }

            return StartLineNumber < position.LineNumber && EndLineNumber > position.LineNumber;
        }

        public bool ContainsRange(IRange range)
        {
            bool isStart = StartLineNumber <= range.StartLineNumber;
            bool isStartColumn = StartLineNumber != range.StartLineNumber || StartColumn <= range.StartColumn;
            bool isEnd = EndLineNumber >= range.EndLineNumber;
            bool isEndColumn = EndLineNumber != range.EndLineNumber || EndColumn >= range.EndColumn;

            return isStart && isStartColumn && isEnd && isEndColumn;
        }

        public bool EqualsRange(Range other)
        {
            return StartColumn == other.StartColumn &&
                    StartLineNumber == other.StartLineNumber &&
                    EndColumn == other.EndColumn &&
                    EndLineNumber == other.EndLineNumber;
        }

        public Position GetEndPosition()
        {
            return new Position(EndLineNumber, EndColumn);
        }

        public Position GetStartPosition()
        {
            return new Position(StartLineNumber, StartColumn);
        }

        public Range IntersectRanges(IRange range)
        {
            // TODO
            throw new NotImplementedException();
        }

        public bool IsEmpty()
        {
            return StartLineNumber == EndLineNumber && StartColumn == EndColumn;
        }

        public Range PlusRange(IRange range)
        {
            // TODO
            throw new NotImplementedException();
        }

        public Range SetEndPosition(uint endLineNumber, uint endColumn)
        {
            return new Range(StartLineNumber, StartColumn, endLineNumber, endColumn);
        }

        public Range SetStartPosition(uint startLineNumber, uint startColumn)
        {
            return new Range(startLineNumber, startColumn, EndLineNumber, EndColumn);
        }

        public override string ToString()
        {
            return string.Format("[{0}, {1}-> {2}, {3}]", StartLineNumber, StartColumn, EndLineNumber, EndColumn);
        }

        public static Range Lift(IRange range)
        {
            return new Range(range.StartLineNumber, range.StartColumn, range.EndLineNumber, range.EndColumn);
        }

        // TODO: Weed out unique static method to put here.
    }
}
