// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/IScrollEvent.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ScrollEvent : IScrollEvent
    {
        public double ScrollHeight { get; set; }

        public bool ScrollHeightChanged { get; set; }

        public double ScrollLeft { get; set; }

        public bool ScrollLeftChanged { get; set; }

        public double ScrollTop { get; set; }

        public bool ScrollTopChanged { get; set; }

        public double ScrollWidth { get; set; }

        public bool ScrollWidthChanged { get; set; }

    }
}
