// <auto-generated />
#nullable enable
using System;
using System.Text.Json.Serialization;

namespace Monaco
{
    /// <summary>
    /// A selection in the editor.
    /// The selection is a range that has an orientation.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/classes/Selection.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class Selection : IRange
    {
        /// <summary>
        /// Line number on which the range starts (starts at 1).
        /// </summary>
        [JsonInclude]
        public uint StartLineNumber { get; internal set; }

        /// <summary>
        /// Column on which the range starts in line `startLineNumber` (starts at 1).
        /// </summary>
        [JsonInclude]
        public uint StartColumn { get; internal set; }

        /// <summary>
        /// Line number on which the range ends.
        /// </summary>
        [JsonInclude]
        public uint EndLineNumber { get; internal set; }

        /// <summary>
        /// Column on which the range ends in line `endLineNumber`.
        /// </summary>
        [JsonInclude]
        public uint EndColumn { get; internal set; }

        /// <summary>
        /// The line number on which the selection has ended.
        /// </summary>
        [JsonInclude]
        public uint PositionLineNumber { get; internal set; }

        /// <summary>
        /// The column on `positionLineNumber` where the selection has ended.
        /// </summary>
        [JsonInclude]
        public uint PositionColumn { get; internal set; }

        /// <summary>
        /// The line number on which the selection has started.
        /// </summary>
        [JsonInclude]
        public uint SelectionStartLineNumber { get; internal set; }

        /// <summary>
        /// The column on `selectionStartLineNumber` where the selection has started.
        /// </summary>
        [JsonInclude]
        public uint SelectionStartColumn { get; internal set; }

        [JsonIgnore]
        public SelectionDirection Direction { get; internal set; }

        public Selection(uint selectionStartLineNumber, uint selectionStartColumn, uint positionLineNumber, uint positionColumn)
        {
            SelectionStartLineNumber = selectionStartLineNumber;
            SelectionStartColumn = selectionStartColumn;
            PositionLineNumber = positionLineNumber;
            PositionColumn = positionColumn;

            if (selectionStartLineNumber < positionLineNumber || (selectionStartLineNumber == positionLineNumber && selectionStartColumn <= positionColumn))
            {
                // Start is first
                StartLineNumber = SelectionStartLineNumber;
                StartColumn = SelectionStartColumn;
                EndLineNumber = PositionLineNumber;
                EndColumn = PositionColumn;

                Direction = SelectionDirection.LTR;
            }
            else
            {
                // Flipped
                StartLineNumber = PositionLineNumber;
                StartColumn = PositionColumn;
                EndLineNumber = SelectionStartLineNumber;
                EndColumn = SelectionStartColumn;

                Direction = SelectionDirection.RTL;
            }
        }

        public SelectionDirection GetDirection()
        {
            return Direction;
        }

        public override string ToString()
        {
            return string.Format("[{0}, {1}-> {2}, {3}]", SelectionStartLineNumber, SelectionStartColumn, PositionLineNumber, PositionColumn);
        }
    }
}
