// <auto-generated />
#nullable enable

namespace Monaco
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/ITrustedTypePolicy.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class TrustedTypePolicy : ITrustedTypePolicy
    {
        public string Name { get; set; }

        public object CreateHTML(string input) => throw new NotImplementedException();

        public object CreateScript(string input) => throw new NotImplementedException();

        public object CreateScriptURL(string input) => throw new NotImplementedException();

    }
}
