// <auto-generated />
#nullable enable
using Monaco.Languages.Css;

namespace Monaco.Languages.Html
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.html.IAttributeData.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class AttributeData : IAttributeData
    {
        public object? Description { get; set; }

        public string Name { get; set; }

        public IReference[]? References { get; set; }

        public IValueData[]? Values { get; set; }

        public string? ValueSet { get; set; }

    }
}
