// <auto-generated />
#nullable enable

namespace Monaco.Languages.Html
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.html.CompletionConfiguration.html">Monaco API</see> for more details.
    /// </remarks>
    public interface CompletionConfiguration
    {
        bool this[string providerId] { get; }

    }
}
