// <auto-generated />
#nullable enable

namespace Monaco.Languages.Html
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.html.HTMLFormatConfiguration.html">Monaco API</see> for more details.
    /// </remarks>
    public interface HTMLFormatConfiguration
    {
        string ContentUnformatted { get; }

        bool EndWithNewline { get; }

        string ExtraLiners { get; }

        bool IndentHandlebars { get; }

        bool IndentInnerHtml { get; }

        bool InsertSpaces { get; }

        double MaxPreserveNewLines { get; }

        bool PreserveNewLines { get; }

        double TabSize { get; }

        string Unformatted { get; }

        string WrapAttributes { get; }

        double WrapLineLength { get; }

    }
}
