// <auto-generated />
#nullable enable

namespace Monaco.Languages.Html
{
    /// <summary>
    /// Custom HTML tags attributes and attribute values
    /// https://github.com/microsoft/vscode-html-languageservice/blob/main/docs/customData.md
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.html.HTMLDataV1.html">Monaco API</see> for more details.
    /// </remarks>
    public interface HTMLDataV1
    {
        IAttributeData[]? GlobalAttributes { get; }

        ITagData[]? Tags { get; }

        IValueSet[]? ValueSets { get; }

        object Version { get; }

    }
}
