// <auto-generated />
#nullable enable

namespace Monaco.Languages.Html
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.html.HTMLDataConfiguration.html">Monaco API</see> for more details.
    /// </remarks>
    public interface HTMLDataConfiguration
    {
        /// <summary>
        /// Provides a set of custom data providers.
        /// </summary>
        object? DataProviders { get; }

        /// <summary>
        /// Defines whether the standard HTML tags and attributes are shown
        /// </summary>
        bool? UseDefaultDataProvider { get; }

    }
}
