// <auto-generated />
#nullable enable
using Monaco.Languages.Css;
using System.Text.Json.Serialization;

namespace Monaco.Languages.Html
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.html.IAttributeData.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IAttributeData, AttributeData>))]
    public interface IAttributeData
    {
        object? Description { get; }

        string Name { get; }

        IReference[]? References { get; }

        IValueData[]? Values { get; }

        string? ValueSet { get; }

    }
}
