// <auto-generated />
#nullable enable
using Monaco.Languages.Css;
using System.Text.Json.Serialization;

namespace Monaco.Languages.Html
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.html.ITagData.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ITagData, TagData>))]
    public interface ITagData
    {
        IAttributeData[] Attributes { get; }

        object? Description { get; }

        string Name { get; }

        IReference[]? References { get; }

    }
}
