// <auto-generated />
#nullable enable
using Monaco.Languages.Css;
using System.Text.Json.Serialization;

namespace Monaco.Languages.Html
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.css.IValueData.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IValueData, ValueData>))]
    public interface IValueData
    {
        object? Description { get; }

        string Name { get; }

        IReference[]? References { get; }

    }
}
