// <auto-generated />
#nullable enable
using Monaco;
using Monaco.Languages.Css;

namespace Monaco.Languages.Html
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.html.LanguageServiceRegistration.html">Monaco API</see> for more details.
    /// </remarks>
    public interface LanguageServiceRegistration : IDisposable
    {
        LanguageServiceDefaults Defaults { get; }

    }
}
