// <auto-generated />
#nullable enable
using Monaco;
using Monaco.Languages.Css;

namespace Monaco.Languages.Html
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.css.LanguageServiceDefaults.html">Monaco API</see> for more details.
    /// </remarks>
    public interface LanguageServiceDefaults
    {
        string LanguageId { get; }

        ModeConfiguration ModeConfiguration { get; }

        IEvent<LanguageServiceDefaults> OnDidChange { get; }

        Options Options { get; }

        void SetModeConfiguration(ModeConfiguration modeConfiguration);

        void SetOptions(Options options);

    }
}
