// <auto-generated />
#nullable enable
using Monaco.Languages.Css;

namespace Monaco.Languages.Html
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.css.MarkupContent.html">Monaco API</see> for more details.
    /// </remarks>
    public interface MarkupContent
    {
        MarkupKind Kind { get; }

        string Value { get; }

    }
}
