// <auto-generated />
#nullable enable
using Monaco.Languages.Css;

namespace Monaco.Languages.Html
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.css.IValueData.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ValueData : IValueData
    {
        public object? Description { get; set; }

        public string Name { get; set; }

        public IReference[]? References { get; set; }

    }
}
