// <auto-generated />
#nullable enable
using Monaco.Languages.Css;

namespace Monaco.Languages.Html
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.html.IValueSet.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ValueSet : IValueSet
    {
        public string Name { get; set; }

        public IValueData[] Values { get; set; }

    }
}
