// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Worker
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/worker.IMirrorTextModel.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IMirrorTextModel, MirrorTextModel>))]
    public interface IMirrorTextModel
    {
        double Version { get; }

    }
}
