// <auto-generated />
#nullable enable

namespace Monaco.Worker
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/worker.IMirrorTextModel.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class MirrorTextModel : IMirrorTextModel
    {
        public double Version { get; set; }

    }
}
