#nullable enable

using System.Text;
using System.Text.Json;
using MonacoTypeEmitter.Model;

namespace MonacoTypeEmitter.Emitter;

/// <summary>
/// Emits C# source files from the intermediate Monaco type model.
/// Matches all existing patterns in MonacoEditorComponent/Monaco/.
/// </summary>
public sealed class CSharpEmitter
{
    private readonly MonacoModel _model;
    private readonly IgnoreList _ignoreList;
    private readonly string _outputRoot;
    private readonly HashSet<string> _knownEnumNames;

    /// <summary>
    /// Maps type names to their C# namespace for cross-namespace using directives.
    /// </summary>
    private readonly Dictionary<string, string> _typeToNamespace;

    public CSharpEmitter(MonacoModel model, IgnoreList ignoreList, string outputRoot, string repoRoot)
    {
        _model = model;
        _ignoreList = ignoreList;
        _outputRoot = outputRoot;

        // Collect all known enum names for type resolution
        _knownEnumNames = [];
        // Build type-to-namespace map for cross-namespace resolution
        _typeToNamespace = new Dictionary<string, string>();

        foreach (var ns in model.Namespaces)
        {
            var csharpNs = NameMapper.ToCSharpNamespace(ns.Name);

            foreach (var e in ns.Enums)
            {
                _knownEnumNames.Add(e.Name);
                _typeToNamespace.TryAdd(e.Name, csharpNs);
            }
            foreach (var ta in ns.TypeAliases)
            {
                if (IsStringLiteralUnion(ta.Type))
                {
                    _knownEnumNames.Add(ta.Name);
                    _typeToNamespace.TryAdd(ta.Name, csharpNs);
                }
            }
            foreach (var iface in ns.Interfaces)
            {
                _typeToNamespace.TryAdd(iface.Name, csharpNs);
            }
            foreach (var cls in ns.Classes)
            {
                _typeToNamespace.TryAdd(cls.Name, csharpNs);
            }
        }
    }

    /// <summary>
    /// Emits all C# files. Returns the list of files written (repo-relative paths).
    /// </summary>
    public List<string> EmitAll()
    {
        var written = new List<string>();

        foreach (var ns in _model.Namespaces)
        {
            var csharpNs = NameMapper.ToCSharpNamespace(ns.Name);
            var relDir = NameMapper.ToRelativeDirectory(ns.Name);

            // Emit enums
            foreach (var e in ns.Enums)
            {
                var path = EmitEnum(e, csharpNs, relDir);
                if (path is not null)
                    written.Add(path);
            }

            // Emit type aliases that are string literal unions as enums
            foreach (var ta in ns.TypeAliases)
            {
                if (IsStringLiteralUnion(ta.Type))
                {
                    var path = EmitTypeAliasEnum(ta, csharpNs, relDir);
                    if (path is not null)
                        written.Add(path);
                }
            }

            // Emit interfaces
            foreach (var iface in ns.Interfaces)
            {
                var path = EmitInterface(iface, csharpNs, relDir);
                if (path is not null)
                    written.Add(path);
            }

            // Emit classes (concrete implementations that pair with interfaces)
            foreach (var iface in ns.Interfaces)
            {
                if (iface.Name.StartsWith("I") && iface.Name.Length > 1 && char.IsUpper(iface.Name[1]))
                {
                    var className = iface.Name[1..];
                    var path = EmitConcreteClass(iface, className, csharpNs, relDir);
                    if (path is not null)
                        written.Add(path);
                }
            }

            // Emit actual classes from the model (like Uri, KeyMod)
            foreach (var cls in ns.Classes)
            {
                var path = EmitClass(cls, csharpNs, relDir);
                if (path is not null)
                    written.Add(path);
            }
        }

        return written;
    }

    private string? EmitEnum(EnumInfo enumInfo, string csharpNs, string relDir)
    {
        var fileName = $"{enumInfo.Name}.cs";
        var repoRelPath = GetRepoRelativePath(relDir, fileName);

        if (_ignoreList.IsIgnored(repoRelPath))
        {
            Console.Error.WriteLine($"  Skipping (ignored): {repoRelPath}");
            return null;
        }

        var sb = new StringBuilder();
        WriteAutoGeneratedHeader(sb);

        if (enumInfo.IsStringEnum)
        {
            sb.AppendLine("using System.Runtime.Serialization;");
            sb.AppendLine("using System.Text.Json.Serialization;");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {csharpNs}");
        sb.AppendLine("{");

        WriteDocComment(sb, enumInfo.Documentation, "    ");

        if (enumInfo.IsStringEnum)
        {
            sb.AppendLine($"    [JsonConverter(typeof(JsonStringEnumConverter<{enumInfo.Name}>))]");
        }

        sb.AppendLine($"    public enum {enumInfo.Name}");
        sb.AppendLine("    {");

        for (int i = 0; i < enumInfo.Members.Count; i++)
        {
            var member = enumInfo.Members[i];
            var memberName = NameMapper.ToCSharpEnumMemberName(member.Name);

            if (enumInfo.IsStringEnum)
            {
                var jsonValue = GetEnumMemberJsonValue(member);
                sb.AppendLine($"        [JsonStringEnumMemberName(\"{jsonValue}\")]");
                sb.AppendLine($"        [EnumMember(Value = \"{jsonValue}\")]");
            }

            if (!enumInfo.IsStringEnum && member.Value is not null)
            {
                var numValue = ResolveNumericValue(member.Value);
                if (numValue is not null)
                    sb.Append($"        {memberName} = {numValue}");
                else
                    sb.Append($"        {memberName}");
            }
            else
            {
                sb.Append($"        {memberName}");
            }

            if (i < enumInfo.Members.Count - 1)
                sb.AppendLine(",");
            else
                sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        WriteFile(relDir, fileName, sb.ToString());
        return repoRelPath;
    }

    private string? EmitTypeAliasEnum(TypeAliasInfo typeAlias, string csharpNs, string relDir)
    {
        var fileName = $"{typeAlias.Name}.cs";
        var repoRelPath = GetRepoRelativePath(relDir, fileName);

        if (_ignoreList.IsIgnored(repoRelPath))
        {
            Console.Error.WriteLine($"  Skipping (ignored): {repoRelPath}");
            return null;
        }

        var sb = new StringBuilder();
        WriteAutoGeneratedHeader(sb);
        sb.AppendLine("using System.Runtime.Serialization;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {csharpNs}");
        sb.AppendLine("{");

        WriteDocComment(sb, typeAlias.Documentation, "    ");

        sb.AppendLine($"    [JsonConverter(typeof(JsonStringEnumConverter<{typeAlias.Name}>))]");
        sb.AppendLine($"    public enum {typeAlias.Name}");
        sb.AppendLine("    {");

        var literals = GetStringLiteralValues(typeAlias.Type);
        for (int i = 0; i < literals.Count; i++)
        {
            var literal = literals[i];
            var memberName = NameMapper.ToCSharpEnumMemberName(literal);

            sb.AppendLine($"        [JsonStringEnumMemberName(\"{literal}\")]");
            sb.AppendLine($"        [EnumMember(Value = \"{literal}\")]");
            sb.Append($"        {memberName}");

            if (i < literals.Count - 1)
                sb.AppendLine(",");
            else
                sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        WriteFile(relDir, fileName, sb.ToString());
        return repoRelPath;
    }

    private string? EmitInterface(InterfaceInfo iface, string csharpNs, string relDir)
    {
        // Check if this interface has a matching concrete class
        // (I-prefix pattern: IFoo -> Foo)
        bool hasConcrete = iface.Name.StartsWith("I")
            && iface.Name.Length > 1
            && char.IsUpper(iface.Name[1]);

        var fileName = $"{iface.Name}.cs";
        var repoRelPath = GetRepoRelativePath(relDir, fileName);

        if (_ignoreList.IsIgnored(repoRelPath))
        {
            Console.Error.WriteLine($"  Skipping (ignored): {repoRelPath}");
            return null;
        }

        var sb = new StringBuilder();
        WriteAutoGeneratedHeader(sb);

        // Collect using directives needed for cross-namespace types
        var usings = CollectUsings(csharpNs, iface.Properties, iface.Methods, iface.Extends);

        // Need System.Text.Json.Serialization for [JsonConverter] (concrete pairing) or [JsonPropertyName]
        bool needsJsonSerialization = hasConcrete || iface.Properties.Any(p =>
            NameMapper.NeedsJsonPropertyName(p.Name, NameMapper.ToCSharpPropertyName(p.Name)));
        if (needsJsonSerialization)
            usings.Add("System.Text.Json.Serialization");

        WriteUsings(sb, usings);

        sb.AppendLine();
        sb.AppendLine($"namespace {csharpNs}");
        sb.AppendLine("{");

        WriteDocComment(sb, iface.Documentation, "    ");

        if (hasConcrete)
        {
            var concreteName = iface.Name[1..];
            sb.AppendLine($"    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<{iface.Name}, {concreteName}>))]");
        }

        var extendsClause = "";
        if (iface.Extends.Count > 0)
        {
            var baseTypes = iface.Extends.Select(FormatTypeReference).ToList();
            extendsClause = $" : {string.Join(", ", baseTypes)}";
        }

        var declTypeParams = FormatTypeParameters(iface.TypeParameters);
        sb.AppendLine($"    public interface {iface.Name}{declTypeParams}{extendsClause}");
        sb.AppendLine("    {");

        foreach (var prop in iface.Properties)
        {
            WriteDocComment(sb, prop.Documentation, "        ");

            var csharpType = MapPropertyType(prop);
            var propName = NameMapper.ToCSharpPropertyName(prop.Name);

            if (NameMapper.NeedsJsonPropertyName(prop.Name, propName))
            {
                sb.AppendLine($"        [JsonPropertyName(\"{prop.Name}\")]");
            }

            var getter = prop.IsReadonly ? "get;" : "get; set;";
            sb.AppendLine($"        {csharpType} {propName} {{ {getter} }}");
            sb.AppendLine();
        }

        // Emit methods
        foreach (var method in iface.Methods)
        {
            WriteMethod(sb, method, "        ", isInterface: true);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        WriteFile(relDir, fileName, sb.ToString());
        return repoRelPath;
    }

    private string? EmitConcreteClass(InterfaceInfo iface, string className, string csharpNs, string relDir)
    {
        var fileName = $"{className}.cs";
        var repoRelPath = GetRepoRelativePath(relDir, fileName);

        if (_ignoreList.IsIgnored(repoRelPath))
        {
            Console.Error.WriteLine($"  Skipping (ignored): {repoRelPath}");
            return null;
        }

        var sb = new StringBuilder();
        WriteAutoGeneratedHeader(sb);

        var usings = CollectUsings(csharpNs, iface.Properties, iface.Methods, iface.Extends);

        // Check if any property needs [JsonPropertyName] -- if so, import the serialization namespace
        bool needsJsonSerialization = iface.Properties.Any(p =>
            NameMapper.NeedsJsonPropertyName(p.Name, NameMapper.ToCSharpPropertyName(p.Name)));
        if (needsJsonSerialization)
            usings.Add("System.Text.Json.Serialization");

        WriteUsings(sb, usings);

        sb.AppendLine();
        sb.AppendLine($"namespace {csharpNs}");
        sb.AppendLine("{");

        WriteDocComment(sb, iface.Documentation, "    ");

        sb.AppendLine($"    public sealed class {className} : {iface.Name}");
        sb.AppendLine("    {");

        foreach (var prop in iface.Properties)
        {
            WriteDocComment(sb, prop.Documentation, "        ");

            var csharpType = MapPropertyType(prop);
            var propName = NameMapper.ToCSharpPropertyName(prop.Name);

            if (NameMapper.NeedsJsonPropertyName(prop.Name, propName))
            {
                sb.AppendLine($"        [JsonPropertyName(\"{prop.Name}\")]");
            }

            sb.AppendLine($"        public {csharpType} {propName} {{ get; set; }}");
            sb.AppendLine();
        }

        // Emit methods from interface (as public implementations)
        foreach (var method in iface.Methods)
        {
            WriteMethod(sb, method, "        ", isInterface: false);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        WriteFile(relDir, fileName, sb.ToString());
        return repoRelPath;
    }

    private string? EmitClass(ClassInfo cls, string csharpNs, string relDir)
    {
        var fileName = $"{cls.Name}.cs";
        var repoRelPath = GetRepoRelativePath(relDir, fileName);

        if (_ignoreList.IsIgnored(repoRelPath))
        {
            Console.Error.WriteLine($"  Skipping (ignored): {repoRelPath}");
            return null;
        }

        var sb = new StringBuilder();
        WriteAutoGeneratedHeader(sb);

        // Build the list of base type references for using resolution
        var baseTypeRefs = new List<TypeReference>();
        if (cls.Extends is not null)
            baseTypeRefs.Add(cls.Extends);
        baseTypeRefs.AddRange(cls.Implements);

        var usings = CollectUsings(csharpNs, cls.Properties, cls.Methods, baseTypeRefs);

        // Check if any property needs [JsonPropertyName] -- if so, import the serialization namespace
        bool needsJsonSerialization = cls.Properties.Any(p =>
            NameMapper.NeedsJsonPropertyName(p.Name, NameMapper.ToCSharpPropertyName(p.Name)));
        if (needsJsonSerialization)
            usings.Add("System.Text.Json.Serialization");

        WriteUsings(sb, usings);

        sb.AppendLine();
        sb.AppendLine($"namespace {csharpNs}");
        sb.AppendLine("{");

        WriteDocComment(sb, cls.Documentation, "    ");

        var baseClause = "";
        var bases = new List<string>();
        if (cls.Extends is not null)
            bases.Add(FormatTypeReference(cls.Extends));
        foreach (var impl in cls.Implements)
            bases.Add(FormatTypeReference(impl));
        if (bases.Count > 0)
            baseClause = $" : {string.Join(", ", bases)}";

        var declTypeParams = FormatTypeParameters(cls.TypeParameters);
        sb.AppendLine($"    public sealed class {cls.Name}{declTypeParams}{baseClause}");
        sb.AppendLine("    {");

        foreach (var prop in cls.Properties)
        {
            WriteDocComment(sb, prop.Documentation, "        ");

            var csharpType = MapClassPropertyType(prop);
            var propName = NameMapper.ToCSharpPropertyName(prop.Name);

            if (NameMapper.NeedsJsonPropertyName(prop.Name, propName))
            {
                sb.AppendLine($"        [JsonPropertyName(\"{prop.Name}\")]");
            }

            var accessor = prop.IsReadonly ? "get;" : "get; set;";
            sb.AppendLine($"        public {csharpType} {propName} {{ {accessor} }}");
            sb.AppendLine();
        }

        // Emit methods
        foreach (var method in cls.Methods)
        {
            WriteMethod(sb, method, "        ", isInterface: false);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        WriteFile(relDir, fileName, sb.ToString());
        return repoRelPath;
    }

    // --- Method emission ---

    private void WriteMethod(StringBuilder sb, MethodInfo method, string indent, bool isInterface)
    {
        WriteDocComment(sb, method.Documentation, indent);

        var returnType = TypeMapper.ToCSharpType(method.ReturnType);
        var methodName = NameMapper.ToCSharpPropertyName(method.Name);
        var parameters = FormatParameters(method.Parameters);
        var typeParams = FormatTypeParameters(method.TypeParameters);

        if (isInterface)
        {
            sb.AppendLine($"{indent}{returnType} {methodName}{typeParams}({parameters});");
        }
        else
        {
            var staticMod = method.IsStatic ? "static " : "";
            sb.AppendLine($"{indent}public {staticMod}{returnType} {methodName}{typeParams}({parameters}) => throw new NotImplementedException();");
        }
        sb.AppendLine();

        // Emit overloads
        foreach (var overload in method.Overloads)
        {
            WriteDocComment(sb, overload.Documentation, indent);

            var olReturnType = TypeMapper.ToCSharpType(overload.ReturnType);
            var olParams = FormatParameters(overload.Parameters);
            var olTypeParams = FormatTypeParameters(overload.TypeParameters);

            if (isInterface)
            {
                sb.AppendLine($"{indent}{olReturnType} {methodName}{olTypeParams}({olParams});");
            }
            else
            {
                var staticMod = method.IsStatic ? "static " : "";
                sb.AppendLine($"{indent}public {staticMod}{olReturnType} {methodName}{olTypeParams}({olParams}) => throw new NotImplementedException();");
            }
            sb.AppendLine();
        }
    }

    private string FormatParameters(List<ParameterInfo> parameters)
    {
        if (parameters.Count == 0)
            return "";

        return string.Join(", ", parameters.Select(p =>
        {
            var type = TypeMapper.ToCSharpType(p.Type);

            if (p.IsRestParameter)
            {
                // TS rest param `...args: T[]` maps to `params T[] args`.
                // The mapped type is already T[], so use it directly.
                // If not already an array, wrap in [].
                // Do NOT apply optional/nullable for rest params (they accept zero elements).
                if (type.EndsWith("[]"))
                    return $"params {type} {EscapeCSharpKeyword(p.Name)}";
                return $"params {type}[] {EscapeCSharpKeyword(p.Name)}";
            }

            if (p.IsOptional && !type.EndsWith("?"))
            {
                if (TypeMapper.IsValueType(type) || TypeMapper.IsEnumType(type, _knownEnumNames))
                    type += "?";
                else
                    type += "?";
            }
            return $"{type} {EscapeCSharpKeyword(p.Name)}";
        }));
    }

    private static string FormatTypeParameters(List<TypeParameterInfo> typeParams)
    {
        if (typeParams.Count == 0)
            return "";

        return $"<{string.Join(", ", typeParams.Select(tp => tp.Name))}>";
    }

    /// <summary>
    /// Formats a TypeReference (e.g., extends/implements) with its type arguments.
    /// For example: "IDisposable" or "IComparer&lt;T&gt;".
    /// </summary>
    private static string FormatTypeReference(TypeReference typeRef)
    {
        if (typeRef.TypeArguments.Count == 0)
            return typeRef.Name;

        var typeArgs = string.Join(", ", typeRef.TypeArguments.Select(ta => TypeMapper.ToCSharpType(ta)));
        return $"{typeRef.Name}<{typeArgs}>";
    }

    private static string EscapeCSharpKeyword(string name)
    {
        // C# reserved keywords that might appear as parameter names
        var keywords = new HashSet<string>
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
            "char", "checked", "class", "const", "continue", "decimal", "default",
            "delegate", "do", "double", "else", "enum", "event", "explicit",
            "extern", "false", "finally", "fixed", "float", "for", "foreach",
            "goto", "if", "implicit", "in", "int", "interface", "internal",
            "is", "lock", "long", "namespace", "new", "null", "object",
            "operator", "out", "override", "params", "private", "protected",
            "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
            "sizeof", "stackalloc", "static", "string", "struct", "switch",
            "this", "throw", "true", "try", "typeof", "uint", "ulong",
            "unchecked", "unsafe", "ushort", "using", "virtual", "void",
            "volatile", "while", "value", "var"
        };

        return keywords.Contains(name) ? $"@{name}" : name;
    }

    // --- Using directive collection ---

    /// <summary>
    /// Collects using directives needed for cross-namespace type references,
    /// including base types from extends/implements clauses.
    /// </summary>
    private HashSet<string> CollectUsings(string currentNamespace,
        List<PropertyInfo> properties, List<MethodInfo> methods,
        IEnumerable<TypeReference>? baseTypeRefs = null)
    {
        var usings = new HashSet<string>();

        foreach (var prop in properties)
        {
            CollectTypeUsings(prop.Type, currentNamespace, usings);
        }

        foreach (var method in methods)
        {
            CollectTypeUsings(method.ReturnType, currentNamespace, usings);
            foreach (var param in method.Parameters)
            {
                CollectTypeUsings(param.Type, currentNamespace, usings);
            }
            foreach (var overload in method.Overloads)
            {
                CollectTypeUsings(overload.ReturnType, currentNamespace, usings);
                foreach (var param in overload.Parameters)
                {
                    CollectTypeUsings(param.Type, currentNamespace, usings);
                }
            }
        }

        // Resolve extends/implements base type references
        if (baseTypeRefs is not null)
        {
            foreach (var typeRef in baseTypeRefs)
            {
                if (_typeToNamespace.TryGetValue(typeRef.Name, out var ns) && ns != currentNamespace)
                {
                    usings.Add(ns);
                }
                // Also resolve type arguments of base type references
                foreach (var ta in typeRef.TypeArguments)
                {
                    CollectTypeUsings(ta, currentNamespace, usings);
                }
            }
        }

        return usings;
    }

    private void CollectTypeUsings(TypeInfo type, string currentNamespace, HashSet<string> usings)
    {
        switch (type.Kind)
        {
            case "reference":
                if (type.Name is not null && _typeToNamespace.TryGetValue(type.Name, out var ns))
                {
                    if (ns != currentNamespace)
                        usings.Add(ns);
                }
                if (type.TypeArguments is not null)
                {
                    foreach (var ta in type.TypeArguments)
                        CollectTypeUsings(ta, currentNamespace, usings);
                }
                break;
            case "array":
                if (type.ElementType is not null)
                    CollectTypeUsings(type.ElementType, currentNamespace, usings);
                break;
            case "union":
            case "intersection":
                if (type.Types is not null)
                {
                    foreach (var t in type.Types)
                        CollectTypeUsings(t, currentNamespace, usings);
                }
                break;
            case "typeOperator":
                if (type.Type is not null)
                    CollectTypeUsings(type.Type, currentNamespace, usings);
                break;
        }
    }

    private static void WriteUsings(StringBuilder sb, HashSet<string> usings)
    {
        if (usings.Count == 0)
            return;

        foreach (var u in usings.OrderBy(x => x))
        {
            sb.AppendLine($"using {u};");
        }
    }

    // --- Property type mapping ---

    private string MapPropertyType(PropertyInfo prop)
    {
        var baseType = TypeMapper.ToCSharpType(prop.Type);

        // If optional, make nullable
        if (prop.IsOptional)
        {
            if (TypeMapper.IsValueType(baseType) || TypeMapper.IsEnumType(baseType, _knownEnumNames))
            {
                return baseType + "?";
            }

            // Reference types (including arrays): add ? suffix if not already nullable
            if (!baseType.EndsWith("?"))
                return baseType + "?";
        }

        return baseType;
    }

    private string MapClassPropertyType(PropertyInfo prop)
    {
        var baseType = TypeMapper.ToCSharpType(prop.Type);

        // For class properties, optional means nullable
        if (prop.IsOptional)
        {
            if (TypeMapper.IsValueType(baseType) || TypeMapper.IsEnumType(baseType, _knownEnumNames))
            {
                return baseType + "?";
            }

            // Reference types (including arrays): add ? suffix if not already nullable
            if (!baseType.EndsWith("?"))
                return baseType + "?";
        }

        return baseType;
    }

    // --- Enum helpers ---

    private static string GetEnumMemberJsonValue(EnumMemberInfo member)
    {
        // If the enum member has an explicit string value, use it
        if (member.Value is string strVal)
            return strVal;

        // Handle JsonElement (STJ deserializes object? as JsonElement)
        if (member.Value is JsonElement je && je.ValueKind == JsonValueKind.String)
            return je.GetString() ?? NameMapper.ToCamelCase(member.Name);

        // Otherwise, use the camelCase form of the member name
        return NameMapper.ToCamelCase(member.Name);
    }

    /// <summary>
    /// Extracts a numeric value from an object that may be a JsonElement.
    /// </summary>
    private static long? ResolveNumericValue(object? value)
    {
        if (value is null)
            return null;

        if (value is JsonElement je)
        {
            return je.ValueKind switch
            {
                JsonValueKind.Number => je.TryGetInt64(out var l) ? l : (long)je.GetDouble(),
                _ => null
            };
        }

        if (value is IConvertible conv)
            return conv.ToInt64(null);

        return null;
    }

    /// <summary>
    /// Resolves a string value from an object that may be a JsonElement.
    /// Only returns a value for actual strings -- does not use ToString() fallback
    /// to prevent numeric/bool literals from being misclassified as string values.
    /// </summary>
    private static string? ResolveStringValue(object? value)
    {
        if (value is null)
            return null;

        if (value is string s)
            return s;

        if (value is JsonElement je && je.ValueKind == JsonValueKind.String)
            return je.GetString();

        // Do NOT fall back to ToString() -- non-string values (numbers, bools)
        // must not be treated as string literal union members.
        return null;
    }

    private static bool IsStringLiteralUnion(TypeInfo type)
    {
        if (type.Kind != "union" || type.Types is null)
            return false;

        var nonNull = type.Types
            .Where(t => !(t.Kind == "primitive" && (t.Name == "null" || t.Name == "undefined")))
            .ToList();

        // Must be all string literals -- ResolveStringValue returns null for non-strings
        return nonNull.Count > 0 && nonNull.All(t =>
            t.Kind == "literal" && ResolveStringValue(t.Value) is not null);
    }

    private static List<string> GetStringLiteralValues(TypeInfo type)
    {
        if (type.Kind != "union" || type.Types is null)
            return [];

        return type.Types
            .Where(t => t.Kind == "literal" && ResolveStringValue(t.Value) is not null)
            .Select(t => ResolveStringValue(t.Value)!)
            .ToList();
    }

    // --- File output helpers ---

    private static string GetRepoRelativePath(string relDir, string fileName)
    {
        if (string.IsNullOrEmpty(relDir))
            return $"MonacoEditorComponent/Monaco/{fileName}";

        return $"MonacoEditorComponent/Monaco/{relDir}/{fileName}";
    }

    private void WriteFile(string relDir, string fileName, string content)
    {
        var dir = string.IsNullOrEmpty(relDir)
            ? _outputRoot
            : Path.Combine(_outputRoot, relDir);

        Directory.CreateDirectory(dir);

        var fullPath = Path.Combine(dir, fileName);
        File.WriteAllText(fullPath, content);
        Console.Error.WriteLine($"  Written: {GetRepoRelativePath(relDir, fileName)}");
    }

    private static void WriteAutoGeneratedHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
    }

    private static void WriteDocComment(StringBuilder sb, string? documentation, string indent)
    {
        if (string.IsNullOrWhiteSpace(documentation))
            return;

        sb.AppendLine($"{indent}/// <summary>");
        foreach (var line in documentation.Split('\n'))
        {
            var trimmed = line.TrimEnd('\r');
            if (string.IsNullOrWhiteSpace(trimmed))
                sb.AppendLine($"{indent}///");
            else
                sb.AppendLine($"{indent}/// {EscapeXml(trimmed)}");
        }
        sb.AppendLine($"{indent}/// </summary>");
    }

    private static string EscapeXml(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}
