#nullable enable

using System.Text;
using System.Text.Json;
using MonacoTypeEmitter.Model;

namespace MonacoTypeEmitter.Emitter;

/// <summary>
/// Emits C# source files from the intermediate Monaco type model.
/// Matches all existing patterns in MonacoEditorComponent/Monaco/.
/// </summary>
public sealed class CSharpEmitter
{
    private readonly MonacoModel _model;
    private readonly IgnoreList _ignoreList;
    private readonly string _outputRoot;
    private readonly string _repoRoot;
    private readonly HashSet<string> _knownEnumNames;

    public CSharpEmitter(MonacoModel model, IgnoreList ignoreList, string outputRoot, string repoRoot)
    {
        _model = model;
        _ignoreList = ignoreList;
        _outputRoot = outputRoot;
        _repoRoot = repoRoot;

        // Collect all known enum names for type resolution
        _knownEnumNames = [];
        foreach (var ns in model.Namespaces)
        {
            foreach (var e in ns.Enums)
            {
                _knownEnumNames.Add(e.Name);
            }
            // Type aliases that are string literal unions also become enums
            foreach (var ta in ns.TypeAliases)
            {
                if (IsStringLiteralUnion(ta.Type))
                {
                    _knownEnumNames.Add(ta.Name);
                }
            }
        }
    }

    /// <summary>
    /// Emits all C# files. Returns the list of files written (repo-relative paths).
    /// </summary>
    public List<string> EmitAll()
    {
        var written = new List<string>();

        foreach (var ns in _model.Namespaces)
        {
            var csharpNs = NameMapper.ToCSharpNamespace(ns.Name);
            var relDir = NameMapper.ToRelativeDirectory(ns.Name);

            // Emit enums
            foreach (var e in ns.Enums)
            {
                var path = EmitEnum(e, csharpNs, relDir);
                if (path is not null)
                    written.Add(path);
            }

            // Emit type aliases that are string literal unions as enums
            foreach (var ta in ns.TypeAliases)
            {
                if (IsStringLiteralUnion(ta.Type))
                {
                    var path = EmitTypeAliasEnum(ta, csharpNs, relDir);
                    if (path is not null)
                        written.Add(path);
                }
            }

            // Emit interfaces
            foreach (var iface in ns.Interfaces)
            {
                var path = EmitInterface(iface, csharpNs, relDir, ns);
                if (path is not null)
                    written.Add(path);
            }

            // Emit classes (concrete implementations that pair with interfaces)
            foreach (var iface in ns.Interfaces)
            {
                if (iface.Name.StartsWith("I") && iface.Name.Length > 1 && char.IsUpper(iface.Name[1]))
                {
                    var className = iface.Name[1..];
                    var path = EmitConcreteClass(iface, className, csharpNs, relDir);
                    if (path is not null)
                        written.Add(path);
                }
            }

            // Emit actual classes from the model (like Uri, KeyMod)
            foreach (var cls in ns.Classes)
            {
                var path = EmitClass(cls, csharpNs, relDir);
                if (path is not null)
                    written.Add(path);
            }
        }

        return written;
    }

    private string? EmitEnum(EnumInfo enumInfo, string csharpNs, string relDir)
    {
        var fileName = $"{enumInfo.Name}.cs";
        var repoRelPath = GetRepoRelativePath(relDir, fileName);

        if (_ignoreList.IsIgnored(repoRelPath))
        {
            Console.Error.WriteLine($"  Skipping (ignored): {repoRelPath}");
            return null;
        }

        var sb = new StringBuilder();
        WriteAutoGeneratedHeader(sb);

        if (enumInfo.IsStringEnum)
        {
            sb.AppendLine("using System.Runtime.Serialization;");
            sb.AppendLine("using System.Text.Json.Serialization;");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {csharpNs}");
        sb.AppendLine("{");

        WriteDocComment(sb, enumInfo.Documentation, "    ");

        if (enumInfo.IsStringEnum)
        {
            sb.AppendLine($"    [JsonConverter(typeof(JsonStringEnumConverter<{enumInfo.Name}>))]");
        }

        sb.AppendLine($"    public enum {enumInfo.Name}");
        sb.AppendLine("    {");

        for (int i = 0; i < enumInfo.Members.Count; i++)
        {
            var member = enumInfo.Members[i];
            var memberName = NameMapper.ToCSharpEnumMemberName(member.Name);

            if (enumInfo.IsStringEnum)
            {
                var jsonValue = GetEnumMemberJsonValue(member);
                sb.AppendLine($"        [JsonStringEnumMemberName(\"{jsonValue}\")]");
                sb.AppendLine($"        [EnumMember(Value = \"{jsonValue}\")]");
            }

            if (!enumInfo.IsStringEnum && member.Value is not null)
            {
                var numValue = ResolveNumericValue(member.Value);
                if (numValue is not null)
                    sb.Append($"        {memberName} = {numValue}");
                else
                    sb.Append($"        {memberName}");
            }
            else
            {
                sb.Append($"        {memberName}");
            }

            if (i < enumInfo.Members.Count - 1)
                sb.AppendLine(",");
            else
                sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        WriteFile(relDir, fileName, sb.ToString());
        return repoRelPath;
    }

    private string? EmitTypeAliasEnum(TypeAliasInfo typeAlias, string csharpNs, string relDir)
    {
        var fileName = $"{typeAlias.Name}.cs";
        var repoRelPath = GetRepoRelativePath(relDir, fileName);

        if (_ignoreList.IsIgnored(repoRelPath))
        {
            Console.Error.WriteLine($"  Skipping (ignored): {repoRelPath}");
            return null;
        }

        var sb = new StringBuilder();
        WriteAutoGeneratedHeader(sb);
        sb.AppendLine("using System.Runtime.Serialization;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {csharpNs}");
        sb.AppendLine("{");

        WriteDocComment(sb, typeAlias.Documentation, "    ");

        sb.AppendLine($"    [JsonConverter(typeof(JsonStringEnumConverter<{typeAlias.Name}>))]");
        sb.AppendLine($"    public enum {typeAlias.Name}");
        sb.AppendLine("    {");

        var literals = GetStringLiteralValues(typeAlias.Type);
        for (int i = 0; i < literals.Count; i++)
        {
            var literal = literals[i];
            var memberName = NameMapper.ToCSharpEnumMemberName(literal);

            sb.AppendLine($"        [JsonStringEnumMemberName(\"{literal}\")]");
            sb.AppendLine($"        [EnumMember(Value = \"{literal}\")]");
            sb.Append($"        {memberName}");

            if (i < literals.Count - 1)
                sb.AppendLine(",");
            else
                sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        WriteFile(relDir, fileName, sb.ToString());
        return repoRelPath;
    }

    private string? EmitInterface(InterfaceInfo iface, string csharpNs, string relDir, NamespaceInfo ns)
    {
        // Check if this interface has a matching concrete class
        // (I-prefix pattern: IFoo -> Foo)
        bool hasConcrete = iface.Name.StartsWith("I")
            && iface.Name.Length > 1
            && char.IsUpper(iface.Name[1]);

        var fileName = $"{iface.Name}.cs";
        var repoRelPath = GetRepoRelativePath(relDir, fileName);

        if (_ignoreList.IsIgnored(repoRelPath))
        {
            Console.Error.WriteLine($"  Skipping (ignored): {repoRelPath}");
            return null;
        }

        var sb = new StringBuilder();
        WriteAutoGeneratedHeader(sb);

        var needsStjUsing = hasConcrete; // For InterfaceToClassConverter
        var needsHelperUsing = hasConcrete;

        if (needsStjUsing)
            sb.AppendLine("using System.Text.Json.Serialization;");

        sb.AppendLine();
        sb.AppendLine($"namespace {csharpNs}");
        sb.AppendLine("{");

        WriteDocComment(sb, iface.Documentation, "    ");

        if (hasConcrete)
        {
            var concreteName = iface.Name[1..];
            sb.AppendLine($"    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<{iface.Name}, {concreteName}>))]");
        }

        var extendsClause = "";
        if (iface.Extends.Count > 0)
        {
            var baseTypes = iface.Extends.Select(e => e.Name).ToList();
            extendsClause = $" : {string.Join(", ", baseTypes)}";
        }

        sb.AppendLine($"    public interface {iface.Name}{extendsClause}");
        sb.AppendLine("    {");

        foreach (var prop in iface.Properties)
        {
            WriteDocComment(sb, prop.Documentation, "        ");

            var csharpType = MapPropertyType(prop);
            var propName = NameMapper.ToCSharpPropertyName(prop.Name);

            if (NameMapper.NeedsJsonPropertyName(prop.Name, propName))
            {
                sb.AppendLine($"        [JsonPropertyName(\"{prop.Name}\")]");
            }

            var getter = prop.IsReadonly ? "get;" : "get; set;";
            sb.AppendLine($"        {csharpType} {propName} {{ {getter} }}");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        WriteFile(relDir, fileName, sb.ToString());
        return repoRelPath;
    }

    private string? EmitConcreteClass(InterfaceInfo iface, string className, string csharpNs, string relDir)
    {
        var fileName = $"{className}.cs";
        var repoRelPath = GetRepoRelativePath(relDir, fileName);

        if (_ignoreList.IsIgnored(repoRelPath))
        {
            Console.Error.WriteLine($"  Skipping (ignored): {repoRelPath}");
            return null;
        }

        var sb = new StringBuilder();
        WriteAutoGeneratedHeader(sb);
        sb.AppendLine();
        sb.AppendLine($"namespace {csharpNs}");
        sb.AppendLine("{");

        WriteDocComment(sb, iface.Documentation, "    ");

        sb.AppendLine($"    public sealed class {className} : {iface.Name}");
        sb.AppendLine("    {");

        foreach (var prop in iface.Properties)
        {
            WriteDocComment(sb, prop.Documentation, "        ");

            var csharpType = MapPropertyType(prop);
            var propName = NameMapper.ToCSharpPropertyName(prop.Name);

            sb.AppendLine($"        public {csharpType} {propName} {{ get; set; }}");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        WriteFile(relDir, fileName, sb.ToString());
        return repoRelPath;
    }

    private string? EmitClass(ClassInfo cls, string csharpNs, string relDir)
    {
        var fileName = $"{cls.Name}.cs";
        var repoRelPath = GetRepoRelativePath(relDir, fileName);

        if (_ignoreList.IsIgnored(repoRelPath))
        {
            Console.Error.WriteLine($"  Skipping (ignored): {repoRelPath}");
            return null;
        }

        var sb = new StringBuilder();
        WriteAutoGeneratedHeader(sb);
        sb.AppendLine();
        sb.AppendLine($"namespace {csharpNs}");
        sb.AppendLine("{");

        WriteDocComment(sb, cls.Documentation, "    ");

        var baseClause = "";
        var bases = new List<string>();
        if (cls.Extends is not null)
            bases.Add(cls.Extends.Name);
        foreach (var impl in cls.Implements)
            bases.Add(impl.Name);
        if (bases.Count > 0)
            baseClause = $" : {string.Join(", ", bases)}";

        sb.AppendLine($"    public sealed class {cls.Name}{baseClause}");
        sb.AppendLine("    {");

        foreach (var prop in cls.Properties)
        {
            WriteDocComment(sb, prop.Documentation, "        ");

            var csharpType = MapClassPropertyType(prop);
            var propName = NameMapper.ToCSharpPropertyName(prop.Name);

            var accessor = prop.IsReadonly ? "get;" : "get; set;";
            sb.AppendLine($"        public {csharpType} {propName} {{ {accessor} }}");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        WriteFile(relDir, fileName, sb.ToString());
        return repoRelPath;
    }

    private string MapPropertyType(PropertyInfo prop)
    {
        var baseType = TypeMapper.ToCSharpType(prop.Type);

        // If optional, make nullable
        if (prop.IsOptional)
        {
            if (TypeMapper.IsValueType(baseType) || TypeMapper.IsEnumType(baseType, _knownEnumNames))
            {
                return baseType + "?";
            }

            // Reference types: add ? suffix if not already
            if (!baseType.EndsWith("?") && !baseType.EndsWith("[]"))
                return baseType + "?";
        }

        return baseType;
    }

    private string MapClassPropertyType(PropertyInfo prop)
    {
        var baseType = TypeMapper.ToCSharpType(prop.Type);

        // For class properties, optional means nullable
        if (prop.IsOptional)
        {
            if (TypeMapper.IsValueType(baseType) || TypeMapper.IsEnumType(baseType, _knownEnumNames))
            {
                return baseType + "?";
            }

            if (!baseType.EndsWith("?") && !baseType.EndsWith("[]"))
                return baseType + "?";
        }

        return baseType;
    }

    private static string GetEnumMemberJsonValue(EnumMemberInfo member)
    {
        // If the enum member has an explicit string value, use it
        if (member.Value is string strVal)
            return strVal;

        // Handle JsonElement (STJ deserializes object? as JsonElement)
        if (member.Value is JsonElement je && je.ValueKind == JsonValueKind.String)
            return je.GetString() ?? NameMapper.ToCamelCase(member.Name);

        // Otherwise, use the camelCase form of the member name
        return NameMapper.ToCamelCase(member.Name);
    }

    /// <summary>
    /// Extracts a numeric value from an object that may be a JsonElement.
    /// </summary>
    private static long? ResolveNumericValue(object? value)
    {
        if (value is null)
            return null;

        if (value is JsonElement je)
        {
            return je.ValueKind switch
            {
                JsonValueKind.Number => je.TryGetInt64(out var l) ? l : (long)je.GetDouble(),
                _ => null
            };
        }

        if (value is IConvertible conv)
            return conv.ToInt64(null);

        return null;
    }

    /// <summary>
    /// Resolves a string value from an object that may be a JsonElement.
    /// </summary>
    private static string? ResolveStringValue(object? value)
    {
        if (value is null)
            return null;

        if (value is string s)
            return s;

        if (value is JsonElement je && je.ValueKind == JsonValueKind.String)
            return je.GetString();

        return value.ToString();
    }

    private static bool IsStringLiteralUnion(TypeInfo type)
    {
        if (type.Kind != "union" || type.Types is null)
            return false;

        var nonNull = type.Types
            .Where(t => !(t.Kind == "primitive" && (t.Name == "null" || t.Name == "undefined")))
            .ToList();

        return nonNull.Count > 0 && nonNull.All(t =>
            t.Kind == "literal" && ResolveStringValue(t.Value) is not null);
    }

    private static List<string> GetStringLiteralValues(TypeInfo type)
    {
        if (type.Kind != "union" || type.Types is null)
            return [];

        return type.Types
            .Where(t => t.Kind == "literal" && ResolveStringValue(t.Value) is not null)
            .Select(t => ResolveStringValue(t.Value)!)
            .ToList();
    }

    private string GetRepoRelativePath(string relDir, string fileName)
    {
        if (string.IsNullOrEmpty(relDir))
            return $"MonacoEditorComponent/Monaco/{fileName}";

        return $"MonacoEditorComponent/Monaco/{relDir}/{fileName}";
    }

    private void WriteFile(string relDir, string fileName, string content)
    {
        var dir = string.IsNullOrEmpty(relDir)
            ? _outputRoot
            : Path.Combine(_outputRoot, relDir);

        Directory.CreateDirectory(dir);

        var fullPath = Path.Combine(dir, fileName);
        File.WriteAllText(fullPath, content);
        Console.Error.WriteLine($"  Written: {GetRepoRelativePath(relDir, fileName)}");
    }

    private static void WriteAutoGeneratedHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
    }

    private static void WriteDocComment(StringBuilder sb, string? documentation, string indent)
    {
        if (string.IsNullOrWhiteSpace(documentation))
            return;

        sb.AppendLine($"{indent}/// <summary>");
        foreach (var line in documentation.Split('\n'))
        {
            var trimmed = line.TrimEnd('\r');
            if (string.IsNullOrWhiteSpace(trimmed))
                sb.AppendLine($"{indent}///");
            else
                sb.AppendLine($"{indent}/// {EscapeXml(trimmed)}");
        }
        sb.AppendLine($"{indent}/// </summary>");
    }

    private static string EscapeXml(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}
