// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Languages.Json
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.json.IJSONWorker.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IJSONWorker, JSONWorker>))]
    public interface IJSONWorker
    {
        /// <returns>A task representing the asynchronous operation.</returns>
        object GetMatchingSchemas(string uri);

        /// <returns>A task representing the asynchronous operation.</returns>
        object ParseJSONDocument(string uri);

    }
}
