// <auto-generated />
#nullable enable

namespace Monaco.Languages.Json
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.json.NumberASTNode.html">Monaco API</see> for more details.
    /// </remarks>
    public interface NumberASTNode : BaseASTNode
    {
        bool IsInteger { get; }

        string Type { get; }

        double Value { get; }

    }
}
