// <auto-generated />
#nullable enable

namespace Monaco.Languages.Json
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.json.PropertyASTNode.html">Monaco API</see> for more details.
    /// </remarks>
    public interface PropertyASTNode : BaseASTNode
    {
        ASTNode[] Children { get; }

        double? ColonOffset { get; }

        StringASTNode KeyNode { get; }

        string Type { get; }

        ASTNode? ValueNode { get; }

    }
}
