// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/editor.AccessibilitySupport.html">Monaco API</see> for more details.
    /// </remarks>
    public enum AccessibilitySupport
    {
        Disabled = 1,
        Enabled = 2,
        /// <summary>
        /// This should be the browser case where it is not known if a screen reader is attached or no.
        /// </summary>
        Unknown = 0
    }
}
