// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/classes/editor.ApplyUpdateResult.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ApplyUpdateResult<T>
    {
        public bool DidChange { get; }

        public T NewValue { get; }

        public ApplyUpdateResult(T newValue, bool didChange)
        {
            NewValue = newValue;
            DidChange = didChange;
        }

    }
}
