// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/classes/editor.BareFontInfo.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class BareFontInfo
    {
        public void _bareFontInfoBrand { get; }

        public string FontFamily { get; }

        public string FontFeatureSettings { get; }

        public double FontSize { get; }

        public string FontVariationSettings { get; }

        public string FontWeight { get; }

        public double LetterSpacing { get; }

        public double LineHeight { get; }

        public double PixelRatio { get; }

    }
}
