// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IBaseMouseTarget.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class BaseMouseTarget : IBaseMouseTarget
    {
        /// <summary>
        /// The target element
        /// </summary>
        public object Element { get; set; }

        /// <summary>
        /// Desired mouse column (e.g. when position.column gets clamped to text length -- clicking after text on a line).
        /// </summary>
        public double MouseColumn { get; set; }

        /// <summary>
        /// The 'approximate' editor position
        /// </summary>
        public Position Position { get; set; }

        /// <summary>
        /// The 'approximate' editor range
        /// </summary>
        public Range Range { get; set; }

    }
}
