// <auto-generated />
#nullable enable
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/types/editor.BuiltinTheme.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(JsonStringEnumConverter<BuiltinTheme>))]
    public enum BuiltinTheme
    {
        [JsonStringEnumMemberName("vs")]
        [EnumMember(Value = "vs")]
        Vs,
        [JsonStringEnumMemberName("vs-dark")]
        [EnumMember(Value = "vs-dark")]
        VsDark,
        [JsonStringEnumMemberName("hc-black")]
        [EnumMember(Value = "hc-black")]
        HcBlack,
        [JsonStringEnumMemberName("hc-light")]
        [EnumMember(Value = "hc-light")]
        HcLight
    }
}
