// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// A change
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IChange.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class Change : IChange
    {
        public double ModifiedEndLineNumber { get; set; }

        public double ModifiedStartLineNumber { get; set; }

        public double OriginalEndLineNumber { get; set; }

        public double OriginalStartLineNumber { get; set; }

    }
}
