// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// A character level change.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICharChange.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class CharChange : ICharChange
    {
        public double ModifiedEndColumn { get; set; }

        public double ModifiedStartColumn { get; set; }

        public double OriginalEndColumn { get; set; }

        public double OriginalStartColumn { get; set; }

    }
}
