// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <summary>
    /// A rich code editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICodeEditor.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class CodeEditor : ICodeEditor
    {
        /// <summary>
        /// Some editor operations fire multiple events at once.
        /// To allow users to react to multiple events fired by a single operation,
        /// the editor fires a begin update before the operation and an end update after the operation.
        /// Whenever the editor fires `onBeginUpdate`, it will also fire `onEndUpdate` once the operation finishes.
        /// Note that not all operations are bracketed by `onBeginUpdate` and `onEndUpdate`.
        /// </summary>
        public IEvent<object> OnBeginUpdate { get; set; }

        /// <summary>
        /// An event emitted on a "contextmenu".
        /// </summary>
        public IEvent<IEditorMouseEvent> OnContextMenu { get; set; }

        /// <summary>
        /// An event emitted when editing failed because the editor is read-only.
        /// </summary>
        public IEvent<object> OnDidAttemptReadOnlyEdit { get; set; }

        /// <summary>
        /// An event emitted when the text inside this editor lost focus (i.e. cursor stops blinking).
        /// </summary>
        public IEvent<object> OnDidBlurEditorText { get; set; }

        /// <summary>
        /// An event emitted when the text inside this editor or an editor widget lost focus.
        /// </summary>
        public IEvent<object> OnDidBlurEditorWidget { get; set; }

        /// <summary>
        /// An event emitted when the configuration of the editor has changed. (e.g. `editor.updateOptions()`)
        /// </summary>
        public IEvent<ConfigurationChangedEvent> OnDidChangeConfiguration { get; set; }

        /// <summary>
        /// An event emitted when the cursor position has changed.
        /// </summary>
        public IEvent<ICursorPositionChangedEvent> OnDidChangeCursorPosition { get; set; }

        /// <summary>
        /// An event emitted when the cursor selection has changed.
        /// </summary>
        public IEvent<ICursorSelectionChangedEvent> OnDidChangeCursorSelection { get; set; }

        /// <summary>
        /// An event emitted when hidden areas change in the editor (e.g. due to folding).
        /// </summary>
        public IEvent<object> OnDidChangeHiddenAreas { get; set; }

        /// <summary>
        /// An event emitted when the model of this editor has changed (e.g. `editor.setModel()`).
        /// </summary>
        public IEvent<IModelChangedEvent> OnDidChangeModel { get; set; }

        /// <summary>
        /// An event emitted when the content of the current model has changed.
        /// </summary>
        public IEvent<IModelContentChangedEvent> OnDidChangeModelContent { get; set; }

        /// <summary>
        /// An event emitted when the decorations of the current model have changed.
        /// </summary>
        public IEvent<IModelDecorationsChangedEvent> OnDidChangeModelDecorations { get; set; }

        /// <summary>
        /// An event emitted when the language of the current model has changed.
        /// </summary>
        public IEvent<IModelLanguageChangedEvent> OnDidChangeModelLanguage { get; set; }

        /// <summary>
        /// An event emitted when the language configuration of the current model has changed.
        /// </summary>
        public IEvent<IModelLanguageConfigurationChangedEvent> OnDidChangeModelLanguageConfiguration { get; set; }

        /// <summary>
        /// An event emitted when the options of the current model has changed.
        /// </summary>
        public IEvent<IModelOptionsChangedEvent> OnDidChangeModelOptions { get; set; }

        /// <summary>
        /// An event emitted after composition has ended.
        /// </summary>
        public IEvent<object> OnDidCompositionEnd { get; set; }

        /// <summary>
        /// An event emitted after composition has started.
        /// </summary>
        public IEvent<object> OnDidCompositionStart { get; set; }

        /// <summary>
        /// An event emitted when the content width or content height in the editor has changed.
        /// </summary>
        public IEvent<IContentSizeChangedEvent> OnDidContentSizeChange { get; set; }

        /// <summary>
        /// An event emitted when the text inside this editor gained focus (i.e. cursor starts blinking).
        /// </summary>
        public IEvent<object> OnDidFocusEditorText { get; set; }

        /// <summary>
        /// An event emitted when the text inside this editor or an editor widget gained focus.
        /// </summary>
        public IEvent<object> OnDidFocusEditorWidget { get; set; }

        /// <summary>
        /// An event emitted when the layout of the editor has changed.
        /// </summary>
        public IEvent<EditorLayoutInfo> OnDidLayoutChange { get; set; }

        /// <summary>
        /// An event emitted when users paste text in the editor.
        /// </summary>
        public IEvent<IPasteEvent> OnDidPaste { get; set; }

        /// <summary>
        /// An event emitted when the scroll in the editor has changed.
        /// </summary>
        public IEvent<IScrollEvent> OnDidScrollChange { get; set; }

        /// <summary>
        /// Fires after the editor completes the operation it fired `onBeginUpdate` for.
        /// </summary>
        public IEvent<object> OnEndUpdate { get; set; }

        /// <summary>
        /// An event emitted on a "keydown".
        /// </summary>
        public IEvent<IKeyboardEvent> OnKeyDown { get; set; }

        /// <summary>
        /// An event emitted on a "keyup".
        /// </summary>
        public IEvent<IKeyboardEvent> OnKeyUp { get; set; }

        /// <summary>
        /// An event emitted on a "mousedown".
        /// </summary>
        public IEvent<IEditorMouseEvent> OnMouseDown { get; set; }

        /// <summary>
        /// An event emitted on a "mouseleave".
        /// </summary>
        public IEvent<IPartialEditorMouseEvent> OnMouseLeave { get; set; }

        /// <summary>
        /// An event emitted on a "mousemove".
        /// </summary>
        public IEvent<IEditorMouseEvent> OnMouseMove { get; set; }

        /// <summary>
        /// An event emitted on a "mouseup".
        /// </summary>
        public IEvent<IEditorMouseEvent> OnMouseUp { get; set; }

        /// <summary>
        /// An event emitted when the model of this editor is about to change (e.g. from `editor.setModel()`).
        /// </summary>
        public IEvent<IModelChangedEvent> OnWillChangeModel { get; set; }

        /// <summary>
        /// Add a content widget. Widgets must have unique ids, otherwise they will be overwritten.
        /// </summary>
        public void AddContentWidget(IContentWidget widget) => throw new NotImplementedException();

        /// <summary>
        /// Add a glyph margin widget. Widgets must have unique ids, otherwise they will be overwritten.
        /// </summary>
        public void AddGlyphMarginWidget(IGlyphMarginWidget widget) => throw new NotImplementedException();

        /// <summary>
        /// Add an overlay widget. Widgets must have unique ids, otherwise they will be overwritten.
        /// </summary>
        public void AddOverlayWidget(IOverlayWidget widget) => throw new NotImplementedException();

        /// <summary>
        /// Apply the same font settings as the editor to `target`.
        /// </summary>
        public void ApplyFontInfo(object target) => throw new NotImplementedException();

        /// <summary>
        /// Change the view zones. View zones are lost when a new model is attached to the editor.
        /// </summary>
        public void ChangeViewZones(object callback) => throw new NotImplementedException();

        /// <summary>
        /// All decorations added through this call will get the ownerId of this editor.
        /// </summary>
        /// <returns>An array of results.</returns>
        public string[] DeltaDecorations(string[] oldDecorations, IModelDeltaDecoration[] newDecorations) => throw new NotImplementedException();

        /// <summary>
        /// Execute a command on the editor.
        /// The edits will land on the undo-redo stack, but no "undo stop" will be pushed.
        /// </summary>
        /// <param name="source">The source of the call.</param>
        /// <param name="command">The command to execute</param>
        public void ExecuteCommand(string source, ICommand command) => throw new NotImplementedException();

        /// <summary>
        /// Execute multiple (concomitant) commands on the editor.
        /// </summary>
        /// <param name="source">The source of the call.</param>
        public void ExecuteCommands(string source, ICommand[] commands) => throw new NotImplementedException();

        /// <summary>
        /// Execute edits on the editor.
        /// The edits will land on the undo-redo stack, but no "undo stop" will be pushed.
        /// </summary>
        /// <param name="source">The source of the call.</param>
        /// <param name="edits">The edits to execute.</param>
        /// <param name="endCursorState">Cursor state after the edits were applied.</param>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool ExecuteEdits(string source, IIdentifiedSingleEditOperation[] edits, object? endCursorState) => throw new NotImplementedException();

        /// <summary>
        /// Get an action that is a contribution to this editor.
        /// </summary>
        public IEditorAction GetAction(string id) => throw new NotImplementedException();

        /// <summary>
        /// Get the vertical position (top offset) for the line's bottom w.r.t. to the first line.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetBottomForLineNumber(double lineNumber) => throw new NotImplementedException();

        /// <summary>
        /// Returns the editor's container dom node
        /// </summary>
        /// <returns>A HTMLElement instance.</returns>
        public object GetContainerDomNode() => throw new NotImplementedException();

        /// <summary>
        /// Get the height of the editor's content.
        /// This is information that is "erased" when computing `scrollHeight = Math.max(contentHeight, height)`
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetContentHeight() => throw new NotImplementedException();

        /// <summary>
        /// Get the width of the editor's content.
        /// This is information that is "erased" when computing `scrollWidth = Math.max(contentWidth, width)`
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetContentWidth() => throw new NotImplementedException();

        /// <summary>
        /// Get a contribution of this editor.
        /// </summary>
        public T GetContribution<T>(string id) => throw new NotImplementedException();

        /// <summary>
        /// Get all the decorations for a range (filtering out decorations from other editors).
        /// </summary>
        public IModelDecoration[] GetDecorationsInRange(Range range) => throw new NotImplementedException();

        /// <summary>
        /// Returns the editor's dom node
        /// </summary>
        public object GetDomNode() => throw new NotImplementedException();

        /// <summary>
        /// Get the layout info for the editor.
        /// </summary>
        /// <returns>A EditorLayoutInfo instance.</returns>
        public EditorLayoutInfo GetLayoutInfo() => throw new NotImplementedException();

        /// <summary>
        /// Get all the decorations on a line (filtering out decorations from other editors).
        /// </summary>
        public IModelDecoration[] GetLineDecorations(double lineNumber) => throw new NotImplementedException();

        /// <summary>
        /// Type the getModel() of IEditor.
        /// </summary>
        public ITextModel GetModel() => throw new NotImplementedException();

        /// <summary>
        /// Get the horizontal position (left offset) for the column w.r.t to the beginning of the line.
        /// This method works only if the line `lineNumber` is currently rendered (in the editor's viewport).
        /// Use this method with caution.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetOffsetForColumn(double lineNumber, double column) => throw new NotImplementedException();

        /// <summary>
        /// Gets a specific editor option.
        /// </summary>
        /// <returns>A FindComputedEditorOptionValueById instance.</returns>
        public FindComputedEditorOptionValueById<T> GetOption<T>(T id) => throw new NotImplementedException();

        /// <summary>
        /// Gets all the editor computed options.
        /// </summary>
        /// <returns>A IComputedEditorOptions instance.</returns>
        public IComputedEditorOptions GetOptions() => throw new NotImplementedException();

        /// <summary>
        /// Returns the editor's configuration (without any validation or defaults).
        /// </summary>
        /// <returns>A IEditorOptions instance.</returns>
        public IEditorOptions GetRawOptions() => throw new NotImplementedException();

        /// <summary>
        /// Get the visible position for `position`.
        /// The result position takes scrolling into account and is relative to the top left corner of the editor.
        /// Explanation 1: the results of this method will change for the same `position` if the user scrolls the editor.
        /// Explanation 2: the results of this method will not change if the container of the editor gets repositioned.
        /// Warning: the results of this method are inaccurate for positions that are outside the current editor viewport.
        /// </summary>
        public object GetScrolledVisiblePosition(IPosition position) => throw new NotImplementedException();

        /// <summary>
        /// Get the scrollHeight of the editor's viewport.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetScrollHeight() => throw new NotImplementedException();

        /// <summary>
        /// Get the scrollLeft of the editor's viewport.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetScrollLeft() => throw new NotImplementedException();

        /// <summary>
        /// Get the scrollTop of the editor's viewport.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetScrollTop() => throw new NotImplementedException();

        /// <summary>
        /// Get the scrollWidth of the editor's viewport.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetScrollWidth() => throw new NotImplementedException();

        /// <summary>
        /// Get the hit test target at coordinates `clientX` and `clientY`.
        /// The coordinates are relative to the top-left of the viewport.
        /// </summary>
        public IMouseTarget GetTargetAtClientPoint(double clientX, double clientY) => throw new NotImplementedException();

        /// <summary>
        /// Get the vertical position (top offset) for the line's top w.r.t. to the first line.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetTopForLineNumber(double lineNumber, bool? includeViewZones) => throw new NotImplementedException();

        /// <summary>
        /// Get the vertical position (top offset) for the position w.r.t. to the first line.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetTopForPosition(double lineNumber, double column) => throw new NotImplementedException();

        /// <summary>
        /// Get value of the current model attached to this editor.
        /// </summary>
        /// <returns>A string value.</returns>
        public string GetValue(object? options) => throw new NotImplementedException();

        /// <summary>
        /// Returns the ranges that are currently visible.
        /// Does not account for horizontal scrolling.
        /// </summary>
        /// <returns>An array of results.</returns>
        public Range[] GetVisibleRanges() => throw new NotImplementedException();

        /// <summary>
        /// Is called when the model has been set, view state was restored and options are updated.
        /// This is the best place to compute data for the viewport (such as tokens).
        /// </summary>
        public void HandleInitialized() => throw new NotImplementedException();

        /// <summary>
        /// Check if the editor is currently scrolling towards a different scroll position.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool HasPendingScrollAnimation() => throw new NotImplementedException();

        /// <summary>
        /// Returns true if the text inside this editor or an editor widget has focus.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool HasWidgetFocus() => throw new NotImplementedException();

        /// <summary>
        /// Layout/Reposition a content widget. This is a ping to the editor to call widget.getPosition()
        /// and update appropriately.
        /// </summary>
        public void LayoutContentWidget(IContentWidget widget) => throw new NotImplementedException();

        /// <summary>
        /// Layout/Reposition a glyph margin widget. This is a ping to the editor to call widget.getPosition()
        /// and update appropriately.
        /// </summary>
        public void LayoutGlyphMarginWidget(IGlyphMarginWidget widget) => throw new NotImplementedException();

        /// <summary>
        /// Layout/Reposition an overlay widget. This is a ping to the editor to call widget.getPosition()
        /// and update appropriately.
        /// </summary>
        public void LayoutOverlayWidget(IOverlayWidget widget) => throw new NotImplementedException();

        /// <summary>
        /// Remove the "undo stop" in the undo-redo stack.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool PopUndoStop() => throw new NotImplementedException();

        /// <summary>
        /// Create an "undo stop" in the undo-redo stack.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool PushUndoStop() => throw new NotImplementedException();

        /// <summary>
        /// Remove a content widget.
        /// </summary>
        public void RemoveContentWidget(IContentWidget widget) => throw new NotImplementedException();

        /// <summary>
        /// Remove previously added decorations.
        /// </summary>
        public void RemoveDecorations(string[] decorationIds) => throw new NotImplementedException();

        /// <summary>
        /// Remove a glyph margin widget.
        /// </summary>
        public void RemoveGlyphMarginWidget(IGlyphMarginWidget widget) => throw new NotImplementedException();

        /// <summary>
        /// Remove an overlay widget.
        /// </summary>
        public void RemoveOverlayWidget(IOverlayWidget widget) => throw new NotImplementedException();

        /// <summary>
        /// Force an editor render now.
        /// </summary>
        public void Render(bool? forceRedraw) => throw new NotImplementedException();

        /// <summary>
        /// Restores the view state of the editor from a serializable object generated by `saveViewState`.
        /// </summary>
        public void RestoreViewState(ICodeEditorViewState state) => throw new NotImplementedException();

        /// <summary>
        /// Saves current view state of the editor in a serializable object.
        /// </summary>
        public ICodeEditorViewState SaveViewState() => throw new NotImplementedException();

        public void SetBanner(object bannerDomNode, double height) => throw new NotImplementedException();

        /// <summary>
        /// Sets the current model attached to this editor.
        /// If the previous model was created by the editor via the value key in the options
        /// literal object, it will be destroyed. Otherwise, if the previous model was set
        /// via setModel, or the model key in the options literal object, the previous model
        /// will not be destroyed.
        /// It is safe to call setModel(null) to simply detach the current model from the editor.
        /// </summary>
        public void SetModel(ITextModel model) => throw new NotImplementedException();

        /// <summary>
        /// Change the scrollLeft of the editor's viewport.
        /// </summary>
        public void SetScrollLeft(double newScrollLeft, ScrollType? scrollType) => throw new NotImplementedException();

        /// <summary>
        /// Change the scroll position of the editor's viewport.
        /// </summary>
        public void SetScrollPosition(INewScrollPosition position, ScrollType? scrollType) => throw new NotImplementedException();

        /// <summary>
        /// Change the scrollTop of the editor's viewport.
        /// </summary>
        public void SetScrollTop(double newScrollTop, ScrollType? scrollType) => throw new NotImplementedException();

        /// <summary>
        /// Set the value of the current model attached to this editor.
        /// </summary>
        public void SetValue(string newValue) => throw new NotImplementedException();

        /// <summary>
        /// Write the screen reader content to be the current selection
        /// </summary>
        public void WriteScreenReaderContent(string reason) => throw new NotImplementedException();

    }
}
