// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <summary>
    /// Represents an object that can handle editor open operations (e.g. when "go to definition" is called
    /// with a resource other than the current model).
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICodeEditorOpener.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class CodeEditorOpener : ICodeEditorOpener
    {
        /// <summary>
        /// Callback that is invoked when a resource other than the current model should be opened (e.g. when "go to definition" is called).
        /// The callback should return `true` if the request was handled and `false` otherwise.
        /// </summary>
        /// <param name="source">The code editor instance that initiated the request.</param>
        /// <param name="resource">The Uri of the resource that should be opened.</param>
        /// <param name="selectionOrPosition">An optional position or selection inside the model corresponding to `resource` that can be used to set the cursor.</param>
        public object OpenCodeEditor(ICodeEditor source, Uri resource, object? selectionOrPosition) => throw new NotImplementedException();

    }
}
