// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IColorizerElementOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ColorizerElementOptions : IColorizerElementOptions
    {
        public string? MimeType { get; set; }

        public string? Theme { get; set; }

    }
}
