// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IColorizerOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ColorizerOptions : IColorizerOptions
    {
        public double? TabSize { get; set; }

    }
}
