// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICommandMetadata.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class CommandMetadata : ICommandMetadata
    {
        public object Description { get; set; }

    }
}
