// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICommandHandler.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class CommandHandler : ICommandHandler
    {
        public void Invoke(params object[] args) => throw new NotImplementedException();

    }
}
