// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <summary>
    /// A command that modifies text / cursor state on a model.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICommand.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class Command : ICommand
    {
        /// <summary>
        /// Compute the cursor state after the edit operations were applied.
        /// </summary>
        /// <param name="model">The model the command has executed on.</param>
        /// <param name="helper">A helper to get inverse edit operations and to get previously tracked selections.</param>
        /// <returns>A Selection instance.</returns>
        public Selection ComputeCursorState(ITextModel model, ICursorStateComputerData helper) => throw new NotImplementedException();

        /// <summary>
        /// Get the edit operations needed to execute this command.
        /// </summary>
        /// <param name="model">The model the command will execute on.</param>
        /// <param name="builder">A helper to collect the needed edit operations and to track selections.</param>
        public void GetEditOperations(ITextModel model, IEditOperationBuilder builder) => throw new NotImplementedException();

    }
}
