// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IContentSizeChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ContentSizeChangedEvent : IContentSizeChangedEvent
    {
        public double ContentHeight { get; set; }

        public bool ContentHeightChanged { get; set; }

        public double ContentWidth { get; set; }

        public bool ContentWidthChanged { get; set; }

    }
}
