// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// A positioning preference for rendering content widgets.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/editor.ContentWidgetPositionPreference.html">Monaco API</see> for more details.
    /// </remarks>
    public enum ContentWidgetPositionPreference
    {
        /// <summary>
        /// Place the content widget above a position
        /// </summary>
        ABOVE = 1,
        /// <summary>
        /// Place the content widget below a position
        /// </summary>
        BELOW = 2,
        /// <summary>
        /// Place the content widget exactly at a position
        /// </summary>
        EXACT = 0
    }
}
