// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <summary>
    /// A helper for computing cursor state after a command.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICursorStateComputerData.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class CursorStateComputerData : ICursorStateComputerData
    {
        /// <summary>
        /// Get the inverse edit operations of the added edit operations.
        /// </summary>
        /// <returns>An array of results.</returns>
        public IValidEditOperation[] GetInverseEditOperations() => throw new NotImplementedException();

        /// <summary>
        /// Get a previously tracked selection.
        /// </summary>
        /// <param name="id">The unique identifier returned by `trackSelection`.</param>
        /// <returns>A Selection instance.</returns>
        public Selection GetTrackedSelection(string id) => throw new NotImplementedException();

    }
}
