// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <summary>
    /// An event describing that the cursor position has changed.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICursorPositionChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class CursorPositionChangedEvent : ICursorPositionChangedEvent
    {
        /// <summary>
        /// Primary cursor's position.
        /// </summary>
        public Position Position { get; set; }

        /// <summary>
        /// Reason.
        /// </summary>
        public CursorChangeReason Reason { get; set; }

        /// <summary>
        /// Secondary cursors' position.
        /// </summary>
        public Position[] SecondaryPositions { get; set; }

        /// <summary>
        /// Source of the call that caused the event.
        /// </summary>
        public string Source { get; set; }

    }
}
