// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for the diff editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IDiffEditorOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class DiffEditorOptions : IDiffEditorOptions
    {
    }
}
