// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IDiffEditorViewModel.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class DiffEditorViewModel : IDiffEditorViewModel
    {
        public IDiffEditorModel Model { get; set; }

        /// <returns>A task representing the asynchronous operation.</returns>
        public object WaitForDiff() => throw new NotImplementedException();

    }
}
