// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// A model for the diff editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IDiffEditorModel.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class DiffEditorModel : IDiffEditorModel
    {
        /// <summary>
        /// Modified model.
        /// </summary>
        public ITextModel Modified { get; set; }

        /// <summary>
        /// Original model.
        /// </summary>
        public ITextModel Original { get; set; }

    }
}
