// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <summary>
    /// A rich diff editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IDiffEditor.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class DiffEditor : IDiffEditor
    {
        /// <summary>
        /// An event emitted when the diff model is changed (i.e. the diff editor shows new content).
        /// </summary>
        public IEvent<object> OnDidChangeModel { get; set; }

        /// <summary>
        /// An event emitted when the diff information computed by this diff editor has been updated.
        /// </summary>
        public IEvent<object> OnDidUpdateDiff { get; set; }

        public void AccessibleDiffViewerNext() => throw new NotImplementedException();

        public void AccessibleDiffViewerPrev() => throw new NotImplementedException();

        /// <returns>A IDiffEditorViewModel instance.</returns>
        public IDiffEditorViewModel CreateViewModel(IDiffEditorModel model) => throw new NotImplementedException();

        /// <returns>A HTMLElement instance.</returns>
        public object GetContainerDomNode() => throw new NotImplementedException();

        /// <summary>
        /// Get the computed diff information.
        /// </summary>
        public ILineChange[] GetLineChanges() => throw new NotImplementedException();

        /// <summary>
        /// Type the getModel() of IEditor.
        /// </summary>
        public IDiffEditorModel GetModel() => throw new NotImplementedException();

        /// <summary>
        /// Get the `modified` editor.
        /// </summary>
        /// <returns>A ICodeEditor instance.</returns>
        public ICodeEditor GetModifiedEditor() => throw new NotImplementedException();

        /// <summary>
        /// Get the `original` editor.
        /// </summary>
        /// <returns>A ICodeEditor instance.</returns>
        public ICodeEditor GetOriginalEditor() => throw new NotImplementedException();

        /// <summary>
        /// Jumps to the next or previous diff.
        /// </summary>
        public void GoToDiff(string target) => throw new NotImplementedException();

        public void HandleInitialized() => throw new NotImplementedException();

        /// <summary>
        /// Restores the view state of the editor from a serializable object generated by `saveViewState`.
        /// </summary>
        public void RestoreViewState(IDiffEditorViewState state) => throw new NotImplementedException();

        /// <summary>
        /// Scrolls to the first diff.
        /// (Waits until the diff computation finished.)
        /// </summary>
        public object RevealFirstDiff() => throw new NotImplementedException();

        /// <summary>
        /// Saves current view state of the editor in a serializable object.
        /// </summary>
        public IDiffEditorViewState SaveViewState() => throw new NotImplementedException();

        /// <summary>
        /// Sets the current model attached to this editor.
        /// If the previous model was created by the editor via the value key in the options
        /// literal object, it will be destroyed. Otherwise, if the previous model was set
        /// via setModel, or the model key in the options literal object, the previous model
        /// will not be destroyed.
        /// It is safe to call setModel(null) to simply detach the current model from the editor.
        /// </summary>
        public void SetModel(object model) => throw new NotImplementedException();

        /// <summary>
        /// Update the editor's options after the editor has been created.
        /// </summary>
        public void UpdateOptions(IDiffEditorOptions newOptions) => throw new NotImplementedException();

    }
}
