// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IDiffEditorConstructionOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class DiffEditorConstructionOptions : IDiffEditorConstructionOptions
    {
        /// <summary>
        /// Aria label for modified editor.
        /// </summary>
        public string? ModifiedAriaLabel { get; set; }

        /// <summary>
        /// Aria label for original editor.
        /// </summary>
        public string? OriginalAriaLabel { get; set; }

        /// <summary>
        /// Place overflow widgets inside an external DOM node.
        /// Defaults to an internal DOM node.
        /// </summary>
        public object? OverflowWidgetsDomNode { get; set; }

    }
}
