// <auto-generated />
#nullable enable
using Monaco.Editor;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// The initial editor dimension (to avoid measuring the container).
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IDimension.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class Dimension : IDimension
    {
        public uint Height { get; set; }

        public uint Width { get; set; }
    }
}
