// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for editor drop into behavior
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IDropIntoEditorOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class DropIntoEditorOptions : IDropIntoEditorOptions
    {
        /// <summary>
        /// Enable dropping into editor.
        /// Defaults to true.
        /// </summary>
        public bool? Enabled { get; set; }

        /// <summary>
        /// Controls if a widget is shown after a drop.
        /// Defaults to 'afterDrop'.
        /// </summary>
        public string? ShowDropSelector { get; set; }

    }
}
