// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorAction.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class EditorAction : IEditorAction
    {
        public string Alias { get; set; }

        public string Id { get; set; }

        public string Label { get; set; }

        public ICommandMetadata Metadata { get; set; }

        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool IsSupported() => throw new NotImplementedException();

        /// <returns>A task representing the asynchronous operation.</returns>
        public object Run(object? args) => throw new NotImplementedException();

    }
}
