// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for auto indentation in the editor
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/editor.EditorAutoIndentStrategy.html">Monaco API</see> for more details.
    /// </remarks>
    public enum EditorAutoIndentStrategy
    {
        Advanced = 3,
        Brackets = 2,
        Full = 4,
        Keep = 1,
        None = 0
    }
}
