// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for editor padding
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorPaddingOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class EditorPaddingOptions : IEditorPaddingOptions
    {
        /// <summary>
        /// Spacing between bottom edge of editor and last line.
        /// </summary>
        public double? Bottom { get; set; }

        /// <summary>
        /// Spacing between top edge of editor and first line.
        /// </summary>
        public double? Top { get; set; }

    }
}
