// <auto-generated />
#nullable enable
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for auto closing quotes and brackets
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/types/editor.EditorAutoClosingStrategy.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(JsonStringEnumConverter<EditorAutoClosingStrategy>))]
    public enum EditorAutoClosingStrategy
    {
        [JsonStringEnumMemberName("always")]
        [EnumMember(Value = "always")]
        Always,
        [JsonStringEnumMemberName("languageDefined")]
        [EnumMember(Value = "languageDefined")]
        LanguageDefined,
        [JsonStringEnumMemberName("beforeWhitespace")]
        [EnumMember(Value = "beforeWhitespace")]
        BeforeWhitespace,
        [JsonStringEnumMemberName("never")]
        [EnumMember(Value = "never")]
        Never
    }
}
