// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// The internal layout details of the editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.EditorLayoutInfo.html">Monaco API</see> for more details.
    /// </remarks>
    public interface EditorLayoutInfo
    {
        /// <summary>
        /// Left position for the content (actual text)
        /// </summary>
        double ContentLeft { get; }

        /// <summary>
        /// The width of the content (actual text)
        /// </summary>
        double ContentWidth { get; }

        /// <summary>
        /// Left position for the line decorations.
        /// </summary>
        double DecorationsLeft { get; }

        /// <summary>
        /// The width of the line decorations.
        /// </summary>
        double DecorationsWidth { get; }

        /// <summary>
        /// The number of decoration lanes to render in the glyph margin.
        /// </summary>
        double GlyphMarginDecorationLaneCount { get; }

        /// <summary>
        /// Left position for the glyph margin.
        /// </summary>
        double GlyphMarginLeft { get; }

        /// <summary>
        /// The width of the glyph margin.
        /// </summary>
        double GlyphMarginWidth { get; }

        /// <summary>
        /// Full editor height.
        /// </summary>
        double Height { get; }

        /// <summary>
        /// The height of the horizontal scrollbar.
        /// </summary>
        double HorizontalScrollbarHeight { get; }

        bool IsViewportWrapping { get; }

        bool IsWordWrapMinified { get; }

        /// <summary>
        /// Left position for the line numbers.
        /// </summary>
        double LineNumbersLeft { get; }

        /// <summary>
        /// The width of the line numbers.
        /// </summary>
        double LineNumbersWidth { get; }

        /// <summary>
        /// Layout information for the minimap
        /// </summary>
        EditorMinimapLayoutInfo Minimap { get; }

        /// <summary>
        /// The position of the overview ruler.
        /// </summary>
        OverviewRulerPosition OverviewRuler { get; }

        /// <summary>
        /// The width of the vertical scrollbar.
        /// </summary>
        double VerticalScrollbarWidth { get; }

        /// <summary>
        /// The number of columns (of typical characters) fitting on a viewport line.
        /// </summary>
        double ViewportColumn { get; }

        /// <summary>
        /// Full editor width.
        /// </summary>
        double Width { get; }

        double WrappingColumn { get; }

    }
}
