// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorOverrideServices.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class EditorOverrideServices : IEditorOverrideServices
    {
        public object this[string index] { get; set; }

    }
}
