// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorZoom.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class EditorZoom : IEditorZoom
    {
        public IEvent<double> OnDidChangeZoomLevel { get; set; }

        /// <returns>A numeric value.</returns>
        public double GetZoomLevel() => throw new NotImplementedException();

        public void SetZoomLevel(double zoomLevel) => throw new NotImplementedException();

    }
}
