// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Control the behavior and rendering of the code action lightbulb.
    ///
    /// Configuration options for editor lightbulb
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorLightbulbOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class EditorLightbulbOptions
    {
        /// <summary>
        /// Enable the lightbulb code action.
        /// Defaults to true.
        /// </summary>
        public bool? Enabled { get; set; }
    }

}
