// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for editor find widget
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorFindOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class EditorFindOptions : IEditorFindOptions
    {
        public bool? AddExtraSpaceOnTop { get; set; }

        /// <summary>
        /// Controls if Find in Selection flag is turned on in the editor.
        /// </summary>
        public string? AutoFindInSelection { get; set; }

        /// <summary>
        /// Controls whether the cursor should move to find matches while typing.
        /// </summary>
        public bool? CursorMoveOnType { get; set; }

        /// <summary>
        /// Controls whether the search result and diff result automatically restarts from the beginning (or the end) when no further matches can be found
        /// </summary>
        public bool? Loop { get; set; }

        /// <summary>
        /// Controls if we seed search string in the Find Widget with editor selection.
        /// </summary>
        public string? SeedSearchStringFromSelection { get; set; }

    }
}
