// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <summary>
    /// A mouse event originating from the editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorMouseEvent.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class EditorMouseEvent : IEditorMouseEvent
    {
        public IMouseEvent Event { get; set; }

        public IMouseTarget Target { get; set; }

    }
}
