// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// The internal layout details of the editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.EditorMinimapLayoutInfo.html">Monaco API</see> for more details.
    /// </remarks>
    public interface EditorMinimapLayoutInfo
    {
        double MinimapCanvasInnerHeight { get; }

        double MinimapCanvasInnerWidth { get; }

        double MinimapCanvasOuterHeight { get; }

        double MinimapCanvasOuterWidth { get; }

        bool MinimapHeightIsEditorHeight { get; }

        bool MinimapIsSampling { get; }

        double MinimapLeft { get; }

        double MinimapLineHeight { get; }

        double MinimapScale { get; }

        double MinimapWidth { get; }

        RenderMinimap RenderMinimap { get; }

    }
}
