// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/classes/editor.FindMatch.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class FindMatch
    {
        public void _findMatchBrand { get; set; }

        public string[] Matches { get; }

        public Range Range { get; }

    }
}
