// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/classes/editor.FontInfo.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class FontInfo : BareFontInfo
    {
        public void _editorStylingBrand { get; }

        public bool CanUseHalfwidthRightwardsArrow { get; }

        public bool IsMonospace { get; }

        public bool IsTrusted { get; }

        public double MaxDigitWidth { get; }

        public double MiddotWidth { get; }

        public double SpaceWidth { get; }

        public double TypicalFullwidthCharacterWidth { get; }

        public double TypicalHalfwidthCharacterWidth { get; }

        public double Version { get; }

        public double WsmiddotWidth { get; }

    }
}
