// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// A glyph margin widget renders in the editor glyph margin.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IGlyphMarginWidget.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class GlyphMarginWidget : IGlyphMarginWidget
    {
        /// <summary>
        /// Get the dom node of the glyph widget.
        /// </summary>
        /// <returns>A HTMLElement instance.</returns>
        public object GetDomNode() => throw new NotImplementedException();

        /// <summary>
        /// Get a unique identifier of the glyph widget.
        /// </summary>
        /// <returns>A string value.</returns>
        public string GetId() => throw new NotImplementedException();

        /// <summary>
        /// Get the placement of the glyph widget.
        /// </summary>
        /// <returns>A IGlyphMarginWidgetPosition instance.</returns>
        public IGlyphMarginWidgetPosition GetPosition() => throw new NotImplementedException();

    }
}
