// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IGlyphMarginLanesModel.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class GlyphMarginLanesModel : IGlyphMarginLanesModel
    {
        /// <summary>
        /// The number of lanes that should be rendered in the editor.
        /// </summary>
        public double RequiredLanes { get; set; }

        /// <summary>
        /// Gets the lanes that should be rendered starting at a given line number.
        /// </summary>
        /// <returns>An array of results.</returns>
        public GlyphMarginLane[] GetLanesAtLine(double lineNumber) => throw new NotImplementedException();

        /// <summary>
        /// Registers that a lane should be visible at the Range in the model.
        /// </summary>
        /// <param name="persist">- if true, notes that the lane should always be visible, even on lines where there's no specific request for that lane.</param>
        public void Push(GlyphMarginLane lane, Range range, bool? persist) => throw new NotImplementedException();

        /// <summary>
        /// Resets the model and ensures it can contain at least `maxLine` lines.
        /// </summary>
        public void Reset(double maxLine) => throw new NotImplementedException();

    }
}
