// <auto-generated />
#nullable enable
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/types/editor.GoToLocationValues.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(JsonStringEnumConverter<GoToLocationValues>))]
    public enum GoToLocationValues
    {
        [JsonStringEnumMemberName("peek")]
        [EnumMember(Value = "peek")]
        Peek,
        [JsonStringEnumMemberName("gotoAndPeek")]
        [EnumMember(Value = "gotoAndPeek")]
        GotoAndPeek,
        [JsonStringEnumMemberName("goto")]
        [EnumMember(Value = "goto")]
        Goto
    }
}
