// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for go to location
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IGotoLocationOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class GoToLocationOptions
    {
        public string? AlternativeDeclarationCommand { get; set; }

        public string? AlternativeDefinitionCommand { get; set; }

        public string? AlternativeImplementationCommand { get; set; }

        public string? AlternativeReferenceCommand { get; set; }

        public string? AlternativeTypeDefinitionCommand { get; set; }

        public Multiple? Multiple { get; set; }

        public Multiple? MultipleDeclarations { get; set; }

        public Multiple? MultipleDefinitions { get; set; }

        public Multiple? MultipleImplementations { get; set; }

        public Multiple? MultipleReferences { get; set; }

        public Multiple? MultipleTypeDefinitions { get; set; }
    }

}
