// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A change computed by the diff editor, expressed in line numbers.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IChange.html">Monaco API</see> for more details.
    /// <para>
    /// Line numbers are 1-based, except that a side with no lines in the change reports 0
    /// for both its start and end - that is how a pure insertion or deletion is encoded.
    /// They are therefore signed rather than unsigned.
    /// </para>
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IChange, Change>))]
    public partial interface IChange
    {
        /// <summary>
        /// The 1-based line number where the change starts in the original document,
        /// or 0 when the change is a pure insertion.
        /// </summary>
        int OriginalStartLineNumber { get; }

        /// <summary>
        /// The 1-based line number where the change ends in the original document,
        /// or 0 when the change is a pure insertion.
        /// </summary>
        int OriginalEndLineNumber { get; }

        /// <summary>
        /// The 1-based line number where the change starts in the modified document,
        /// or 0 when the change is a pure deletion.
        /// </summary>
        int ModifiedStartLineNumber { get; }

        /// <summary>
        /// The 1-based line number where the change ends in the modified document,
        /// or 0 when the change is a pure deletion.
        /// </summary>
        int ModifiedEndLineNumber { get; }
    }
}
