// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A character level change.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICharChange.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ICharChange, CharChange>))]
    public interface ICharChange : IChange
    {
        double ModifiedEndColumn { get; }

        double ModifiedStartColumn { get; }

        double OriginalEndColumn { get; }

        double OriginalStartColumn { get; }

    }
}
