// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A (serializable) state of the code editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICodeEditorViewState.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ICodeEditorViewState, CodeEditorViewState>))]
    public interface ICodeEditorViewState
    {
        object ContributionsState { get; set; }

        ICursorState[] CursorState { get; set; }

        IViewState ViewState { get; set; }

    }
}
