// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IColorizerElementOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IColorizerElementOptions, ColorizerElementOptions>))]
    public interface IColorizerElementOptions : IColorizerOptions
    {
        string? MimeType { get; set; }

        string? Theme { get; set; }

    }
}
