// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// All computed editor options.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IComputedEditorOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IComputedEditorOptions, ComputedEditorOptions>))]
    public interface IComputedEditorOptions
    {
        /// <returns>A FindComputedEditorOptionValueById instance.</returns>
        FindComputedEditorOptionValueById<T> Get<T>(T id);

    }
}
