// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICommandHandler.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ICommandHandler, CommandHandler>))]
    public interface ICommandHandler
    {
        void Invoke(params object[] args);

    }
}
