// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A position for rendering content widgets.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IContentWidgetPosition.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IContentWidgetPosition, ContentWidgetPosition>))]
    public interface IContentWidgetPosition
    {
        /// <summary>
        /// Desired position which serves as an anchor for placing the content widget.
        /// The widget will be placed above, at, or below the specified position, based on the
        /// provided preference. The widget will always touch this position.
        ///
        /// Given sufficient horizontal space, the widget will be placed to the right of the
        /// passed in position. This can be tweaked by providing a `secondaryPosition`.
        /// </summary>
        IPosition Position { get; set; }

        /// <summary>
        /// Placement preference when multiple view positions refer to the same (model) position.
        /// This plays a role when injected text is involved.
        /// </summary>
        PositionAffinity? PositionAffinity { get; set; }

        /// <summary>
        /// Placement preference for position, in order of preference.
        /// </summary>
        ContentWidgetPositionPreference[] Preference { get; set; }

        /// <summary>
        /// Optionally, a secondary position can be provided to further define the placing of
        /// the content widget. The secondary position must have the same line number as the
        /// primary position. If possible, the widget will be placed such that it also touches
        /// the secondary position.
        /// </summary>
        IPosition? SecondaryPosition { get; set; }

    }
}
