// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A content widget renders inline with the text and can be easily placed 'near' an editor position.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IContentWidget.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IContentWidget, ContentWidget>))]
    public interface IContentWidget
    {
        /// <summary>
        /// Render this content widget in a location where it could overflow the editor's view dom node.
        /// </summary>
        bool? AllowEditorOverflow { get; set; }

        /// <summary>
        /// Call preventDefault() on mousedown events that target the content widget.
        /// </summary>
        bool? SuppressMouseDown { get; set; }

        /// <summary>
        /// Optional function that is invoked after rendering the content
        /// widget. Is being invoked with the selected position preference
        /// or `null` if not rendered.
        /// </summary>
        void AfterRender(ContentWidgetPositionPreference position);

        /// <summary>
        /// Optional function that is invoked before rendering
        /// the content widget. If a dimension is returned the editor will
        /// attempt to use it.
        /// </summary>
        IDimension BeforeRender();

        /// <summary>
        /// Get the dom node of the content widget.
        /// </summary>
        /// <returns>A HTMLElement instance.</returns>
        object GetDomNode();

        /// <summary>
        /// Get a unique identifier of the content widget.
        /// </summary>
        /// <returns>A string value.</returns>
        string GetId();

        /// <summary>
        /// Get the placement of the content widget.
        /// If null is returned, the content widget will be placed off screen.
        /// </summary>
        IContentWidgetPosition GetPosition();

    }
}
