// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// An event describing that the cursor position has changed.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICursorPositionChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ICursorPositionChangedEvent, CursorPositionChangedEvent>))]
    public interface ICursorPositionChangedEvent
    {
        /// <summary>
        /// Primary cursor's position.
        /// </summary>
        Position Position { get; }

        /// <summary>
        /// Reason.
        /// </summary>
        CursorChangeReason Reason { get; }

        /// <summary>
        /// Secondary cursors' position.
        /// </summary>
        Position[] SecondaryPositions { get; }

        /// <summary>
        /// Source of the call that caused the event.
        /// </summary>
        string Source { get; }

    }
}
