// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A (serializable) state of the cursors.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICursorState.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ICursorState, CursorState>))]
    public interface ICursorState
    {
        bool InSelectionMode { get; set; }

        IPosition Position { get; set; }

        IPosition SelectionStart { get; set; }

    }
}
