// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A callback that can compute the cursor state after applying a series of edit operations.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICursorStateComputer.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ICursorStateComputer, CursorStateComputer>))]
    public interface ICursorStateComputer
    {
        /// <summary>
        /// A callback that can compute the resulting cursors state after some edit operations have been executed.
        /// </summary>
        Selection[] Invoke(IValidEditOperation[] inverseEditOperations);

    }
}
