// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// An event describing that the cursor selection has changed.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ICursorSelectionChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ICursorSelectionChangedEvent, CursorSelectionChangedEvent>))]
    public interface ICursorSelectionChangedEvent
    {
        /// <summary>
        /// The model version id.
        /// </summary>
        double ModelVersionId { get; }

        /// <summary>
        /// The model version id the that `oldSelections` refer to.
        /// </summary>
        double OldModelVersionId { get; }

        /// <summary>
        /// The old selections.
        /// </summary>
        Selection[] OldSelections { get; }

        /// <summary>
        /// Reason.
        /// </summary>
        CursorChangeReason Reason { get; }

        /// <summary>
        /// The secondary selections.
        /// </summary>
        Selection[] SecondarySelections { get; }

        /// <summary>
        /// The primary selection.
        /// </summary>
        Selection Selection { get; }

        /// <summary>
        /// Source of the call that caused the event.
        /// </summary>
        string Source { get; }

    }
}
