// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IDiffEditorBaseOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IDiffEditorBaseOptions, DiffEditorBaseOptions>))]
    public interface IDiffEditorBaseOptions
    {
        /// <summary>
        /// Whether the diff editor aria label should be verbose.
        /// </summary>
        bool? AccessibilityVerbose { get; set; }

        /// <summary>
        /// If set, the diff editor is optimized for small views.
        /// Defaults to `false`.
        /// </summary>
        bool? CompactMode { get; set; }

        /// <summary>
        /// Diff Algorithm
        /// </summary>
        string? DiffAlgorithm { get; set; }

        /// <summary>
        /// Should the diff editor enable code lens?
        /// Defaults to false.
        /// </summary>
        bool? DiffCodeLens { get; set; }

        /// <summary>
        /// Control the wrapping of the diff editor.
        /// </summary>
        string? DiffWordWrap { get; set; }

        /// <summary>
        /// Allow the user to resize the diff editor split view.
        /// Defaults to true.
        /// </summary>
        bool? EnableSplitViewResizing { get; set; }

        object? Experimental { get; set; }

        object? HideUnchangedRegions { get; set; }

        /// <summary>
        /// Compute the diff by ignoring leading/trailing whitespace
        /// Defaults to true.
        /// </summary>
        bool? IgnoreTrimWhitespace { get; set; }

        /// <summary>
        /// Is the diff editor inside another editor
        /// Defaults to false
        /// </summary>
        bool? IsInEmbeddedEditor { get; set; }

        /// <summary>
        /// Timeout in milliseconds after which diff computation is cancelled.
        /// Defaults to 5000.
        /// </summary>
        double? MaxComputationTime { get; set; }

        /// <summary>
        /// Maximum supported file size in MB.
        /// Defaults to 50.
        /// </summary>
        double? MaxFileSize { get; set; }

        /// <summary>
        /// If the diff editor should only show the difference review mode.
        /// </summary>
        bool? OnlyShowAccessibleDiffViewer { get; set; }

        /// <summary>
        /// Original model should be editable?
        /// Defaults to false.
        /// </summary>
        bool? OriginalEditable { get; set; }

        /// <summary>
        /// Indicates if the gutter menu should be rendered.
        /// </summary>
        bool? RenderGutterMenu { get; set; }

        /// <summary>
        /// Render +/- indicators for added/deleted changes.
        /// Defaults to true.
        /// </summary>
        bool? RenderIndicators { get; set; }

        /// <summary>
        /// Shows icons in the glyph margin to revert changes.
        /// Default to true.
        /// </summary>
        bool? RenderMarginRevertIcon { get; set; }

        /// <summary>
        /// Is the diff editor should render overview ruler
        /// Defaults to true
        /// </summary>
        bool? RenderOverviewRuler { get; set; }

        /// <summary>
        /// Render the differences in two side-by-side editors.
        /// Defaults to true.
        /// </summary>
        bool? RenderSideBySide { get; set; }

        /// <summary>
        /// When `renderSideBySide` is enabled, `useInlineViewWhenSpaceIsLimited` is set,
        /// and the diff editor has a width less than `renderSideBySideInlineBreakpoint`, the inline view is used.
        /// </summary>
        double? RenderSideBySideInlineBreakpoint { get; set; }

        /// <summary>
        /// The default ratio when rendering side-by-side editors.
        /// Must be a number between 0 and 1, min sizes apply.
        /// Defaults to 0.5
        /// </summary>
        double? SplitViewDefaultRatio { get; set; }

        /// <summary>
        /// When `renderSideBySide` is enabled, `useInlineViewWhenSpaceIsLimited` is set,
        /// and the diff editor has a width less than `renderSideBySideInlineBreakpoint`, the inline view is used.
        /// </summary>
        bool? UseInlineViewWhenSpaceIsLimited { get; set; }

    }
}
