// <auto-generated />
#nullable enable
using Monaco.Editor;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for the diff editor: the editor-level options of the
    /// underlying editors, plus the diff-specific options.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IDiffEditorOptions.html">Monaco API</see> for more details.
    /// <para>
    /// Nothing implements this union directly. <c>DiffCodeEditor</c> splits it in two: the
    /// editor-level half is carried by <see cref="CodeEditorBase.Options"/> and applied to
    /// the modified sub-editor, and the diff-specific half by
    /// <c>DiffCodeEditor.DiffOptions</c>, typed as <see cref="DiffEditorOptions"/>.
    /// </para>
    /// </remarks>
    public partial interface IDiffEditorOptions : IEditorOptions, IDiffEditorBaseOptions
    {
    }
}
