// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IDiffEditorViewModel.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IDiffEditorViewModel, DiffEditorViewModel>))]
    public interface IDiffEditorViewModel : IDisposable
    {
        IDiffEditorModel Model { get; }

        /// <returns>A task representing the asynchronous operation.</returns>
        object WaitForDiff();

    }
}
