// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// The diff-specific subset of the diff editor configuration.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IDiffEditorBaseOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IDiffEditorBaseOptions, DiffEditorOptions>))]
    public partial interface IDiffEditorBaseOptions
    {
        /// <summary>
        /// Whether the diff editor aria label should be verbose.
        /// </summary>
        bool? AccessibilityVerbose { get; set; }

        /// <summary>
        /// If set, the diff editor is optimized for small views.
        /// Defaults to false.
        /// </summary>
        bool? CompactMode { get; set; }

        /// <summary>
        /// Diff algorithm.
        /// Defaults to Advanced.
        /// </summary>
        DiffAlgorithm? DiffAlgorithm { get; set; }

        /// <summary>
        /// Should the diff editor enable code lens?
        /// Defaults to false.
        /// </summary>
        bool? DiffCodeLens { get; set; }

        /// <summary>
        /// Control the wrapping of the diff editor.
        /// </summary>
        DiffWordWrap? DiffWordWrap { get; set; }

        /// <summary>
        /// Allow the user to resize the diff editor split view.
        /// Defaults to true.
        /// </summary>
        bool? EnableSplitViewResizing { get; set; }

        /// <summary>
        /// Experimental options. May change between Monaco versions.
        /// </summary>
        DiffEditorExperimentalOptions? Experimental { get; set; }

        /// <summary>
        /// Collapse regions that contain no changes.
        /// </summary>
        DiffEditorHideUnchangedRegionsOptions? HideUnchangedRegions { get; set; }

        /// <summary>
        /// Compute the diff by ignoring leading/trailing whitespace.
        /// Defaults to true.
        /// </summary>
        bool? IgnoreTrimWhitespace { get; set; }

        /// <summary>
        /// Is the diff editor inside another editor.
        /// Defaults to false.
        /// </summary>
        bool? IsInEmbeddedEditor { get; set; }

        /// <summary>
        /// Timeout in milliseconds after which diff computation is cancelled.
        /// Defaults to 5000.
        /// </summary>
        uint? MaxComputationTime { get; set; }

        /// <summary>
        /// Maximum supported file size in MB.
        /// Defaults to 50.
        /// </summary>
        uint? MaxFileSize { get; set; }

        /// <summary>
        /// If the diff editor should only show the difference review mode.
        /// </summary>
        bool? OnlyShowAccessibleDiffViewer { get; set; }

        /// <summary>
        /// Original model should be editable?
        /// Defaults to false.
        /// </summary>
        bool? OriginalEditable { get; set; }

        /// <summary>
        /// Indicates if the gutter menu should be rendered.
        /// </summary>
        bool? RenderGutterMenu { get; set; }

        /// <summary>
        /// Render +/- indicators for added/deleted changes.
        /// Defaults to true.
        /// </summary>
        bool? RenderIndicators { get; set; }

        /// <summary>
        /// Shows icons in the glyph margin to revert changes.
        /// Defaults to true.
        /// </summary>
        bool? RenderMarginRevertIcon { get; set; }

        /// <summary>
        /// Should the diff editor render the overview ruler.
        /// Defaults to true.
        /// </summary>
        bool? RenderOverviewRuler { get; set; }

        /// <summary>
        /// Render the differences in two side-by-side editors.
        /// Defaults to true.
        /// </summary>
        bool? RenderSideBySide { get; set; }

        /// <summary>
        /// When <see cref="RenderSideBySide"/> is enabled and
        /// <see cref="UseInlineViewWhenSpaceIsLimited"/> is set, a diff editor narrower than this
        /// width (in pixels) renders the inline view instead.
        /// </summary>
        uint? RenderSideBySideInlineBreakpoint { get; set; }

        /// <summary>
        /// The default ratio when rendering side-by-side editors.
        /// Must be a number between 0 and 1; minimum sizes still apply.
        /// Defaults to 0.5.
        /// </summary>
        double? SplitViewDefaultRatio { get; set; }

        /// <summary>
        /// Switch to the inline view when the diff editor is narrower than
        /// <see cref="RenderSideBySideInlineBreakpoint"/>.
        /// </summary>
        bool? UseInlineViewWhenSpaceIsLimited { get; set; }
    }
}
