// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorZoom.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IEditorZoom, EditorZoom>))]
    public interface IEditorZoom
    {
        IEvent<double> OnDidChangeZoomLevel { get; set; }

        /// <returns>A numeric value.</returns>
        double GetZoomLevel();

        void SetZoomLevel(double zoomLevel);

    }
}
