// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for editor lightbulb
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorLightbulbOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IEditorLightbulbOptions, EditorLightbulbOptions>))]
    public interface IEditorLightbulbOptions
    {
        /// <summary>
        /// Enable the lightbulb code action.
        /// The three possible values are `off`, `on` and `onCode` and the default is `onCode`.
        /// `off` disables the code action menu.
        /// `on` shows the code action menu on code and on empty lines.
        /// `onCode` shows the code action menu on code only.
        /// </summary>
        ShowLightbulbIconMode? Enabled { get; set; }

    }
}
