// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor_editor_api.editor.IEditorFindOptions.html">monaco.editor.IEditorFindOptions</see>
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorFindOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class IEditorFindOptions
    {
        /// <summary>
        /// Controls if Find in Selection flag is turned on in the editor.
        /// </summary>
        public bool AutoFindInSelection { get; set; }
        /// <summary>
        /// Controls if we seed search string in the Find Widget with editor selection.
        /// </summary>
        public bool SeedSearchStringFromSelection { get; set; } //= true;
    }
}
