// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for the editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IEditorOptions, EditorOptions>))]
    public interface IEditorOptions
    {
        /// <summary>
        /// Accept suggestions on provider defined characters.
        /// Defaults to true.
        /// </summary>
        bool? AcceptSuggestionOnCommitCharacter { get; set; }

        /// <summary>
        /// Accept suggestions on ENTER.
        /// Defaults to 'on'.
        /// </summary>
        string? AcceptSuggestionOnEnter { get; set; }

        /// <summary>
        /// Controls the number of lines in the editor that can be read out by a screen reader
        /// </summary>
        double? AccessibilityPageSize { get; set; }

        /// <summary>
        /// Configure the editor's accessibility support.
        /// Defaults to 'auto'. It is best to leave this to 'auto'.
        /// </summary>
        string? AccessibilitySupport { get; set; }

        /// <summary>
        /// The aria label for the editor's textarea (when it is focused).
        /// </summary>
        string? AriaLabel { get; set; }

        /// <summary>
        /// Whether the aria-required attribute should be set on the editors textarea.
        /// </summary>
        bool? AriaRequired { get; set; }

        /// <summary>
        /// Options for auto closing brackets.
        /// Defaults to language defined behavior.
        /// </summary>
        EditorAutoClosingStrategy? AutoClosingBrackets { get; set; }

        /// <summary>
        /// Options for auto closing comments.
        /// Defaults to language defined behavior.
        /// </summary>
        EditorAutoClosingStrategy? AutoClosingComments { get; set; }

        /// <summary>
        /// Options for pressing backspace near quotes or bracket pairs.
        /// </summary>
        EditorAutoClosingEditStrategy? AutoClosingDelete { get; set; }

        /// <summary>
        /// Options for typing over closing quotes or brackets.
        /// </summary>
        EditorAutoClosingEditStrategy? AutoClosingOvertype { get; set; }

        /// <summary>
        /// Options for auto closing quotes.
        /// Defaults to language defined behavior.
        /// </summary>
        EditorAutoClosingStrategy? AutoClosingQuotes { get; set; }

        /// <summary>
        /// Controls whether the editor should automatically adjust the indentation when users type, paste, move or indent lines.
        /// Defaults to advanced.
        /// </summary>
        string? AutoIndent { get; set; }

        /// <summary>
        /// Enable that the editor will install a ResizeObserver to check if its container dom node size has changed.
        /// Defaults to false.
        /// </summary>
        bool? AutomaticLayout { get; set; }

        /// <summary>
        /// Options for auto surrounding.
        /// Defaults to always allowing auto surrounding.
        /// </summary>
        EditorAutoSurroundStrategy? AutoSurround { get; set; }

        /// <summary>
        /// Configures bracket pair colorization (disabled by default).
        /// </summary>
        IBracketPairColorizationOptions? BracketPairColorization { get; set; }

        /// <summary>
        /// Timeout for running code actions on save.
        /// </summary>
        double? CodeActionsOnSaveTimeout { get; set; }

        /// <summary>
        /// Show code lens
        /// Defaults to true.
        /// </summary>
        bool? CodeLens { get; set; }

        /// <summary>
        /// Code lens font family. Defaults to editor font family.
        /// </summary>
        string? CodeLensFontFamily { get; set; }

        /// <summary>
        /// Code lens font size. Default to 90% of the editor font size
        /// </summary>
        double? CodeLensFontSize { get; set; }

        /// <summary>
        /// Enable inline color decorators and color picker rendering.
        /// </summary>
        bool? ColorDecorators { get; set; }

        /// <summary>
        /// Controls what is the condition to spawn a color picker from a color dectorator
        /// </summary>
        string? ColorDecoratorsActivatedOn { get; set; }

        /// <summary>
        /// Controls the max number of color decorators that can be rendered in an editor at once.
        /// </summary>
        double? ColorDecoratorsLimit { get; set; }

        /// <summary>
        /// Enable that the selection with the mouse and keys is doing column selection.
        /// Defaults to false.
        /// </summary>
        bool? ColumnSelection { get; set; }

        /// <summary>
        /// Control the behaviour of comments in the editor.
        /// </summary>
        IEditorCommentsOptions? Comments { get; set; }

        /// <summary>
        /// Enable custom contextmenu.
        /// Defaults to true.
        /// </summary>
        bool? Contextmenu { get; set; }

        /// <summary>
        /// Syntax highlighting is copied.
        /// </summary>
        bool? CopyWithSyntaxHighlighting { get; set; }

        /// <summary>
        /// Control the cursor animation style, possible values are 'blink', 'smooth', 'phase', 'expand' and 'solid'.
        /// Defaults to 'blink'.
        /// </summary>
        string? CursorBlinking { get; set; }

        /// <summary>
        /// Enable smooth caret animation.
        /// Defaults to 'off'.
        /// </summary>
        string? CursorSmoothCaretAnimation { get; set; }

        /// <summary>
        /// Control the cursor style, either 'block' or 'line'.
        /// Defaults to 'line'.
        /// </summary>
        string? CursorStyle { get; set; }

        /// <summary>
        /// Controls the minimal number of visible leading and trailing lines surrounding the cursor.
        /// Defaults to 0.
        /// </summary>
        double? CursorSurroundingLines { get; set; }

        /// <summary>
        /// Controls when `cursorSurroundingLines` should be enforced
        /// Defaults to `default`, `cursorSurroundingLines` is not enforced when cursor position is changed
        /// by mouse.
        /// </summary>
        string? CursorSurroundingLinesStyle { get; set; }

        /// <summary>
        /// Control the width of the cursor when cursorStyle is set to 'line'
        /// </summary>
        double? CursorWidth { get; set; }

        /// <summary>
        /// Controls whether to use default color decorations or not using the default document color provider
        /// </summary>
        bool? DefaultColorDecorators { get; set; }

        /// <summary>
        /// Controls whether the definition link opens element in the peek widget.
        /// Defaults to false.
        /// </summary>
        bool? DefinitionLinkOpensInPeek { get; set; }

        /// <summary>
        /// Disable the use of `transform: translate3d(0px, 0px, 0px)` for the editor margin and lines layers.
        /// The usage of `transform: translate3d(0px, 0px, 0px)` acts as a hint for browsers to create an extra layer.
        /// Defaults to false.
        /// </summary>
        bool? DisableLayerHinting { get; set; }

        /// <summary>
        /// Disable the optimizations for monospace fonts.
        /// Defaults to false.
        /// </summary>
        bool? DisableMonospaceOptimizations { get; set; }

        /// <summary>
        /// Should the textarea used for input use the DOM `readonly` attribute.
        /// Defaults to false.
        /// </summary>
        bool? DomReadOnly { get; set; }

        /// <summary>
        /// Controls if the editor should allow to move selections via drag and drop.
        /// Defaults to false.
        /// </summary>
        bool? DragAndDrop { get; set; }

        /// <summary>
        /// Controls dropping into the editor from an external source.
        ///
        /// When enabled, this shows a preview of the drop location and triggers an `onDropIntoEditor` event.
        /// </summary>
        IDropIntoEditorOptions? DropIntoEditor { get; set; }

        /// <summary>
        /// Copying without a selection copies the current line.
        /// </summary>
        bool? EmptySelectionClipboard { get; set; }

        IInlineEditOptions? ExperimentalInlineEdit { get; set; }

        /// <summary>
        /// Enable experimental whitespace rendering.
        /// Defaults to 'svg'.
        /// </summary>
        string? ExperimentalWhitespaceRendering { get; set; }

        /// <summary>
        /// Class name to be added to the editor.
        /// </summary>
        string? ExtraEditorClassName { get; set; }

        /// <summary>
        /// FastScrolling mulitplier speed when pressing `Alt`
        /// Defaults to 5.
        /// </summary>
        double? FastScrollSensitivity { get; set; }

        /// <summary>
        /// Control the behavior of the find widget.
        /// </summary>
        IEditorFindOptions? Find { get; set; }

        /// <summary>
        /// Display overflow widgets as `fixed`.
        /// Defaults to `false`.
        /// </summary>
        bool? FixedOverflowWidgets { get; set; }

        /// <summary>
        /// Enable code folding.
        /// Defaults to true.
        /// </summary>
        bool? Folding { get; set; }

        /// <summary>
        /// Enable highlight for folded regions.
        /// Defaults to true.
        /// </summary>
        bool? FoldingHighlight { get; set; }

        /// <summary>
        /// Auto fold imports folding regions.
        /// Defaults to true.
        /// </summary>
        bool? FoldingImportsByDefault { get; set; }

        /// <summary>
        /// Maximum number of foldable regions.
        /// Defaults to 5000.
        /// </summary>
        double? FoldingMaximumRegions { get; set; }

        /// <summary>
        /// Selects the folding strategy. 'auto' uses the strategies contributed for the current document, 'indentation' uses the indentation based folding strategy.
        /// Defaults to 'auto'.
        /// </summary>
        string? FoldingStrategy { get; set; }

        /// <summary>
        /// The font family
        /// </summary>
        string? FontFamily { get; set; }

        /// <summary>
        /// Enable font ligatures.
        /// Defaults to false.
        /// </summary>
        object? FontLigatures { get; set; }

        /// <summary>
        /// The font size
        /// </summary>
        double? FontSize { get; set; }

        /// <summary>
        /// Enable font variations.
        /// Defaults to false.
        /// </summary>
        object? FontVariations { get; set; }

        /// <summary>
        /// The font weight
        /// </summary>
        string? FontWeight { get; set; }

        /// <summary>
        /// Enable format on paste.
        /// Defaults to false.
        /// </summary>
        bool? FormatOnPaste { get; set; }

        /// <summary>
        /// Enable format on type.
        /// Defaults to false.
        /// </summary>
        bool? FormatOnType { get; set; }

        /// <summary>
        /// Enable the rendering of the glyph margin.
        /// Defaults to true in vscode and to false in monaco-editor.
        /// </summary>
        bool? GlyphMargin { get; set; }

        IGotoLocationOptions? GotoLocation { get; set; }

        /// <summary>
        /// Controls the behavior of editor guides.
        /// </summary>
        IGuidesOptions? Guides { get; set; }

        /// <summary>
        /// Should the cursor be hidden in the overview ruler.
        /// Defaults to false.
        /// </summary>
        bool? HideCursorInOverviewRuler { get; set; }

        /// <summary>
        /// Configure the editor's hover.
        /// </summary>
        IEditorHoverOptions? Hover { get; set; }

        /// <summary>
        /// This editor is used inside a diff editor.
        /// </summary>
        bool? InDiffEditor { get; set; }

        /// <summary>
        /// Control the behavior and rendering of the inline hints.
        /// </summary>
        IEditorInlayHintsOptions? InlayHints { get; set; }

        /// <summary>
        /// Controls whether the accessibility hint should be provided to screen reader users when an inline completion is shown.
        /// </summary>
        bool? InlineCompletionsAccessibilityVerbose { get; set; }

        IInlineSuggestOptions? InlineSuggest { get; set; }

        /// <summary>
        /// The letter spacing
        /// </summary>
        double? LetterSpacing { get; set; }

        /// <summary>
        /// Control the behavior and rendering of the code action lightbulb.
        /// </summary>
        IEditorLightbulbOptions? Lightbulb { get; set; }

        /// <summary>
        /// The width reserved for line decorations (in px).
        /// Line decorations are placed between line numbers and the editor content.
        /// You can pass in a string in the format floating point followed by "ch". e.g. 1.3ch.
        /// Defaults to 10.
        /// </summary>
        object? LineDecorationsWidth { get; set; }

        /// <summary>
        /// The line height
        /// </summary>
        double? LineHeight { get; set; }

        /// <summary>
        /// Control the rendering of line numbers.
        /// If it is a function, it will be invoked when rendering a line number and the return value will be rendered.
        /// Otherwise, if it is a truthy, line numbers will be rendered normally (equivalent of using an identity function).
        /// Otherwise, line numbers will not be rendered.
        /// Defaults to `on`.
        /// </summary>
        LineNumbersType? LineNumbers { get; set; }

        /// <summary>
        /// Control the width of line numbers, by reserving horizontal space for rendering at least an amount of digits.
        /// Defaults to 5.
        /// </summary>
        double? LineNumbersMinChars { get; set; }

        /// <summary>
        /// Enable linked editing.
        /// Defaults to false.
        /// </summary>
        bool? LinkedEditing { get; set; }

        /// <summary>
        /// Enable detecting links and making them clickable.
        /// Defaults to true.
        /// </summary>
        bool? Links { get; set; }

        /// <summary>
        /// Enable highlighting of matching brackets.
        /// Defaults to 'always'.
        /// </summary>
        string? MatchBrackets { get; set; }

        /// <summary>
        /// Controls whether suggestions allow matches in the middle of the word instead of only at the beginning
        /// </summary>
        bool? MatchOnWordStartOnly { get; set; }

        /// <summary>
        /// Control the behavior and rendering of the minimap.
        /// </summary>
        IEditorMinimapOptions? Minimap { get; set; }

        /// <summary>
        /// Control the mouse pointer style, either 'text' or 'default' or 'copy'
        /// Defaults to 'text'
        /// </summary>
        string? MouseStyle { get; set; }

        /// <summary>
        /// A multiplier to be used on the `deltaX` and `deltaY` of mouse wheel scroll events.
        /// Defaults to 1.
        /// </summary>
        double? MouseWheelScrollSensitivity { get; set; }

        /// <summary>
        /// Zoom the font in the editor when using the mouse wheel in combination with holding Ctrl.
        /// Defaults to false.
        /// </summary>
        bool? MouseWheelZoom { get; set; }

        /// <summary>
        /// Controls the max number of text cursors that can be in an active editor at once.
        /// </summary>
        double? MultiCursorLimit { get; set; }

        /// <summary>
        /// Merge overlapping selections.
        /// Defaults to true
        /// </summary>
        bool? MultiCursorMergeOverlapping { get; set; }

        /// <summary>
        /// The modifier to be used to add multiple cursors with the mouse.
        /// Defaults to 'alt'
        /// </summary>
        string? MultiCursorModifier { get; set; }

        /// <summary>
        /// Configure the behaviour when pasting a text with the line count equal to the cursor count.
        /// Defaults to 'spread'.
        /// </summary>
        string? MultiCursorPaste { get; set; }

        /// <summary>
        /// Enable semantic occurrences highlight.
        /// Defaults to 'singleFile'.
        /// 'off' disables occurrence highlighting
        /// 'singleFile' triggers occurrence highlighting in the current document
        /// 'multiFile'  triggers occurrence highlighting across valid open documents
        /// </summary>
        string? OccurrencesHighlight { get; set; }

        /// <summary>
        /// Controls if a border should be drawn around the overview ruler.
        /// Defaults to `true`.
        /// </summary>
        bool? OverviewRulerBorder { get; set; }

        /// <summary>
        /// The number of vertical lanes the overview ruler should render.
        /// Defaults to 3.
        /// </summary>
        double? OverviewRulerLanes { get; set; }

        /// <summary>
        /// Controls the spacing around the editor.
        /// </summary>
        IEditorPaddingOptions? Padding { get; set; }

        /// <summary>
        /// Parameter hint options.
        /// </summary>
        IEditorParameterHintOptions? ParameterHints { get; set; }

        /// <summary>
        /// Controls support for changing how content is pasted into the editor.
        /// </summary>
        IPasteAsOptions? PasteAs { get; set; }

        /// <summary>
        /// Controls whether to focus the inline editor in the peek widget by default.
        /// Defaults to false.
        /// </summary>
        string? PeekWidgetDefaultFocus { get; set; }

        /// <summary>
        /// Sets a placeholder for the editor.
        /// If set, the placeholder is shown if the editor is empty.
        /// </summary>
        string? Placeholder { get; set; }

        /// <summary>
        /// Enable quick suggestions (shadow suggestions)
        /// Defaults to true.
        /// </summary>
        object? QuickSuggestions { get; set; }

        /// <summary>
        /// Quick suggestions show delay (in ms)
        /// Defaults to 10 (ms)
        /// </summary>
        double? QuickSuggestionsDelay { get; set; }

        /// <summary>
        /// Should the editor be read only. See also `domReadOnly`.
        /// Defaults to false.
        /// </summary>
        bool? ReadOnly { get; set; }

        /// <summary>
        /// The message to display when the editor is readonly.
        /// </summary>
        IMarkdownString? ReadOnlyMessage { get; set; }

        /// <summary>
        /// deprecated, use linkedEditing instead
        /// </summary>
        bool? RenameOnType { get; set; }

        /// <summary>
        /// Enable rendering of control characters.
        /// Defaults to true.
        /// </summary>
        bool? RenderControlCharacters { get; set; }

        /// <summary>
        /// Render last line number when the file ends with a newline.
        /// Defaults to 'on' for Windows and macOS and 'dimmed' for Linux.
        /// </summary>
        string? RenderFinalNewline { get; set; }

        /// <summary>
        /// Enable rendering of current line highlight.
        /// Defaults to all.
        /// </summary>
        string? RenderLineHighlight { get; set; }

        /// <summary>
        /// Control if the current line highlight should be rendered only the editor is focused.
        /// Defaults to false.
        /// </summary>
        bool? RenderLineHighlightOnlyWhenFocus { get; set; }

        /// <summary>
        /// Should the editor render validation decorations.
        /// Defaults to editable.
        /// </summary>
        string? RenderValidationDecorations { get; set; }

        /// <summary>
        /// Enable rendering of whitespace.
        /// Defaults to 'selection'.
        /// </summary>
        string? RenderWhitespace { get; set; }

        /// <summary>
        /// When revealing the cursor, a virtual padding (px) is added to the cursor, turning it into a rectangle.
        /// This virtual padding ensures that the cursor gets revealed before hitting the edge of the viewport.
        /// Defaults to 30 (px).
        /// </summary>
        double? RevealHorizontalRightPadding { get; set; }

        /// <summary>
        /// Render the editor selection with rounded borders.
        /// Defaults to true.
        /// </summary>
        bool? RoundedSelection { get; set; }

        /// <summary>
        /// Render vertical lines at the specified columns.
        /// Defaults to empty array.
        /// </summary>
        object[]? Rulers { get; set; }

        /// <summary>
        /// Control whether a screen reader announces inline suggestion content immediately.
        /// </summary>
        bool? ScreenReaderAnnounceInlineSuggestion { get; set; }

        /// <summary>
        /// Control the behavior and rendering of the scrollbars.
        /// </summary>
        IEditorScrollbarOptions? Scrollbar { get; set; }

        /// <summary>
        /// Enable that scrolling can go beyond the last column by a number of columns.
        /// Defaults to 5.
        /// </summary>
        double? ScrollBeyondLastColumn { get; set; }

        /// <summary>
        /// Enable that scrolling can go one screen size after the last line.
        /// Defaults to true.
        /// </summary>
        bool? ScrollBeyondLastLine { get; set; }

        /// <summary>
        /// Enable that the editor scrolls only the predominant axis. Prevents horizontal drift when scrolling vertically on a trackpad.
        /// Defaults to true.
        /// </summary>
        bool? ScrollPredominantAxis { get; set; }

        /// <summary>
        /// Enable Linux primary clipboard.
        /// Defaults to true.
        /// </summary>
        bool? SelectionClipboard { get; set; }

        /// <summary>
        /// Enable selection highlight.
        /// Defaults to true.
        /// </summary>
        bool? SelectionHighlight { get; set; }

        /// <summary>
        /// Should the corresponding line be selected when clicking on the line number?
        /// Defaults to true.
        /// </summary>
        bool? SelectOnLineNumbers { get; set; }

        /// <summary>
        /// Controls strikethrough deprecated variables.
        /// </summary>
        bool? ShowDeprecated { get; set; }

        /// <summary>
        /// Controls whether the fold actions in the gutter stay always visible or hide unless the mouse is over the gutter.
        /// Defaults to 'mouseover'.
        /// </summary>
        string? ShowFoldingControls { get; set; }

        /// <summary>
        /// Controls fading out of unused variables.
        /// </summary>
        bool? ShowUnused { get; set; }

        /// <summary>
        /// Smart select options.
        /// </summary>
        ISmartSelectOptions? SmartSelect { get; set; }

        /// <summary>
        /// Enable that the editor animates scrolling to a position.
        /// Defaults to false.
        /// </summary>
        bool? SmoothScrolling { get; set; }

        /// <summary>
        /// Enable snippet suggestions. Default to 'true'.
        /// </summary>
        string? SnippetSuggestions { get; set; }

        /// <summary>
        /// Control the behavior of sticky scroll options
        /// </summary>
        IEditorStickyScrollOptions? StickyScroll { get; set; }

        /// <summary>
        /// Emulate selection behaviour of tab characters when using spaces for indentation.
        /// This means selection will stick to tab stops.
        /// </summary>
        bool? StickyTabStops { get; set; }

        /// <summary>
        /// Performance guard: Stop rendering a line after x characters.
        /// Defaults to 10000.
        /// Use -1 to never stop rendering
        /// </summary>
        double? StopRenderingLineAfter { get; set; }

        /// <summary>
        /// Suggest options.
        /// </summary>
        ISuggestOptions? Suggest { get; set; }

        /// <summary>
        /// The font size for the suggest widget.
        /// Defaults to the editor font size.
        /// </summary>
        double? SuggestFontSize { get; set; }

        /// <summary>
        /// The line height for the suggest widget.
        /// Defaults to the editor line height.
        /// </summary>
        double? SuggestLineHeight { get; set; }

        /// <summary>
        /// Enable the suggestion box to pop-up on trigger characters.
        /// Defaults to true.
        /// </summary>
        bool? SuggestOnTriggerCharacters { get; set; }

        /// <summary>
        /// The history mode for suggestions.
        /// </summary>
        string? SuggestSelection { get; set; }

        /// <summary>
        /// Enable tab completion.
        /// </summary>
        string? TabCompletion { get; set; }

        /// <summary>
        /// Controls whether the editor / terminal receives tabs or defers them to the workbench for navigation.
        /// </summary>
        bool? TabFocusMode { get; set; }

        /// <summary>
        /// The `tabindex` property of the editor's textarea
        /// </summary>
        double? TabIndex { get; set; }

        /// <summary>
        /// Controls whether clicking on the empty content after a folded line will unfold the line.
        /// Defaults to false.
        /// </summary>
        bool? UnfoldOnClickAfterEndOfLine { get; set; }

        /// <summary>
        /// Controls the behavior of the unicode highlight feature
        /// (by default, ambiguous and invisible characters are highlighted).
        /// </summary>
        IUnicodeHighlightOptions? UnicodeHighlight { get; set; }

        /// <summary>
        /// Remove unusual line terminators like LINE SEPARATOR (LS), PARAGRAPH SEPARATOR (PS).
        /// Defaults to 'prompt'.
        /// </summary>
        string? UnusualLineTerminators { get; set; }

        /// <summary>
        /// Control if the editor should use shadow DOM.
        /// </summary>
        bool? UseShadowDOM { get; set; }

        /// <summary>
        /// Inserting and deleting whitespace follows tab stops.
        /// </summary>
        bool? UseTabStops { get; set; }

        /// <summary>
        /// Sets whether line breaks appear wherever the text would otherwise overflow its content box.
        /// When wordBreak = 'normal', Use the default line break rule.
        /// When wordBreak = 'keepAll', Word breaks should not be used for Chinese/Japanese/Korean (CJK) text. Non-CJK text behavior is the same as for normal.
        /// </summary>
        string? WordBreak { get; set; }

        /// <summary>
        /// Locales used for segmenting lines into words when doing word related navigations or operations.
        ///
        /// Specify the BCP 47 language tag of the word you wish to recognize (e.g., ja, zh-CN, zh-Hant-TW, etc.).
        /// Defaults to empty array
        /// </summary>
        object? WordSegmenterLocales { get; set; }

        /// <summary>
        /// A string containing the word separators used when doing word navigation.
        /// Defaults to `~!@#$%^&amp;*()-=+[{]}\\|;:\'",.&lt;&gt;/?
        /// </summary>
        string? WordSeparators { get; set; }

        /// <summary>
        /// Control the wrapping of the editor.
        /// When `wordWrap` = "off", the lines will never wrap.
        /// When `wordWrap` = "on", the lines will wrap at the viewport width.
        /// When `wordWrap` = "wordWrapColumn", the lines will wrap at `wordWrapColumn`.
        /// When `wordWrap` = "bounded", the lines will wrap at min(viewport width, wordWrapColumn).
        /// Defaults to "off".
        /// </summary>
        string? WordWrap { get; set; }

        /// <summary>
        /// Configure word wrapping characters. A break will be introduced after these characters.
        /// </summary>
        string? WordWrapBreakAfterCharacters { get; set; }

        /// <summary>
        /// Configure word wrapping characters. A break will be introduced before these characters.
        /// </summary>
        string? WordWrapBreakBeforeCharacters { get; set; }

        /// <summary>
        /// Control the wrapping of the editor.
        /// When `wordWrap` = "off", the lines will never wrap.
        /// When `wordWrap` = "on", the lines will wrap at the viewport width.
        /// When `wordWrap` = "wordWrapColumn", the lines will wrap at `wordWrapColumn`.
        /// When `wordWrap` = "bounded", the lines will wrap at min(viewport width, wordWrapColumn).
        /// Defaults to 80.
        /// </summary>
        double? WordWrapColumn { get; set; }

        /// <summary>
        /// Override the `wordWrap` setting.
        /// </summary>
        string? WordWrapOverride1 { get; set; }

        /// <summary>
        /// Override the `wordWrapOverride1` setting.
        /// </summary>
        string? WordWrapOverride2 { get; set; }

        /// <summary>
        /// Control indentation of wrapped lines. Can be: 'none', 'same', 'indent' or 'deepIndent'.
        /// Defaults to 'same' in vscode and to 'none' in monaco-editor.
        /// </summary>
        string? WrappingIndent { get; set; }

        /// <summary>
        /// Controls the wrapping strategy to use.
        /// Defaults to 'simple'.
        /// </summary>
        string? WrappingStrategy { get; set; }

    }
}
