// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorConstructionOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public partial interface IEditorConstructionOptions : IEditorOptions
    {
        /// <summary>
        /// The initial editor dimension (to avoid measuring the container).
        /// </summary>
        IDimension? Dimension { get; set; }
    }
}
