// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A builder and helper for edit operations for a command.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditOperationBuilder.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IEditOperationBuilder, EditOperationBuilder>))]
    public interface IEditOperationBuilder
    {
        /// <summary>
        /// Add a new edit operation (a replace operation).
        /// </summary>
        /// <param name="range">The range to replace (delete). May be empty to represent a simple insert.</param>
        /// <param name="text">The text to replace with. May be null to represent a simple delete.</param>
        void AddEditOperation(IRange range, string text, bool? forceMoveMarkers);

        /// <summary>
        /// Add a new edit operation (a replace operation).
        /// The inverse edits will be accessible in `ICursorStateComputerData.getInverseEditOperations()`
        /// </summary>
        /// <param name="range">The range to replace (delete). May be empty to represent a simple insert.</param>
        /// <param name="text">The text to replace with. May be null to represent a simple delete.</param>
        void AddTrackedEditOperation(IRange range, string text, bool? forceMoveMarkers);

        /// <summary>
        /// Track `selection` when applying edit operations.
        /// A best effort will be made to not grow/expand the selection.
        /// An empty selection will clamp to a nearby character.
        /// </summary>
        /// <param name="selection">The selection to track.</param>
        /// <param name="trackPreviousOnEmpty">If set, and the selection is empty, indicates whether the selection should clamp to the previous or the next character.</param>
        /// <returns>A string value.</returns>
        string TrackSelection(Selection selection, bool? trackPreviousOnEmpty);

    }
}
