// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for editor inlayHints
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorInlayHintsOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IEditorInlayHintsOptions, EditorInlayHintsOptions>))]
    public interface IEditorInlayHintsOptions
    {
        /// <summary>
        /// Enable the inline hints.
        /// Defaults to true.
        /// </summary>
        string? Enabled { get; set; }

        /// <summary>
        /// Font family of inline hints.
        /// Defaults to editor font family.
        /// </summary>
        string? FontFamily { get; set; }

        /// <summary>
        /// Font size of inline hints.
        /// Default to 90% of the editor font size.
        /// </summary>
        double? FontSize { get; set; }

        /// <summary>
        /// Enables the padding around the inlay hint.
        /// Defaults to false.
        /// </summary>
        bool? Padding { get; set; }

    }
}
