// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorStickyScrollOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IEditorStickyScrollOptions, EditorStickyScrollOptions>))]
    public interface IEditorStickyScrollOptions
    {
        /// <summary>
        /// Model to choose for sticky scroll by default
        /// </summary>
        string? DefaultModel { get; set; }

        /// <summary>
        /// Enable the sticky scroll
        /// </summary>
        bool? Enabled { get; set; }

        /// <summary>
        /// Maximum number of sticky lines to show
        /// </summary>
        double? MaxLineCount { get; set; }

        /// <summary>
        /// Define whether to scroll sticky scroll with editor horizontal scrollbae
        /// </summary>
        bool? ScrollWithEditor { get; set; }

    }
}
