// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for editor comments
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorCommentsOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed partial class IEditorCommentsOptions
    {
        /// <summary>
        /// Insert a space after the line comment token and inside the block comments tokens.
        /// Defaults to true.
        /// </summary>
        public bool? InsertSpace { get; set; }
    }
}
