// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A collection of decorations
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorDecorationsCollection.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IEditorDecorationsCollection, EditorDecorationsCollection>))]
    public interface IEditorDecorationsCollection
    {
        /// <summary>
        /// Get the decorations count.
        /// </summary>
        double Length { get; set; }

        /// <summary>
        /// An event emitted when decorations change in the editor,
        /// but the change is not caused by us setting or clearing the collection.
        /// </summary>
        IEvent<IModelDecorationsChangedEvent> OnDidChange { get; set; }

        /// <summary>
        /// Append `newDecorations` to this collection.
        /// </summary>
        /// <returns>An array of results.</returns>
        string[] Append(IModelDeltaDecoration[] newDecorations);

        /// <summary>
        /// Remove all previous decorations.
        /// </summary>
        void Clear();

        /// <summary>
        /// Get the range for a decoration.
        /// </summary>
        Range GetRange(double index);

        /// <summary>
        /// Get all ranges for decorations.
        /// </summary>
        /// <returns>An array of results.</returns>
        Range[] GetRanges();

        /// <summary>
        /// Determine if a decoration is in this collection.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        bool Has(IModelDecoration decoration);

        /// <summary>
        /// Replace all previous decorations with `newDecorations`.
        /// </summary>
        /// <returns>An array of results.</returns>
        string[] Set(IModelDeltaDecoration[] newDecorations);

    }
}
