// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorOption.html">Monaco API</see> for more details.
    /// </remarks>
    public interface IEditorOption<K, V>
    {
        V DefaultValue { get; set; }

        K Id { get; }

        string Name { get; }

        /// <summary>
        /// Might modify `value`.
        /// </summary>
        /// <returns>A ApplyUpdateResult instance.</returns>
        ApplyUpdateResult<V> ApplyUpdate(V @value, V update);

    }
}
