// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IGlyphMarginLanesModel.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IGlyphMarginLanesModel, GlyphMarginLanesModel>))]
    public interface IGlyphMarginLanesModel
    {
        /// <summary>
        /// The number of lanes that should be rendered in the editor.
        /// </summary>
        double RequiredLanes { get; }

        /// <summary>
        /// Gets the lanes that should be rendered starting at a given line number.
        /// </summary>
        /// <returns>An array of results.</returns>
        GlyphMarginLane[] GetLanesAtLine(double lineNumber);

        /// <summary>
        /// Registers that a lane should be visible at the Range in the model.
        /// </summary>
        /// <param name="persist">- if true, notes that the lane should always be visible, even on lines where there's no specific request for that lane.</param>
        void Push(GlyphMarginLane lane, Range range, bool? persist);

        /// <summary>
        /// Resets the model and ensures it can contain at least `maxLine` lines.
        /// </summary>
        void Reset(double maxLine);

    }
}
