// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A glyph margin widget renders in the editor glyph margin.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IGlyphMarginWidget.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IGlyphMarginWidget, GlyphMarginWidget>))]
    public interface IGlyphMarginWidget
    {
        /// <summary>
        /// Get the dom node of the glyph widget.
        /// </summary>
        /// <returns>A HTMLElement instance.</returns>
        object GetDomNode();

        /// <summary>
        /// Get a unique identifier of the glyph widget.
        /// </summary>
        /// <returns>A string value.</returns>
        string GetId();

        /// <summary>
        /// Get the placement of the glyph widget.
        /// </summary>
        /// <returns>A IGlyphMarginWidgetPosition instance.</returns>
        IGlyphMarginWidgetPosition GetPosition();

    }
}
