// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A position for rendering glyph margin widgets.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IGlyphMarginWidgetPosition.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IGlyphMarginWidgetPosition, GlyphMarginWidgetPosition>))]
    public interface IGlyphMarginWidgetPosition
    {
        /// <summary>
        /// The glyph margin lane where the widget should be shown.
        /// </summary>
        GlyphMarginLane Lane { get; set; }

        /// <summary>
        /// The editor range that this widget applies to.
        /// </summary>
        IRange Range { get; set; }

        /// <summary>
        /// The priority order of the widget, used for determining which widget
        /// to render when there are multiple.
        /// </summary>
        double ZIndex { get; set; }

    }
}
