// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IGuidesOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IGuidesOptions, GuidesOptions>))]
    public interface IGuidesOptions
    {
        /// <summary>
        /// Enable rendering of bracket pair guides.
        /// Defaults to false.
        /// </summary>
        object? BracketPairs { get; set; }

        /// <summary>
        /// Enable rendering of vertical bracket pair guides.
        /// Defaults to 'active'.
        /// </summary>
        object? BracketPairsHorizontal { get; set; }

        /// <summary>
        /// Enable highlighting of the active bracket pair.
        /// Defaults to true.
        /// </summary>
        bool? HighlightActiveBracketPair { get; set; }

        /// <summary>
        /// Enable highlighting of the active indent guide.
        /// Defaults to true.
        /// </summary>
        object? HighlightActiveIndentation { get; set; }

        /// <summary>
        /// Enable rendering of indent guides.
        /// Defaults to true.
        /// </summary>
        bool? Indentation { get; set; }

    }
}
