// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IInlineEditOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IInlineEditOptions, InlineEditOptions>))]
    public interface IInlineEditOptions
    {
        /// <summary>
        /// Enable or disable the rendering of automatic inline edit.
        /// </summary>
        bool? Enabled { get; set; }

        /// <summary>
        /// Font family for inline suggestions.
        /// </summary>
        object? FontFamily { get; set; }

        /// <summary>
        /// Does not clear active inline suggestions when the editor loses focus.
        /// </summary>
        bool? KeepOnBlur { get; set; }

        string? ShowToolbar { get; set; }

    }
}
