// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A keybinding rule.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IKeybindingRule.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IKeybindingRule, KeybindingRule>))]
    public interface IKeybindingRule
    {
        string? Command { get; set; }

        object? CommandArgs { get; set; }

        double Keybinding { get; set; }

        string? When { get; set; }

    }
}
