// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Options for rendering a model decoration in the overview ruler.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelDecorationOverviewRulerOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IModelDecorationOverviewRulerOptions, ModelDecorationOverviewRulerOptions>))]
    public interface IModelDecorationOverviewRulerOptions : IDecorationOptions
    {
        /// <summary>
        /// The position in the overview ruler.
        /// </summary>
        OverviewRulerLane Position { get; set; }

    }
}
