// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelOptionsChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IModelOptionsChangedEvent, ModelOptionsChangedEvent>))]
    public interface IModelOptionsChangedEvent
    {
        bool IndentSize { get; }

        bool InsertSpaces { get; }

        bool TabSize { get; }

        bool TrimAutoWhitespace { get; }

    }
}
