// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// An event describing that the language configuration associated with a model has changed.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelLanguageConfigurationChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IModelLanguageConfigurationChangedEvent, ModelLanguageConfigurationChangedEvent>))]
    public interface IModelLanguageConfigurationChangedEvent
    {
    }
}
