// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// An event describing that the current language associated with a model has changed.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelLanguageChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IModelLanguageChangedEvent, ModelLanguageChangedEvent>))]
    public interface IModelLanguageChangedEvent
    {
        /// <summary>
        /// New language
        /// </summary>
        string NewLanguage { get; }

        /// <summary>
        /// Previous language
        /// </summary>
        string OldLanguage { get; }

        /// <summary>
        /// Source of the call that caused the event.
        /// </summary>
        string Source { get; }

    }
}
