// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// An event describing that an editor has had its model reset (i.e. `editor.setModel()`).
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IModelChangedEvent, ModelChangedEvent>))]
    public interface IModelChangedEvent
    {
        /// <summary>
        /// The `uri` of the new model or null.
        /// </summary>
        Uri NewModelUrl { get; }

        /// <summary>
        /// The `uri` of the previous model or null.
        /// </summary>
        Uri OldModelUrl { get; }

    }
}
