// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A decoration in the model.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelDecoration.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IModelDecoration, ModelDecoration>))]
    public interface IModelDecoration
    {
        /// <summary>
        /// Identifier for a decoration.
        /// </summary>
        string Id { get; }

        /// <summary>
        /// Options associated with this decoration.
        /// </summary>
        IModelDecorationOptions Options { get; }

        /// <summary>
        /// Identifier for a decoration's owner.
        /// </summary>
        double OwnerId { get; }

        /// <summary>
        /// Range that this decoration covers.
        /// </summary>
        Range Range { get; }

    }
}
