// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// An event describing a change in the text of a model.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelContentChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IModelContentChangedEvent, ModelContentChangedEvent>))]
    public interface IModelContentChangedEvent
    {
        /// <summary>
        /// The changes are ordered from the end of the document to the beginning, so they should be safe to apply in sequence.
        /// </summary>
        IModelContentChange[] Changes { get; }

        /// <summary>
        /// The (new) end-of-line character.
        /// </summary>
        string Eol { get; }

        /// <summary>
        /// Flag that indicates that this event describes an eol change.
        /// </summary>
        bool IsEolChange { get; }

        /// <summary>
        /// Flag that indicates that all decorations were lost with this edit.
        /// The model has been reset to a new value.
        /// </summary>
        bool IsFlush { get; }

        /// <summary>
        /// Flag that indicates that this event was generated while redoing.
        /// </summary>
        bool IsRedoing { get; }

        /// <summary>
        /// Flag that indicates that this event was generated while undoing.
        /// </summary>
        bool IsUndoing { get; }

        /// <summary>
        /// The new version id the model has transitioned to.
        /// </summary>
        double VersionId { get; }

    }
}
