// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// An event describing that model decorations have changed.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelDecorationsChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IModelDecorationsChangedEvent, ModelDecorationsChangedEvent>))]
    public interface IModelDecorationsChangedEvent
    {
        bool AffectsGlyphMargin { get; }

        bool AffectsLineNumber { get; }

        bool AffectsMinimap { get; }

        bool AffectsOverviewRuler { get; }

    }
}
