// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetOverlayWidget.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IMouseTargetOverlayWidget, MouseTargetOverlayWidget>))]
    public interface IMouseTargetOverlayWidget : IBaseMouseTarget
    {
        string Detail { get; }

        object Position { get; }

        object Range { get; }

        MouseTargetType.OVERLAY_WIDGET Type { get; }

    }
}
