// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetMarginData.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IMouseTargetMarginData, MouseTargetMarginData>))]
    public interface IMouseTargetMarginData
    {
        GlyphMarginLane? GlyphMarginLane { get; }

        double GlyphMarginLeft { get; }

        double GlyphMarginWidth { get; }

        bool IsAfterLines { get; }

        double LineNumbersWidth { get; }

        double OffsetX { get; }

    }
}
