// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetTextarea.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IMouseTargetTextarea, MouseTargetTextarea>))]
    public interface IMouseTargetTextarea : IBaseMouseTarget
    {
        object Position { get; }

        object Range { get; }

        MouseTargetType.TEXTAREA Type { get; }

    }
}
