// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetContentTextData.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IMouseTargetContentTextData, MouseTargetContentTextData>))]
    public interface IMouseTargetContentTextData
    {
        bool MightBeForeignElement { get; }

    }
}
