// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetViewZoneData.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IMouseTargetViewZoneData, MouseTargetViewZoneData>))]
    public interface IMouseTargetViewZoneData
    {
        double AfterLineNumber { get; }

        Position Position { get; }

        Position PositionAfter { get; }

        Position PositionBefore { get; }

        string ViewZoneId { get; }

    }
}
