// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetOverviewRuler.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IMouseTargetOverviewRuler, MouseTargetOverviewRuler>))]
    public interface IMouseTargetOverviewRuler : IBaseMouseTarget
    {
        MouseTargetType.OVERVIEW_RULER Type { get; }

    }
}
