// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetContentText.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IMouseTargetContentText, MouseTargetContentText>))]
    public interface IMouseTargetContentText : IBaseMouseTarget
    {
        IMouseTargetContentTextData Detail { get; }

        Position Position { get; }

        Range Range { get; }

        MouseTargetType.CONTENT_TEXT Type { get; }

    }
}
