// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetContentWidget.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IMouseTargetContentWidget, MouseTargetContentWidget>))]
    public interface IMouseTargetContentWidget : IBaseMouseTarget
    {
        string Detail { get; }

        object Position { get; }

        object Range { get; }

        MouseTargetType.CONTENT_WIDGET Type { get; }

    }
}
