// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetUnknown.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IMouseTargetUnknown, MouseTargetUnknown>))]
    public interface IMouseTargetUnknown : IBaseMouseTarget
    {
        MouseTargetType.UNKNOWN Type { get; }

    }
}
