// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetOutsideEditor.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IMouseTargetOutsideEditor, MouseTargetOutsideEditor>))]
    public interface IMouseTargetOutsideEditor : IBaseMouseTarget
    {
        double OutsideDistance { get; }

        string OutsidePosition { get; }

        MouseTargetType.OUTSIDE_EDITOR Type { get; }

    }
}
