// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.INewScrollPosition.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<INewScrollPosition, NewScrollPosition>))]
    public interface INewScrollPosition
    {
        double? ScrollLeft { get; set; }

        double? ScrollTop { get; set; }

    }
}
