// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// Configures text that is injected into the view without changing the underlying document.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.InjectedTextOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public interface InjectedTextOptions
    {
        /// <summary>
        /// This field allows to attach data to this injected text.
        /// The data can be read when injected texts at a given position are queried.
        /// </summary>
        object? AttachedData { get; }

        /// <summary>
        /// Sets the text to inject. Must be a single line.
        /// </summary>
        string Content { get; }

        /// <summary>
        /// /**
        ///          * Configures cursor stops around injected text.
        ///          * Defaults to {@link InjectedTextCursorStops.Both}.
        /// </summary>
        InjectedTextCursorStops? CursorStops { get; }

        /// <summary>
        /// If set, the decoration will be rendered inline with the text with this CSS class name.
        /// </summary>
        string? InlineClassName { get; }

        /// <summary>
        /// If there is an `inlineClassName` which affects letter spacing.
        /// </summary>
        bool? InlineClassNameAffectsLetterSpacing { get; }

    }
}
