// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IInlineEditOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class InlineEditOptions : IInlineEditOptions
    {
        /// <summary>
        /// Enable or disable the rendering of automatic inline edit.
        /// </summary>
        public bool? Enabled { get; set; }

        /// <summary>
        /// Font family for inline suggestions.
        /// </summary>
        public object? FontFamily { get; set; }

        /// <summary>
        /// Does not clear active inline suggestions when the editor loses focus.
        /// </summary>
        public bool? KeepOnBlur { get; set; }

        public string? ShowToolbar { get; set; }

    }
}
