// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IInlineSuggestOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class InlineSuggestOptions : IInlineSuggestOptions
    {
        /// <summary>
        /// Enable or disable the rendering of automatic inline completions.
        /// </summary>
        public bool? Enabled { get; set; }

        /// <summary>
        /// Font family for inline suggestions.
        /// </summary>
        public object? FontFamily { get; set; }

        /// <summary>
        /// Does not clear active inline suggestions when the editor loses focus.
        /// </summary>
        public bool? KeepOnBlur { get; set; }

        /// <summary>
        /// Configures the mode.
        /// Use `prefix` to only show ghost text if the text to replace is a prefix of the suggestion text.
        /// Use `subword` to only show ghost text if the replace text is a subword of the suggestion text.
        /// Use `subwordSmart` to only show ghost text if the replace text is a subword of the suggestion text, but the subword must start after the cursor position.
        /// Defaults to `prefix`.
        /// </summary>
        public string? Mode { get; set; }

        public string? ShowToolbar { get; set; }

        public bool? SuppressSuggestions { get; set; }

    }
}
