// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.InternalEditorScrollbarOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public interface InternalEditorScrollbarOptions
    {
        bool AlwaysConsumeMouseWheel { get; }

        double ArrowSize { get; }

        bool HandleMouseWheel { get; }

        ScrollbarVisibility Horizontal { get; }

        bool HorizontalHasArrows { get; }

        double HorizontalScrollbarSize { get; }

        double HorizontalSliderSize { get; }

        bool IgnoreHorizontalScrollbarInContentHeight { get; }

        bool ScrollByPage { get; }

        bool UseShadows { get; }

        ScrollbarVisibility Vertical { get; }

        bool VerticalHasArrows { get; }

        double VerticalScrollbarSize { get; }

        double VerticalSliderSize { get; }

    }
}
