// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A position for rendering overlay widgets.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IOverlayWidgetPosition.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IOverlayWidgetPosition, OverlayWidgetPosition>))]
    public interface IOverlayWidgetPosition
    {
        /// <summary>
        /// The position preference for the overlay widget.
        /// </summary>
        object Preference { get; set; }

        /// <summary>
        /// When set, stacks with other overlay widgets with the same preference,
        /// in an order determined by the ordinal value.
        /// </summary>
        double? StackOridinal { get; set; }

    }
}
