// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A paste event originating from the editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IPasteEvent.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IPasteEvent, PasteEvent>))]
    public interface IPasteEvent
    {
        ClipboardEvent? ClipboardEvent { get; }

        string LanguageId { get; }

        Range Range { get; }

    }
}
