// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for editor pasting as into behavior
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IPasteAsOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IPasteAsOptions, PasteAsOptions>))]
    public interface IPasteAsOptions
    {
        /// <summary>
        /// Enable paste as functionality in editors.
        /// Defaults to true.
        /// </summary>
        bool? Enabled { get; set; }

        /// <summary>
        /// Controls if a widget is shown after a drop.
        /// Defaults to 'afterPaste'.
        /// </summary>
        string? ShowPasteSelector { get; set; }

    }
}
