// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for quick suggestions
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IQuickSuggestionsOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IQuickSuggestionsOptions, QuickSuggestionsOptions>))]
    public interface IQuickSuggestionsOptions
    {
        object? Comments { get; set; }

        object? Other { get; set; }

        object? Strings { get; set; }

    }
}
