// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IStandaloneThemeData.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IStandaloneThemeData, StandaloneThemeData>))]
    public interface IStandaloneThemeData
    {
        BuiltinTheme Base { get; set; }

        IColors Colors { get; set; }

        string[]? EncodedTokensColors { get; set; }

        bool Inherit { get; set; }

        ITokenThemeRule[] Rules { get; set; }

    }
}
