// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// The options to create an editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IStandaloneEditorConstructionOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IStandaloneEditorConstructionOptions, StandaloneEditorConstructionOptions>))]
    public interface IStandaloneEditorConstructionOptions : IEditorConstructionOptions, IGlobalEditorOptions
    {
        /// <summary>
        /// An URL to open when Ctrl+H (Windows and Linux) or Cmd+H (OSX) is pressed in
        /// the accessibility help dialog in the editor.
        ///
        /// Defaults to "https://go.microsoft.com/fwlink/?linkid=852450"
        /// </summary>
        string? AccessibilityHelpUrl { get; set; }

        /// <summary>
        /// Container element to use for ARIA messages.
        /// Defaults to document.body.
        /// </summary>
        object? AriaContainerElement { get; set; }

        /// <summary>
        /// If enabled, will automatically change to high contrast theme if the OS is using a high contrast theme.
        /// Defaults to true.
        /// </summary>
        bool? AutoDetectHighContrast { get; set; }

        /// <summary>
        /// The initial language of the auto created model in the editor.
        /// To not automatically create a model, use `model: null`.
        /// </summary>
        string? Language { get; set; }

        /// <summary>
        /// The initial model associated with this code editor.
        /// </summary>
        ITextModel? Model { get; set; }

        /// <summary>
        /// Initial theme to be used for rendering.
        /// The current out-of-the-box available themes are: 'vs' (default), 'vs-dark', 'hc-black', 'hc-light.
        /// You can create custom themes via `monaco.editor.defineTheme`.
        /// To switch a theme, use `monaco.editor.setTheme`.
        /// **NOTE**: The theme might be overwritten if the OS is in high contrast mode, unless `autoDetectHighContrast` is set to false.
        /// </summary>
        string? Theme { get; set; }

        /// <summary>
        /// The initial value of the auto created model in the editor.
        /// To not automatically create a model, use `model: null`.
        /// </summary>
        string? Value { get; set; }

    }
}
