// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IStandaloneDiffEditor.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IStandaloneDiffEditor, StandaloneDiffEditor>))]
    public interface IStandaloneDiffEditor : IDiffEditor
    {
        /// <returns>A IDisposable instance.</returns>
        IDisposable AddAction(IActionDescriptor descriptor);

        string AddCommand(double keybinding, ICommandHandler handler, string? context);

        /// <returns>A IContextKey instance.</returns>
        IContextKey<T> CreateContextKey<T>(string key, T defaultValue);

        /// <returns>A IStandaloneCodeEditor instance.</returns>
        IStandaloneCodeEditor GetModifiedEditor();

        /// <returns>A IStandaloneCodeEditor instance.</returns>
        IStandaloneCodeEditor GetOriginalEditor();

    }
}
