// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A model.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ITextModel.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ITextModel, TextModel>))]
    public interface ITextModel
    {
        /// <summary>
        /// A unique identifier associated with this model.
        /// </summary>
        string Id { get; }

        /// <summary>
        /// An event emitted when the model has been attached to the first editor or detached from the last editor.
        /// </summary>
        IEvent<object> OnDidChangeAttached { get; }

        /// <summary>
        /// An event emitted when decorations of the model have changed.
        /// </summary>
        IEvent<IModelDecorationsChangedEvent> OnDidChangeDecorations { get; }

        /// <summary>
        /// An event emitted when the language associated with the model has changed.
        /// </summary>
        IEvent<IModelLanguageChangedEvent> OnDidChangeLanguage { get; }

        /// <summary>
        /// An event emitted when the language configuration associated with the model has changed.
        /// </summary>
        IEvent<IModelLanguageConfigurationChangedEvent> OnDidChangeLanguageConfiguration { get; }

        /// <summary>
        /// An event emitted when the model options have changed.
        /// </summary>
        IEvent<IModelOptionsChangedEvent> OnDidChangeOptions { get; }

        /// <summary>
        /// An event emitted right before disposing the model.
        /// </summary>
        IEvent<object> OnWillDispose { get; }

        /// <summary>
        /// Gets the resource associated with this editor model.
        /// </summary>
        Uri Uri { get; }

        /// <summary>
        /// Edit the model without adding the edits to the undo stack.
        /// This can have dire consequences on the undo stack! See
        /// </summary>
        /// <param name="operations">The edit operations.</param>
        void ApplyEdits(IIdentifiedSingleEditOperation[] operations);

        void ApplyEdits(IIdentifiedSingleEditOperation[] operations, bool computeUndoEdits);

        /// <returns>An array of results.</returns>
        IValidEditOperation[] ApplyEdits(IIdentifiedSingleEditOperation[] operations, bool computeUndoEdits);

        /// <summary>
        /// Get the text stored in this model.
        /// </summary>
        /// <returns>A ITextSnapshot instance.</returns>
        ITextSnapshot CreateSnapshot(bool? preserveBOM);

        /// <summary>
        /// Perform a minimum amount of operations, in order to transform the decorations
        /// identified by `oldDecorations` to the decorations described by `newDecorations`
        /// and returns the new identifiers associated with the resulting decorations.
        /// </summary>
        /// <param name="oldDecorations">Array containing previous decorations identifiers.</param>
        /// <param name="newDecorations">Array describing what decorations should result after the call.</param>
        /// <param name="ownerId">Identifies the editor id in which these decorations should appear. If no `ownerId` is provided, the decorations will appear in all editors that attach this model.</param>
        /// <returns>An array of results.</returns>
        string[] DeltaDecorations(string[] oldDecorations, IModelDeltaDecoration[] newDecorations, double? ownerId);

        /// <summary>
        /// Detect the indentation options for this model from its content.
        /// </summary>
        void DetectIndentation(bool defaultInsertSpaces, double defaultTabSize);

        /// <summary>
        /// Destroy this model.
        /// </summary>
        void Dispose();

        /// <summary>
        /// Search the model.
        /// </summary>
        /// <param name="searchString">The string used to search. If it is a regular expression, set `isRegex` to true.</param>
        /// <param name="searchOnlyEditableRange">Limit the searching to only search inside the editable range of the model.</param>
        /// <param name="isRegex">Used to indicate that `searchString` is a regular expression.</param>
        /// <param name="matchCase">Force the matching to match lower/upper case exactly.</param>
        /// <param name="wordSeparators">Force the matching to match entire words only. Pass null otherwise.</param>
        /// <param name="captureMatches">The result will contain the captured groups.</param>
        /// <param name="limitResultCount">Limit the number of results</param>
        /// <returns>An array of results.</returns>
        FindMatch[] FindMatches(string searchString, bool searchOnlyEditableRange, bool isRegex, bool matchCase, string wordSeparators, bool captureMatches, double? limitResultCount);

        /// <summary>
        /// Search the model.
        /// </summary>
        /// <param name="searchString">The string used to search. If it is a regular expression, set `isRegex` to true.</param>
        /// <param name="searchScope">Limit the searching to only search inside these ranges.</param>
        /// <param name="isRegex">Used to indicate that `searchString` is a regular expression.</param>
        /// <param name="matchCase">Force the matching to match lower/upper case exactly.</param>
        /// <param name="wordSeparators">Force the matching to match entire words only. Pass null otherwise.</param>
        /// <param name="captureMatches">The result will contain the captured groups.</param>
        /// <param name="limitResultCount">Limit the number of results</param>
        /// <returns>An array of results.</returns>
        FindMatch[] FindMatches(string searchString, object searchScope, bool isRegex, bool matchCase, string wordSeparators, bool captureMatches, double? limitResultCount);

        /// <summary>
        /// Search the model for the next match. Loops to the beginning of the model if needed.
        /// </summary>
        /// <param name="searchString">The string used to search. If it is a regular expression, set `isRegex` to true.</param>
        /// <param name="searchStart">Start the searching at the specified position.</param>
        /// <param name="isRegex">Used to indicate that `searchString` is a regular expression.</param>
        /// <param name="matchCase">Force the matching to match lower/upper case exactly.</param>
        /// <param name="wordSeparators">Force the matching to match entire words only. Pass null otherwise.</param>
        /// <param name="captureMatches">The result will contain the captured groups.</param>
        FindMatch FindNextMatch(string searchString, IPosition searchStart, bool isRegex, bool matchCase, string wordSeparators, bool captureMatches);

        /// <summary>
        /// Search the model for the previous match. Loops to the end of the model if needed.
        /// </summary>
        /// <param name="searchString">The string used to search. If it is a regular expression, set `isRegex` to true.</param>
        /// <param name="searchStart">Start the searching at the specified position.</param>
        /// <param name="isRegex">Used to indicate that `searchString` is a regular expression.</param>
        /// <param name="matchCase">Force the matching to match lower/upper case exactly.</param>
        /// <param name="wordSeparators">Force the matching to match entire words only. Pass null otherwise.</param>
        /// <param name="captureMatches">The result will contain the captured groups.</param>
        FindMatch FindPreviousMatch(string searchString, IPosition searchStart, bool isRegex, bool matchCase, string wordSeparators, bool captureMatches);

        /// <summary>
        /// Gets all the decorations as an array.
        /// </summary>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <param name="filterOutValidation">If set, it will ignore decorations specific to validation (i.e. warnings, errors).</param>
        /// <returns>An array of results.</returns>
        IModelDecoration[] GetAllDecorations(double? ownerId, bool? filterOutValidation);

        /// <summary>
        /// Gets all decorations that render in the glyph margin as an array.
        /// </summary>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <returns>An array of results.</returns>
        IModelDecoration[] GetAllMarginDecorations(double? ownerId);

        /// <summary>
        /// Get the alternative version id of the model.
        /// This alternative version id is not always incremented,
        /// it will return the same values in the case of undo-redo.
        /// </summary>
        /// <returns>A numeric value.</returns>
        double GetAlternativeVersionId();

        /// <summary>
        /// Get the character count of text in a certain range.
        /// </summary>
        /// <param name="range">The range describing what text length to get.</param>
        /// <returns>A numeric value.</returns>
        double GetCharacterCountInRange(IRange range, EndOfLinePreference? eol);

        /// <summary>
        /// Get the options associated with a decoration.
        /// </summary>
        /// <param name="id">The decoration id.</param>
        IModelDecorationOptions GetDecorationOptions(string id);

        /// <summary>
        /// Get the range associated with a decoration.
        /// </summary>
        /// <param name="id">The decoration id.</param>
        Range GetDecorationRange(string id);

        /// <summary>
        /// Gets all the decorations in a range as an array. Only `startLineNumber` and `endLineNumber` from `range` are used for filtering.
        /// So for now it returns all the decorations on the same line as `range`.
        /// </summary>
        /// <param name="range">The range to search in</param>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <param name="filterOutValidation">If set, it will ignore decorations specific to validation (i.e. warnings, errors).</param>
        /// <param name="onlyMinimapDecorations">If set, it will return only decorations that render in the minimap.</param>
        /// <param name="onlyMarginDecorations">If set, it will return only decorations that render in the glyph margin.</param>
        /// <returns>An array of results.</returns>
        IModelDecoration[] GetDecorationsInRange(IRange range, double? ownerId, bool? filterOutValidation, bool? onlyMinimapDecorations, bool? onlyMarginDecorations);

        /// <summary>
        /// Get the end of line sequence predominantly used in the text buffer.
        /// </summary>
        /// <returns>A EndOfLineSequence instance.</returns>
        EndOfLineSequence GetEndOfLineSequence();

        /// <summary>
        /// Get the end of line sequence predominantly used in the text buffer.
        /// </summary>
        /// <returns>A string value.</returns>
        string GetEOL();

        /// <summary>
        /// Get a range covering the entire model.
        /// </summary>
        /// <returns>A Range instance.</returns>
        Range GetFullModelRange();

        /// <summary>
        /// Gets all the decorations that contain injected text.
        /// </summary>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <returns>An array of results.</returns>
        IModelDecoration[] GetInjectedTextDecorations(double? ownerId);

        /// <summary>
        /// Get the language associated with this model.
        /// </summary>
        /// <returns>A string value.</returns>
        string GetLanguageId();

        /// <summary>
        /// Get the text for a certain line.
        /// </summary>
        /// <returns>A string value.</returns>
        string GetLineContent(double lineNumber);

        /// <summary>
        /// Get the number of lines in the model.
        /// </summary>
        /// <returns>A numeric value.</returns>
        double GetLineCount();

        /// <summary>
        /// Gets all the decorations for the line `lineNumber` as an array.
        /// </summary>
        /// <param name="lineNumber">The line number</param>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <param name="filterOutValidation">If set, it will ignore decorations specific to validation (i.e. warnings, errors).</param>
        /// <returns>An array of results.</returns>
        IModelDecoration[] GetLineDecorations(double lineNumber, double? ownerId, bool? filterOutValidation);

        /// <summary>
        /// Returns the column before the first non whitespace character for line at `lineNumber`.
        /// Returns 0 if line is empty or contains only whitespace.
        /// </summary>
        /// <returns>A numeric value.</returns>
        double GetLineFirstNonWhitespaceColumn(double lineNumber);

        /// <summary>
        /// Returns the column after the last non whitespace character for line at `lineNumber`.
        /// Returns 0 if line is empty or contains only whitespace.
        /// </summary>
        /// <returns>A numeric value.</returns>
        double GetLineLastNonWhitespaceColumn(double lineNumber);

        /// <summary>
        /// Get the text length for a certain line.
        /// </summary>
        /// <returns>A numeric value.</returns>
        double GetLineLength(double lineNumber);

        /// <summary>
        /// Get the maximum legal column for line at `lineNumber`
        /// </summary>
        /// <returns>A numeric value.</returns>
        double GetLineMaxColumn(double lineNumber);

        /// <summary>
        /// Get the minimum legal column for line at `lineNumber`
        /// </summary>
        /// <returns>A numeric value.</returns>
        double GetLineMinColumn(double lineNumber);

        /// <summary>
        /// Get the text for all lines.
        /// </summary>
        /// <returns>An array of results.</returns>
        string[] GetLinesContent();

        /// <summary>
        /// Gets all the decorations for the lines between `startLineNumber` and `endLineNumber` as an array.
        /// </summary>
        /// <param name="startLineNumber">The start line number</param>
        /// <param name="endLineNumber">The end line number</param>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <param name="filterOutValidation">If set, it will ignore decorations specific to validation (i.e. warnings, errors).</param>
        /// <returns>An array of results.</returns>
        IModelDecoration[] GetLinesDecorations(double startLineNumber, double endLineNumber, double? ownerId, bool? filterOutValidation);

        /// <summary>
        /// Converts the position to a zero-based offset.
        ///
        /// The position will be [adjusted](#TextDocument.validatePosition).
        /// </summary>
        /// <param name="position">A position.</param>
        /// <returns>A numeric value.</returns>
        double GetOffsetAt(IPosition position);

        /// <summary>
        /// Get the resolved options for this model.
        /// </summary>
        /// <returns>A TextModelResolvedOptions instance.</returns>
        TextModelResolvedOptions GetOptions();

        /// <summary>
        /// Gets all the decorations that should be rendered in the overview ruler as an array.
        /// </summary>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <param name="filterOutValidation">If set, it will ignore decorations specific to validation (i.e. warnings, errors).</param>
        /// <returns>An array of results.</returns>
        IModelDecoration[] GetOverviewRulerDecorations(double? ownerId, bool? filterOutValidation);

        /// <summary>
        /// Converts a zero-based offset to a position.
        /// </summary>
        /// <param name="offset">A zero-based offset.</param>
        /// <returns>A Position instance.</returns>
        Position GetPositionAt(double offset);

        /// <summary>
        /// Get the text stored in this model.
        /// </summary>
        /// <param name="eol">The end of line character preference. Defaults to `EndOfLinePreference.TextDefined`.</param>
        /// <returns>A string value.</returns>
        string GetValue(EndOfLinePreference? eol, bool? preserveBOM);

        /// <summary>
        /// Get the text in a certain range.
        /// </summary>
        /// <param name="range">The range describing what text to get.</param>
        /// <param name="eol">The end of line character preference. This will only be used for multiline ranges. Defaults to `EndOfLinePreference.TextDefined`.</param>
        /// <returns>A string value.</returns>
        string GetValueInRange(IRange range, EndOfLinePreference? eol);

        /// <summary>
        /// Get the length of the text stored in this model.
        /// </summary>
        /// <returns>A numeric value.</returns>
        double GetValueLength(EndOfLinePreference? eol, bool? preserveBOM);

        /// <summary>
        /// Get the length of text in a certain range.
        /// </summary>
        /// <param name="range">The range describing what text length to get.</param>
        /// <returns>A numeric value.</returns>
        double GetValueLengthInRange(IRange range, EndOfLinePreference? eol);

        /// <summary>
        /// Get the current version id of the model.
        /// Anytime a change happens to the model (even undo/redo),
        /// the version id is incremented.
        /// </summary>
        /// <returns>A numeric value.</returns>
        double GetVersionId();

        /// <summary>
        /// Get the word under or besides `position`.
        /// </summary>
        /// <param name="position">The position to look for a word.</param>
        IWordAtPosition GetWordAtPosition(IPosition position);

        /// <summary>
        /// Get the word under or besides `position` trimmed to `position`.column
        /// </summary>
        /// <param name="position">The position to look for a word.</param>
        /// <returns>A IWordAtPosition instance.</returns>
        IWordAtPosition GetWordUntilPosition(IPosition position);

        /// <summary>
        /// Returns if this model is attached to an editor or not.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        bool IsAttachedToEditor();

        /// <summary>
        /// Returns if the model was disposed or not.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        bool IsDisposed();

        /// <summary>
        /// Advances the given position by the given offset (negative offsets are also accepted)
        /// and returns it as a new valid position.
        ///
        /// If the offset and position are such that their combination goes beyond the beginning or
        /// end of the model, throws an exception.
        ///
        /// If the offset is such that the new position would be in the middle of a multi-byte
        /// line terminator, throws an exception.
        /// </summary>
        /// <returns>A Position instance.</returns>
        Position ModifyPosition(IPosition position, double offset);

        /// <summary>
        /// Normalize a string containing whitespace according to indentation rules (converts to spaces or to tabs).
        /// </summary>
        /// <returns>A string value.</returns>
        string NormalizeIndentation(string str);

        /// <summary>
        /// An event emitted when the contents of the model have changed.
        /// </summary>
        /// <returns>A IDisposable instance.</returns>
        IDisposable OnDidChangeContent(object listener);

        /// <summary>
        /// Open the current undo-redo element.
        /// This offers a way to remove the current undo/redo stop point.
        /// </summary>
        void PopStackElement();

        /// <summary>
        /// Push edit operations, basically editing the model. This is the preferred way
        /// of editing the model. The edit operations will land on the undo stack.
        /// </summary>
        /// <param name="beforeCursorState">The cursor state before the edit operations. This cursor state will be returned when `undo` or `redo` are invoked.</param>
        /// <param name="editOperations">The edit operations.</param>
        /// <param name="cursorStateComputer">A callback that can compute the resulting cursors state after the edit operations have been executed.</param>
        Selection[] PushEditOperations(Selection[] beforeCursorState, IIdentifiedSingleEditOperation[] editOperations, ICursorStateComputer cursorStateComputer);

        /// <summary>
        /// Change the end of line sequence. This is the preferred way of
        /// changing the eol sequence. This will land on the undo stack.
        /// </summary>
        void PushEOL(EndOfLineSequence eol);

        /// <summary>
        /// Close the current undo-redo element.
        /// This offers a way to create an undo/redo stop point.
        /// </summary>
        void PushStackElement();

        /// <summary>
        /// Change the end of line sequence without recording in the undo stack.
        /// This can have dire consequences on the undo stack! See
        /// </summary>
        void SetEOL(EndOfLineSequence eol);

        /// <summary>
        /// Replace the entire text buffer value contained in this model.
        /// </summary>
        void SetValue(object newValue);

        /// <summary>
        /// Change the options of this model.
        /// </summary>
        void UpdateOptions(ITextModelUpdateOptions newOpts);

        /// <summary>
        /// Create a valid position.
        /// </summary>
        /// <returns>A Position instance.</returns>
        Position ValidatePosition(IPosition position);

        /// <summary>
        /// Create a valid range.
        /// </summary>
        /// <returns>A Range instance.</returns>
        Range ValidateRange(IRange range);

    }
}
