// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ITokenThemeRule.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<ITokenThemeRule, TokenThemeRule>))]
    public interface ITokenThemeRule
    {
        string? Background { get; set; }

        string? FontStyle { get; set; }

        string? Foreground { get; set; }

        string Token { get; set; }

    }
}
