// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for unicode highlighting.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IUnicodeHighlightOptions.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IUnicodeHighlightOptions, UnicodeHighlightOptions>))]
    public interface IUnicodeHighlightOptions
    {
        /// <summary>
        /// Defines allowed characters that are not being highlighted.
        /// </summary>
        object? AllowedCharacters { get; set; }

        /// <summary>
        /// Unicode characters that are common in allowed locales are not being highlighted.
        /// </summary>
        object? AllowedLocales { get; set; }

        /// <summary>
        /// Controls whether characters are highlighted that can be confused with basic ASCII characters, except those that are common in the current user locale.
        /// </summary>
        bool? AmbiguousCharacters { get; set; }

        /// <summary>
        /// Controls whether characters in comments should also be subject to unicode highlighting.
        /// </summary>
        object? IncludeComments { get; set; }

        /// <summary>
        /// Controls whether characters in strings should also be subject to unicode highlighting.
        /// </summary>
        object? IncludeStrings { get; set; }

        /// <summary>
        /// Controls whether characters that just reserve space or have no width at all are highlighted.
        /// </summary>
        bool? InvisibleCharacters { get; set; }

        /// <summary>
        /// Controls whether all non-basic ASCII characters are highlighted. Only characters between U+0020 and U+007E, tab, line-feed and carriage-return are considered basic ASCII.
        /// </summary>
        object? NonBasicASCII { get; set; }

    }
}
