// <auto-generated />
#nullable enable
using Monaco;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A (serializable) state of the view.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IViewState.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IViewState, ViewState>))]
    public interface IViewState
    {
        IPosition FirstPosition { get; set; }

        double FirstPositionDeltaTop { get; set; }

        double ScrollLeft { get; set; }

        /// <summary>
        /// written by previous versions
        /// </summary>
        double? ScrollTop { get; set; }

        /// <summary>
        /// written by previous versions
        /// </summary>
        double? ScrollTopWithoutViewZones { get; set; }

    }
}
