// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// A view zone is a full horizontal rectangle that 'pushes' text down.
    /// The editor reserves space for view zones when rendering.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IViewZone.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IViewZone, ViewZone>))]
    public interface IViewZone
    {
        /// <summary>
        /// The column after which this zone should appear.
        /// If not set, the maxLineColumn of `afterLineNumber` will be used.
        /// This is relevant for wrapped lines.
        /// </summary>
        double? AfterColumn { get; set; }

        /// <summary>
        /// If the `afterColumn` has multiple view columns, the affinity specifies which one to use. Defaults to `none`.
        /// </summary>
        PositionAffinity? AfterColumnAffinity { get; set; }

        /// <summary>
        /// The line number after which this zone should appear.
        /// Use 0 to place a view zone before the first line number.
        /// </summary>
        double AfterLineNumber { get; set; }

        /// <summary>
        /// The dom node of the view zone
        /// </summary>
        object DomNode { get; set; }

        /// <summary>
        /// The height in lines of the view zone.
        /// If specified, `heightInPx` will be used instead of this.
        /// If neither `heightInPx` nor `heightInLines` is specified, a default of `heightInLines` = 1 will be chosen.
        /// </summary>
        double? HeightInLines { get; set; }

        /// <summary>
        /// The height in px of the view zone.
        /// If this is set, the editor will give preference to it rather than `heightInLines` above.
        /// If neither `heightInPx` nor `heightInLines` is specified, a default of `heightInLines` = 1 will be chosen.
        /// </summary>
        double? HeightInPx { get; set; }

        /// <summary>
        /// An optional dom node for the view zone that will be placed in the margin area.
        /// </summary>
        object? MarginDomNode { get; set; }

        /// <summary>
        /// The minimum width in px of the view zone.
        /// If this is set, the editor will ensure that the scroll width is &gt;= than this value.
        /// </summary>
        double? MinWidthInPx { get; set; }

        /// <summary>
        /// Callback which gives the height in pixels of the view zone.
        /// </summary>
        object? OnComputedHeight { get; set; }

        /// <summary>
        /// Callback which gives the relative top of the view zone as it appears (taking scrolling into account).
        /// </summary>
        object? OnDomNodeTop { get; set; }

        /// <summary>
        /// Tiebreaker that is used when multiple view zones want to be after the same line.
        /// Defaults to `afterColumn` otherwise 10000;
        /// </summary>
        double? Ordinal { get; set; }

        /// <summary>
        /// Render the zone even when its line is hidden.
        /// </summary>
        bool? ShowInHiddenAreas { get; set; }

        /// <summary>
        /// Suppress mouse down events.
        /// If set, the editor will attach a mouse down listener to the view zone and .preventDefault on it.
        /// Defaults to false
        /// </summary>
        bool? SuppressMouseDown { get; set; }

    }
}
