// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <summary>
    /// Word inside a model.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IWordAtPosition.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(Monaco.Helpers.InterfaceToClassConverter<IWordAtPosition, WordAtPosition>))]
    public interface IWordAtPosition
    {
        /// <summary>
        /// The column where the word ends.
        /// </summary>
        double EndColumn { get; }

        /// <summary>
        /// The column where the word starts.
        /// </summary>
        double StartColumn { get; }

        /// <summary>
        /// The word.
        /// </summary>
        string Word { get; }

    }
}
