// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
using Monaco.Helpers;

namespace Monaco.Editor
{
    /// <summary>
    /// <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor_editor_api.editor.IWordAtPosition.html">monaco.editor.IWordAtPosition</see>
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IWordAtPosition.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(InterfaceToClassConverter<IWordAtPosition, WordAtPosition>))]
    public partial interface IWordAtPosition
    {
        /// <summary>
        /// Column where the word ends.
        /// </summary>
        uint EndColumn { get; }

        /// <summary>
        /// Column where the word starts.
        /// </summary>
        uint StartColumn { get; }

        /// <summary>
        /// The word.
        /// </summary>
        string? Word { get; }
    }
}
