// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <inheritdoc cref="ILineChange" />
    public sealed partial class LineChange : Change, ILineChange
    {
        /// <summary>
        /// Character-level changes within this line change, or <see langword="null"/> when
        /// Monaco did not compute them (for example for a pure insertion or deletion).
        /// </summary>
        [JsonInclude]
        public CharChange[]? CharChanges { get; internal set; }

        /// <inheritdoc />
        ICharChange[]? ILineChange.CharChanges => CharChanges;
    }
}
