// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ILocalizedString.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class LocalizedString : ILocalizedString
    {
        public string Original { get; set; }

        public string Value { get; set; }

    }
}
