// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// Section header style.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/editor.MinimapSectionHeaderStyle.html">Monaco API</see> for more details.
    /// </remarks>
    public enum MinimapSectionHeaderStyle
    {
        Normal = 1,
        Underlined = 2
    }
}
