// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <summary>
    /// An event describing that an editor has had its model reset (i.e. `editor.setModel()`).
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ModelChangedEvent : IModelChangedEvent
    {
        /// <summary>
        /// The `uri` of the new model or null.
        /// </summary>
        public Uri NewModelUrl { get; set; }

        /// <summary>
        /// The `uri` of the previous model or null.
        /// </summary>
        public Uri OldModelUrl { get; set; }

    }
}
