// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// An event describing that the current language associated with a model has changed.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelLanguageChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ModelLanguageChangedEvent : IModelLanguageChangedEvent
    {
        /// <summary>
        /// New language
        /// </summary>
        public string NewLanguage { get; set; }

        /// <summary>
        /// Previous language
        /// </summary>
        public string OldLanguage { get; set; }

        /// <summary>
        /// Source of the call that caused the event.
        /// </summary>
        public string Source { get; set; }

    }
}
