// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// Options for rendering a model decoration in the overview ruler.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelDecorationOverviewRulerOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ModelDecorationOverviewRulerOptions : IModelDecorationOverviewRulerOptions
    {
        /// <summary>
        /// The position in the overview ruler.
        /// </summary>
        public OverviewRulerLane Position { get; set; }

    }
}
