// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <summary>
    /// A decoration in the model.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelDecoration.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ModelDecoration : IModelDecoration
    {
        /// <summary>
        /// Identifier for a decoration.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Options associated with this decoration.
        /// </summary>
        public IModelDecorationOptions Options { get; set; }

        /// <summary>
        /// Identifier for a decoration's owner.
        /// </summary>
        public double OwnerId { get; set; }

        /// <summary>
        /// Range that this decoration covers.
        /// </summary>
        public Range Range { get; set; }

    }
}
