// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelOptionsChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ModelOptionsChangedEvent : IModelOptionsChangedEvent
    {
        public bool IndentSize { get; set; }

        public bool InsertSpaces { get; set; }

        public bool TabSize { get; set; }

        public bool TrimAutoWhitespace { get; set; }

    }
}
