// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelContentChange.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ModelContentChange : IModelContentChange
    {
        /// <summary>
        /// The range that got replaced.
        /// </summary>
        public IRange Range { get; set; }

        /// <summary>
        /// The length of the range that got replaced.
        /// </summary>
        public double RangeLength { get; set; }

        /// <summary>
        /// The offset of the range that got replaced.
        /// </summary>
        public double RangeOffset { get; set; }

        /// <summary>
        /// The new text for the range.
        /// </summary>
        public string Text { get; set; }

    }
}
