// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelDecorationGlyphMarginOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ModelDecorationGlyphMarginOptions : IModelDecorationGlyphMarginOptions
    {
        /// <summary>
        /// /**
        ///          * Whether the glyph margin lane in {@link position}should be rendered even
        ///          * outside of this decoration's range.
        /// </summary>
        public bool? PersistLane { get; set; }

        /// <summary>
        /// The position in the glyph margin.
        /// </summary>
        public GlyphMarginLane Position { get; set; }

    }
}
