// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// Options for rendering a model decoration in the minimap.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelDecorationMinimapOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ModelDecorationMinimapOptions : IModelDecorationMinimapOptions
    {
        /// <summary>
        /// The position in the minimap.
        /// </summary>
        public MinimapPosition Position { get; set; }

        /// <summary>
        /// If the decoration is for a section header, which header style.
        /// </summary>
        public MinimapSectionHeaderStyle? SectionHeaderStyle { get; set; }

        /// <summary>
        /// If the decoration is for a section header, the header text.
        /// </summary>
        public string? SectionHeaderText { get; set; }

    }
}
