// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// An event describing that model decorations have changed.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IModelDecorationsChangedEvent.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ModelDecorationsChangedEvent : IModelDecorationsChangedEvent
    {
        public bool AffectsGlyphMargin { get; set; }

        public bool AffectsLineNumber { get; set; }

        public bool AffectsMinimap { get; set; }

        public bool AffectsOverviewRuler { get; set; }

    }
}
