// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetUnknown.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class MouseTargetUnknown : IMouseTargetUnknown
    {
        public MouseTargetType.UNKNOWN Type { get; set; }

    }
}
