// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetMargin.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class MouseTargetMargin : IMouseTargetMargin
    {
        public IMouseTargetMarginData Detail { get; set; }

        public Position Position { get; set; }

        public Range Range { get; set; }

        public object Type { get; set; }

    }
}
