// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetViewZoneData.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class MouseTargetViewZoneData : IMouseTargetViewZoneData
    {
        public double AfterLineNumber { get; set; }

        public Position Position { get; set; }

        public Position PositionAfter { get; set; }

        public Position PositionBefore { get; set; }

        public string ViewZoneId { get; set; }

    }
}
