// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetViewZone.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class MouseTargetViewZone : IMouseTargetViewZone
    {
        public IMouseTargetViewZoneData Detail { get; set; }

        public Position Position { get; set; }

        public Range Range { get; set; }

        public object Type { get; set; }

    }
}
