// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetContentText.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class MouseTargetContentText : IMouseTargetContentText
    {
        public IMouseTargetContentTextData Detail { get; set; }

        public Position Position { get; set; }

        public Range Range { get; set; }

        public MouseTargetType.CONTENT_TEXT Type { get; set; }

    }
}
