// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetMarginData.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class MouseTargetMarginData : IMouseTargetMarginData
    {
        public GlyphMarginLane? GlyphMarginLane { get; set; }

        public double GlyphMarginLeft { get; set; }

        public double GlyphMarginWidth { get; set; }

        public bool IsAfterLines { get; set; }

        public double LineNumbersWidth { get; set; }

        public double OffsetX { get; set; }

    }
}
