// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetContentEmpty.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class MouseTargetContentEmpty : IMouseTargetContentEmpty
    {
        public IMouseTargetContentEmptyData Detail { get; set; }

        public Position Position { get; set; }

        public Range Range { get; set; }

        public MouseTargetType.CONTENT_EMPTY Type { get; set; }

    }
}
