// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetTextarea.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class MouseTargetTextarea : IMouseTargetTextarea
    {
        public object Position { get; set; }

        public object Range { get; set; }

        public MouseTargetType.TEXTAREA Type { get; set; }

    }
}
