// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IMouseTargetContentWidget.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class MouseTargetContentWidget : IMouseTargetContentWidget
    {
        public string Detail { get; set; }

        public object Position { get; set; }

        public object Range { get; set; }

        public MouseTargetType.CONTENT_WIDGET Type { get; set; }

    }
}
