// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.INewScrollPosition.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class NewScrollPosition : INewScrollPosition
    {
        public double? ScrollLeft { get; set; }

        public double? ScrollTop { get; set; }

    }
}
