// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// Vertical Lane in the overview ruler of the editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/editor.OverviewRulerLane.html">Monaco API</see> for more details.
    /// </remarks>
    public enum OverviewRulerLane
    {
        Center = 2,
        Full = 7,
        Left = 1,
        Right = 4
    }
}
