// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <summary>
    /// A paste event originating from the editor.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IPasteEvent.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class PasteEvent : IPasteEvent
    {
        public ClipboardEvent? ClipboardEvent { get; set; }

        public string LanguageId { get; set; }

        public Range Range { get; set; }

    }
}
