// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/editor.PositionAffinity.html">Monaco API</see> for more details.
    /// </remarks>
    public enum PositionAffinity
    {
        /// <summary>
        /// Prefers the left most position.
        /// </summary>
        Left = 0,
        /// <summary>
        /// If the given position is on injected text, prefers the position left of it.
        /// </summary>
        LeftOfInjectedText = 3,
        /// <summary>
        /// No preference.
        /// </summary>
        None = 2,
        /// <summary>
        /// Prefers the right most position.
        /// </summary>
        Right = 1,
        /// <summary>
        /// If the given position is on injected text, prefers the position right of it.
        /// </summary>
        RightOfInjectedText = 4
    }
}
