// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// Configuration options for quick suggestions
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IQuickSuggestionsOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class QuickSuggestionsOptions : IQuickSuggestionsOptions
    {
        public object? Comments { get; set; }

        public object? Other { get; set; }

        public object? Strings { get; set; }

    }
}
