// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/editor.RenderMinimap.html">Monaco API</see> for more details.
    /// </remarks>
    public enum RenderMinimap
    {
        Blocks = 2,
        None = 0,
        Text = 1
    }
}
