// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/editor.RenderLineNumbersType.html">Monaco API</see> for more details.
    /// </remarks>
    public enum RenderLineNumbersType
    {
        Custom = 4,
        Interval = 3,
        Off = 0,
        On = 1,
        Relative = 2
    }
}
