// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IRulerOption.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class RulerOption : IRulerOption
    {
        public string Color { get; set; }

        public double Column { get; set; }

    }
}
