// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/editor.ScrollType.html">Monaco API</see> for more details.
    /// </remarks>
    public enum ScrollType
    {
        Immediate = 1,
        Smooth = 0
    }
}
