// <auto-generated />
#nullable enable
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/editor.ShowLightbulbIconMode.html">Monaco API</see> for more details.
    /// </remarks>
    [JsonConverter(typeof(JsonStringEnumConverter<ShowLightbulbIconMode>))]
    public enum ShowLightbulbIconMode
    {
        [JsonStringEnumMemberName("off")]
        [EnumMember(Value = "off")]
        Off,
        [JsonStringEnumMemberName("on")]
        [EnumMember(Value = "on")]
        On,
        [JsonStringEnumMemberName("onCode")]
        [EnumMember(Value = "onCode")]
        OnCode
    }
}
