// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IStandaloneDiffEditor.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class StandaloneDiffEditor : IStandaloneDiffEditor
    {
        /// <returns>A IDisposable instance.</returns>
        public IDisposable AddAction(IActionDescriptor descriptor) => throw new NotImplementedException();

        public string AddCommand(double keybinding, ICommandHandler handler, string? context) => throw new NotImplementedException();

        /// <returns>A IContextKey instance.</returns>
        public IContextKey<T> CreateContextKey<T>(string key, T defaultValue) => throw new NotImplementedException();

        /// <returns>A IStandaloneCodeEditor instance.</returns>
        public IStandaloneCodeEditor GetModifiedEditor() => throw new NotImplementedException();

        /// <returns>A IStandaloneCodeEditor instance.</returns>
        public IStandaloneCodeEditor GetOriginalEditor() => throw new NotImplementedException();

    }
}
