// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <summary>
    /// A model.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ITextModel.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class TextModel : ITextModel
    {
        /// <summary>
        /// A unique identifier associated with this model.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// An event emitted when the model has been attached to the first editor or detached from the last editor.
        /// </summary>
        public IEvent<object> OnDidChangeAttached { get; set; }

        /// <summary>
        /// An event emitted when decorations of the model have changed.
        /// </summary>
        public IEvent<IModelDecorationsChangedEvent> OnDidChangeDecorations { get; set; }

        /// <summary>
        /// An event emitted when the language associated with the model has changed.
        /// </summary>
        public IEvent<IModelLanguageChangedEvent> OnDidChangeLanguage { get; set; }

        /// <summary>
        /// An event emitted when the language configuration associated with the model has changed.
        /// </summary>
        public IEvent<IModelLanguageConfigurationChangedEvent> OnDidChangeLanguageConfiguration { get; set; }

        /// <summary>
        /// An event emitted when the model options have changed.
        /// </summary>
        public IEvent<IModelOptionsChangedEvent> OnDidChangeOptions { get; set; }

        /// <summary>
        /// An event emitted right before disposing the model.
        /// </summary>
        public IEvent<object> OnWillDispose { get; set; }

        /// <summary>
        /// Gets the resource associated with this editor model.
        /// </summary>
        public Uri Uri { get; set; }

        /// <summary>
        /// Edit the model without adding the edits to the undo stack.
        /// This can have dire consequences on the undo stack! See
        /// </summary>
        /// <param name="operations">The edit operations.</param>
        public void ApplyEdits(IIdentifiedSingleEditOperation[] operations) => throw new NotImplementedException();

        public void ApplyEdits(IIdentifiedSingleEditOperation[] operations, bool computeUndoEdits) => throw new NotImplementedException();

        /// <returns>An array of results.</returns>
        public IValidEditOperation[] ApplyEdits(IIdentifiedSingleEditOperation[] operations, bool computeUndoEdits) => throw new NotImplementedException();

        /// <summary>
        /// Get the text stored in this model.
        /// </summary>
        /// <returns>A ITextSnapshot instance.</returns>
        public ITextSnapshot CreateSnapshot(bool? preserveBOM) => throw new NotImplementedException();

        /// <summary>
        /// Perform a minimum amount of operations, in order to transform the decorations
        /// identified by `oldDecorations` to the decorations described by `newDecorations`
        /// and returns the new identifiers associated with the resulting decorations.
        /// </summary>
        /// <param name="oldDecorations">Array containing previous decorations identifiers.</param>
        /// <param name="newDecorations">Array describing what decorations should result after the call.</param>
        /// <param name="ownerId">Identifies the editor id in which these decorations should appear. If no `ownerId` is provided, the decorations will appear in all editors that attach this model.</param>
        /// <returns>An array of results.</returns>
        public string[] DeltaDecorations(string[] oldDecorations, IModelDeltaDecoration[] newDecorations, double? ownerId) => throw new NotImplementedException();

        /// <summary>
        /// Detect the indentation options for this model from its content.
        /// </summary>
        public void DetectIndentation(bool defaultInsertSpaces, double defaultTabSize) => throw new NotImplementedException();

        /// <summary>
        /// Destroy this model.
        /// </summary>
        public void Dispose() => throw new NotImplementedException();

        /// <summary>
        /// Search the model.
        /// </summary>
        /// <param name="searchString">The string used to search. If it is a regular expression, set `isRegex` to true.</param>
        /// <param name="searchOnlyEditableRange">Limit the searching to only search inside the editable range of the model.</param>
        /// <param name="isRegex">Used to indicate that `searchString` is a regular expression.</param>
        /// <param name="matchCase">Force the matching to match lower/upper case exactly.</param>
        /// <param name="wordSeparators">Force the matching to match entire words only. Pass null otherwise.</param>
        /// <param name="captureMatches">The result will contain the captured groups.</param>
        /// <param name="limitResultCount">Limit the number of results</param>
        /// <returns>An array of results.</returns>
        public FindMatch[] FindMatches(string searchString, bool searchOnlyEditableRange, bool isRegex, bool matchCase, string wordSeparators, bool captureMatches, double? limitResultCount) => throw new NotImplementedException();

        /// <summary>
        /// Search the model.
        /// </summary>
        /// <param name="searchString">The string used to search. If it is a regular expression, set `isRegex` to true.</param>
        /// <param name="searchScope">Limit the searching to only search inside these ranges.</param>
        /// <param name="isRegex">Used to indicate that `searchString` is a regular expression.</param>
        /// <param name="matchCase">Force the matching to match lower/upper case exactly.</param>
        /// <param name="wordSeparators">Force the matching to match entire words only. Pass null otherwise.</param>
        /// <param name="captureMatches">The result will contain the captured groups.</param>
        /// <param name="limitResultCount">Limit the number of results</param>
        /// <returns>An array of results.</returns>
        public FindMatch[] FindMatches(string searchString, object searchScope, bool isRegex, bool matchCase, string wordSeparators, bool captureMatches, double? limitResultCount) => throw new NotImplementedException();

        /// <summary>
        /// Search the model for the next match. Loops to the beginning of the model if needed.
        /// </summary>
        /// <param name="searchString">The string used to search. If it is a regular expression, set `isRegex` to true.</param>
        /// <param name="searchStart">Start the searching at the specified position.</param>
        /// <param name="isRegex">Used to indicate that `searchString` is a regular expression.</param>
        /// <param name="matchCase">Force the matching to match lower/upper case exactly.</param>
        /// <param name="wordSeparators">Force the matching to match entire words only. Pass null otherwise.</param>
        /// <param name="captureMatches">The result will contain the captured groups.</param>
        public FindMatch FindNextMatch(string searchString, IPosition searchStart, bool isRegex, bool matchCase, string wordSeparators, bool captureMatches) => throw new NotImplementedException();

        /// <summary>
        /// Search the model for the previous match. Loops to the end of the model if needed.
        /// </summary>
        /// <param name="searchString">The string used to search. If it is a regular expression, set `isRegex` to true.</param>
        /// <param name="searchStart">Start the searching at the specified position.</param>
        /// <param name="isRegex">Used to indicate that `searchString` is a regular expression.</param>
        /// <param name="matchCase">Force the matching to match lower/upper case exactly.</param>
        /// <param name="wordSeparators">Force the matching to match entire words only. Pass null otherwise.</param>
        /// <param name="captureMatches">The result will contain the captured groups.</param>
        public FindMatch FindPreviousMatch(string searchString, IPosition searchStart, bool isRegex, bool matchCase, string wordSeparators, bool captureMatches) => throw new NotImplementedException();

        /// <summary>
        /// Gets all the decorations as an array.
        /// </summary>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <param name="filterOutValidation">If set, it will ignore decorations specific to validation (i.e. warnings, errors).</param>
        /// <returns>An array of results.</returns>
        public IModelDecoration[] GetAllDecorations(double? ownerId, bool? filterOutValidation) => throw new NotImplementedException();

        /// <summary>
        /// Gets all decorations that render in the glyph margin as an array.
        /// </summary>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <returns>An array of results.</returns>
        public IModelDecoration[] GetAllMarginDecorations(double? ownerId) => throw new NotImplementedException();

        /// <summary>
        /// Get the alternative version id of the model.
        /// This alternative version id is not always incremented,
        /// it will return the same values in the case of undo-redo.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetAlternativeVersionId() => throw new NotImplementedException();

        /// <summary>
        /// Get the character count of text in a certain range.
        /// </summary>
        /// <param name="range">The range describing what text length to get.</param>
        /// <returns>A numeric value.</returns>
        public double GetCharacterCountInRange(IRange range, EndOfLinePreference? eol) => throw new NotImplementedException();

        /// <summary>
        /// Get the options associated with a decoration.
        /// </summary>
        /// <param name="id">The decoration id.</param>
        public IModelDecorationOptions GetDecorationOptions(string id) => throw new NotImplementedException();

        /// <summary>
        /// Get the range associated with a decoration.
        /// </summary>
        /// <param name="id">The decoration id.</param>
        public Range GetDecorationRange(string id) => throw new NotImplementedException();

        /// <summary>
        /// Gets all the decorations in a range as an array. Only `startLineNumber` and `endLineNumber` from `range` are used for filtering.
        /// So for now it returns all the decorations on the same line as `range`.
        /// </summary>
        /// <param name="range">The range to search in</param>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <param name="filterOutValidation">If set, it will ignore decorations specific to validation (i.e. warnings, errors).</param>
        /// <param name="onlyMinimapDecorations">If set, it will return only decorations that render in the minimap.</param>
        /// <param name="onlyMarginDecorations">If set, it will return only decorations that render in the glyph margin.</param>
        /// <returns>An array of results.</returns>
        public IModelDecoration[] GetDecorationsInRange(IRange range, double? ownerId, bool? filterOutValidation, bool? onlyMinimapDecorations, bool? onlyMarginDecorations) => throw new NotImplementedException();

        /// <summary>
        /// Get the end of line sequence predominantly used in the text buffer.
        /// </summary>
        /// <returns>A EndOfLineSequence instance.</returns>
        public EndOfLineSequence GetEndOfLineSequence() => throw new NotImplementedException();

        /// <summary>
        /// Get the end of line sequence predominantly used in the text buffer.
        /// </summary>
        /// <returns>A string value.</returns>
        public string GetEOL() => throw new NotImplementedException();

        /// <summary>
        /// Get a range covering the entire model.
        /// </summary>
        /// <returns>A Range instance.</returns>
        public Range GetFullModelRange() => throw new NotImplementedException();

        /// <summary>
        /// Gets all the decorations that contain injected text.
        /// </summary>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <returns>An array of results.</returns>
        public IModelDecoration[] GetInjectedTextDecorations(double? ownerId) => throw new NotImplementedException();

        /// <summary>
        /// Get the language associated with this model.
        /// </summary>
        /// <returns>A string value.</returns>
        public string GetLanguageId() => throw new NotImplementedException();

        /// <summary>
        /// Get the text for a certain line.
        /// </summary>
        /// <returns>A string value.</returns>
        public string GetLineContent(double lineNumber) => throw new NotImplementedException();

        /// <summary>
        /// Get the number of lines in the model.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetLineCount() => throw new NotImplementedException();

        /// <summary>
        /// Gets all the decorations for the line `lineNumber` as an array.
        /// </summary>
        /// <param name="lineNumber">The line number</param>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <param name="filterOutValidation">If set, it will ignore decorations specific to validation (i.e. warnings, errors).</param>
        /// <returns>An array of results.</returns>
        public IModelDecoration[] GetLineDecorations(double lineNumber, double? ownerId, bool? filterOutValidation) => throw new NotImplementedException();

        /// <summary>
        /// Returns the column before the first non whitespace character for line at `lineNumber`.
        /// Returns 0 if line is empty or contains only whitespace.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetLineFirstNonWhitespaceColumn(double lineNumber) => throw new NotImplementedException();

        /// <summary>
        /// Returns the column after the last non whitespace character for line at `lineNumber`.
        /// Returns 0 if line is empty or contains only whitespace.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetLineLastNonWhitespaceColumn(double lineNumber) => throw new NotImplementedException();

        /// <summary>
        /// Get the text length for a certain line.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetLineLength(double lineNumber) => throw new NotImplementedException();

        /// <summary>
        /// Get the maximum legal column for line at `lineNumber`
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetLineMaxColumn(double lineNumber) => throw new NotImplementedException();

        /// <summary>
        /// Get the minimum legal column for line at `lineNumber`
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetLineMinColumn(double lineNumber) => throw new NotImplementedException();

        /// <summary>
        /// Get the text for all lines.
        /// </summary>
        /// <returns>An array of results.</returns>
        public string[] GetLinesContent() => throw new NotImplementedException();

        /// <summary>
        /// Gets all the decorations for the lines between `startLineNumber` and `endLineNumber` as an array.
        /// </summary>
        /// <param name="startLineNumber">The start line number</param>
        /// <param name="endLineNumber">The end line number</param>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <param name="filterOutValidation">If set, it will ignore decorations specific to validation (i.e. warnings, errors).</param>
        /// <returns>An array of results.</returns>
        public IModelDecoration[] GetLinesDecorations(double startLineNumber, double endLineNumber, double? ownerId, bool? filterOutValidation) => throw new NotImplementedException();

        /// <summary>
        /// Converts the position to a zero-based offset.
        ///
        /// The position will be [adjusted](#TextDocument.validatePosition).
        /// </summary>
        /// <param name="position">A position.</param>
        /// <returns>A numeric value.</returns>
        public double GetOffsetAt(IPosition position) => throw new NotImplementedException();

        /// <summary>
        /// Get the resolved options for this model.
        /// </summary>
        /// <returns>A TextModelResolvedOptions instance.</returns>
        public TextModelResolvedOptions GetOptions() => throw new NotImplementedException();

        /// <summary>
        /// Gets all the decorations that should be rendered in the overview ruler as an array.
        /// </summary>
        /// <param name="ownerId">If set, it will ignore decorations belonging to other owners.</param>
        /// <param name="filterOutValidation">If set, it will ignore decorations specific to validation (i.e. warnings, errors).</param>
        /// <returns>An array of results.</returns>
        public IModelDecoration[] GetOverviewRulerDecorations(double? ownerId, bool? filterOutValidation) => throw new NotImplementedException();

        /// <summary>
        /// Converts a zero-based offset to a position.
        /// </summary>
        /// <param name="offset">A zero-based offset.</param>
        /// <returns>A Position instance.</returns>
        public Position GetPositionAt(double offset) => throw new NotImplementedException();

        /// <summary>
        /// Get the text stored in this model.
        /// </summary>
        /// <param name="eol">The end of line character preference. Defaults to `EndOfLinePreference.TextDefined`.</param>
        /// <returns>A string value.</returns>
        public string GetValue(EndOfLinePreference? eol, bool? preserveBOM) => throw new NotImplementedException();

        /// <summary>
        /// Get the text in a certain range.
        /// </summary>
        /// <param name="range">The range describing what text to get.</param>
        /// <param name="eol">The end of line character preference. This will only be used for multiline ranges. Defaults to `EndOfLinePreference.TextDefined`.</param>
        /// <returns>A string value.</returns>
        public string GetValueInRange(IRange range, EndOfLinePreference? eol) => throw new NotImplementedException();

        /// <summary>
        /// Get the length of the text stored in this model.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetValueLength(EndOfLinePreference? eol, bool? preserveBOM) => throw new NotImplementedException();

        /// <summary>
        /// Get the length of text in a certain range.
        /// </summary>
        /// <param name="range">The range describing what text length to get.</param>
        /// <returns>A numeric value.</returns>
        public double GetValueLengthInRange(IRange range, EndOfLinePreference? eol) => throw new NotImplementedException();

        /// <summary>
        /// Get the current version id of the model.
        /// Anytime a change happens to the model (even undo/redo),
        /// the version id is incremented.
        /// </summary>
        /// <returns>A numeric value.</returns>
        public double GetVersionId() => throw new NotImplementedException();

        /// <summary>
        /// Get the word under or besides `position`.
        /// </summary>
        /// <param name="position">The position to look for a word.</param>
        public IWordAtPosition GetWordAtPosition(IPosition position) => throw new NotImplementedException();

        /// <summary>
        /// Get the word under or besides `position` trimmed to `position`.column
        /// </summary>
        /// <param name="position">The position to look for a word.</param>
        /// <returns>A IWordAtPosition instance.</returns>
        public IWordAtPosition GetWordUntilPosition(IPosition position) => throw new NotImplementedException();

        /// <summary>
        /// Returns if this model is attached to an editor or not.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool IsAttachedToEditor() => throw new NotImplementedException();

        /// <summary>
        /// Returns if the model was disposed or not.
        /// </summary>
        /// <returns>true if the condition is met; otherwise, false.</returns>
        public bool IsDisposed() => throw new NotImplementedException();

        /// <summary>
        /// Advances the given position by the given offset (negative offsets are also accepted)
        /// and returns it as a new valid position.
        ///
        /// If the offset and position are such that their combination goes beyond the beginning or
        /// end of the model, throws an exception.
        ///
        /// If the offset is such that the new position would be in the middle of a multi-byte
        /// line terminator, throws an exception.
        /// </summary>
        /// <returns>A Position instance.</returns>
        public Position ModifyPosition(IPosition position, double offset) => throw new NotImplementedException();

        /// <summary>
        /// Normalize a string containing whitespace according to indentation rules (converts to spaces or to tabs).
        /// </summary>
        /// <returns>A string value.</returns>
        public string NormalizeIndentation(string str) => throw new NotImplementedException();

        /// <summary>
        /// An event emitted when the contents of the model have changed.
        /// </summary>
        /// <returns>A IDisposable instance.</returns>
        public IDisposable OnDidChangeContent(object listener) => throw new NotImplementedException();

        /// <summary>
        /// Open the current undo-redo element.
        /// This offers a way to remove the current undo/redo stop point.
        /// </summary>
        public void PopStackElement() => throw new NotImplementedException();

        /// <summary>
        /// Push edit operations, basically editing the model. This is the preferred way
        /// of editing the model. The edit operations will land on the undo stack.
        /// </summary>
        /// <param name="beforeCursorState">The cursor state before the edit operations. This cursor state will be returned when `undo` or `redo` are invoked.</param>
        /// <param name="editOperations">The edit operations.</param>
        /// <param name="cursorStateComputer">A callback that can compute the resulting cursors state after the edit operations have been executed.</param>
        public Selection[] PushEditOperations(Selection[] beforeCursorState, IIdentifiedSingleEditOperation[] editOperations, ICursorStateComputer cursorStateComputer) => throw new NotImplementedException();

        /// <summary>
        /// Change the end of line sequence. This is the preferred way of
        /// changing the eol sequence. This will land on the undo stack.
        /// </summary>
        public void PushEOL(EndOfLineSequence eol) => throw new NotImplementedException();

        /// <summary>
        /// Close the current undo-redo element.
        /// This offers a way to create an undo/redo stop point.
        /// </summary>
        public void PushStackElement() => throw new NotImplementedException();

        /// <summary>
        /// Change the end of line sequence without recording in the undo stack.
        /// This can have dire consequences on the undo stack! See
        /// </summary>
        public void SetEOL(EndOfLineSequence eol) => throw new NotImplementedException();

        /// <summary>
        /// Replace the entire text buffer value contained in this model.
        /// </summary>
        public void SetValue(object newValue) => throw new NotImplementedException();

        /// <summary>
        /// Change the options of this model.
        /// </summary>
        public void UpdateOptions(ITextModelUpdateOptions newOpts) => throw new NotImplementedException();

        /// <summary>
        /// Create a valid position.
        /// </summary>
        /// <returns>A Position instance.</returns>
        public Position ValidatePosition(IPosition position) => throw new NotImplementedException();

        /// <summary>
        /// Create a valid range.
        /// </summary>
        /// <returns>A Range instance.</returns>
        public Range ValidateRange(IRange range) => throw new NotImplementedException();

    }
}
