// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/classes/editor.TextModelResolvedOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class TextModelResolvedOptions
    {
        public void _textModelResolvedOptionsBrand { get; set; }

        public BracketPairColorizationOptions BracketPairColorizationOptions { get; }

        public DefaultEndOfLine DefaultEOL { get; }

        public double IndentSize { get; }

        public bool InsertSpaces { get; }

        public object OriginalIndentSize { get; }

        public double TabSize { get; }

        public bool TrimAutoWhitespace { get; }

    }
}
