// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// The kind of animation in which the editor's cursor should be rendered.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/editor.TextEditorCursorBlinkingStyle.html">Monaco API</see> for more details.
    /// </remarks>
    public enum TextEditorCursorBlinkingStyle
    {
        /// <summary>
        /// Blinking
        /// </summary>
        Blink = 1,
        /// <summary>
        /// Expand collapse animation on the y axis
        /// </summary>
        Expand = 4,
        /// <summary>
        /// Hidden
        /// </summary>
        Hidden = 0,
        /// <summary>
        /// Blinking with prolonged filled state and smooth fading
        /// </summary>
        Phase = 3,
        /// <summary>
        /// Blinking with smooth fading
        /// </summary>
        Smooth = 2,
        /// <summary>
        /// No-Blinking
        /// </summary>
        Solid = 5
    }
}
