// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ITextModelUpdateOptions.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class TextModelUpdateOptions : ITextModelUpdateOptions
    {
        public BracketPairColorizationOptions? BracketColorizationOptions { get; set; }

        public object? IndentSize { get; set; }

        public bool? InsertSpaces { get; set; }

        public double? TabSize { get; set; }

        public bool? TrimAutoWhitespace { get; set; }

    }
}
