// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ThemeColor.html">Monaco API</see> for more details.
    /// </remarks>
    public interface ThemeColor
    {
        string Id { get; set; }

    }
}
