// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.ITokenThemeRule.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class TokenThemeRule : ITokenThemeRule
    {
        public string? Background { get; set; }

        public string? FontStyle { get; set; }

        public string? Foreground { get; set; }

        public string Token { get; set; }

    }
}
