// <auto-generated />
#nullable enable
using Monaco;

namespace Monaco.Editor
{
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IValidEditOperation.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ValidEditOperation : IValidEditOperation
    {
        /// <summary>
        /// The range to replace. This can be empty to emulate a simple insert.
        /// </summary>
        public Range Range { get; set; }

        /// <summary>
        /// The text to replace with. This can be empty to emulate a simple delete.
        /// </summary>
        public string Text { get; set; }

    }
}
