// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// An accessor that allows for zones to be added or removed.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IViewZoneChangeAccessor.html">Monaco API</see> for more details.
    /// </remarks>
    public sealed class ViewZoneChangeAccessor : IViewZoneChangeAccessor
    {
        /// <summary>
        /// Create a new view zone.
        /// </summary>
        /// <param name="zone">Zone to create</param>
        /// <returns>A string value.</returns>
        public string AddZone(IViewZone zone) => throw new NotImplementedException();

        /// <summary>
        /// Change a zone's position.
        /// The editor will rescan the `afterLineNumber` and `afterColumn` properties of a view zone.
        /// </summary>
        public void LayoutZone(string id) => throw new NotImplementedException();

        /// <summary>
        /// Remove a zone
        /// </summary>
        /// <param name="id">A unique identifier to the view zone, as returned by the `addZone` call.</param>
        public void RemoveZone(string id) => throw new NotImplementedException();

    }
}
