// <auto-generated />
#nullable enable

namespace Monaco.Editor
{
    /// <summary>
    /// Describes how to indent wrapped lines.
    /// </summary>
    /// <remarks>
    /// See <see href="https://microsoft.github.io/monaco-editor/typedoc/enums/editor.WrappingIndent.html">Monaco API</see> for more details.
    /// </remarks>
    public enum WrappingIndent
    {
        /// <summary>
        /// DeepIndent =&gt; wrapped lines get +2 indentation toward the parent.
        /// </summary>
        DeepIndent = 3,
        /// <summary>
        /// Indent =&gt; wrapped lines get +1 indentation toward the parent.
        /// </summary>
        Indent = 2,
        /// <summary>
        /// No indentation =&gt; wrapped lines begin at column 1.
        /// </summary>
        None = 0,
        /// <summary>
        /// Same =&gt; wrapped lines get the same indentation as the parent.
        /// </summary>
        Same = 1
    }
}
